import test from 'node:test'; import assert from 'node:assert/strict'; import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'; import os from 'node:os'; import path from 'node:path';
import { prepareJournalTransaction, commitJournalTransaction, recoverJournalTransaction, readJournalTransaction, rollbackJournalTransaction } from '../../src/security/journal.mjs';
const tmp=()=>mkdtemp(path.join(os.tmpdir(),'bai-sec-journal-'));
test('prepared journal requires explicit recovery decision',async()=>{const r=await tmp();try{await prepareJournalTransaction(r,{tx_id:'TX1',operations:[{path:'a.txt',data:'A'}]});await assert.rejects(()=>recoverJournalTransaction(r,'TX1'),e=>e.code==='SECURITY_JOURNAL_RECOVERY_DECISION_REQUIRED');}finally{await rm(r,{recursive:true,force:true});}});
test('commit atomically moves prepared operations',async()=>{const r=await tmp();try{await prepareJournalTransaction(r,{tx_id:'TX1',operations:[{path:'a.txt',data:'A'},{path:'b.txt',data:'B'}]});const m=await commitJournalTransaction(r,'TX1');assert.equal(m.state,'COMMITTED');assert.equal(await readFile(path.join(r,'a.txt'),'utf8'),'A');assert.equal(await readFile(path.join(r,'b.txt'),'utf8'),'B');}finally{await rm(r,{recursive:true,force:true});}});
test('complete recovery handles partially moved operation',async()=>{const r=await tmp();try{const m=await prepareJournalTransaction(r,{tx_id:'TX1',operations:[{path:'a.txt',data:'A'},{path:'b.txt',data:'B'}]});const {rename}=await import('node:fs/promises');await rename(path.join(r,m.operations[0].temp_path),path.join(r,'a.txt'));const out=await recoverJournalTransaction(r,'TX1',{strategy:'COMPLETE'});assert.equal(out.state,'COMMITTED');assert.equal(await readFile(path.join(r,'b.txt'),'utf8'),'B');}finally{await rm(r,{recursive:true,force:true});}});
test('corrupt temp fails closed',async()=>{const r=await tmp();try{const m=await prepareJournalTransaction(r,{tx_id:'TX1',operations:[{path:'a.txt',data:'A'}]});await writeFile(path.join(r,m.operations[0].temp_path),'EVIL');await assert.rejects(()=>commitJournalTransaction(r,'TX1'),e=>e.code==='SECURITY_JOURNAL_TEMP_CORRUPT');}finally{await rm(r,{recursive:true,force:true});}});
test('rollback removes prepared temp and marks state',async()=>{const r=await tmp();try{await prepareJournalTransaction(r,{tx_id:'TX1',operations:[{path:'a.txt',data:'A'}]});const m=await rollbackJournalTransaction(r,'TX1');assert.equal(m.state,'ROLLED_BACK');assert.equal((await readJournalTransaction(r,'TX1')).state,'ROLLED_BACK');}finally{await rm(r,{recursive:true,force:true});}});
test('rollback is forbidden after commit phase begins',async()=>{const r=await tmp();try{await prepareJournalTransaction(r,{tx_id:'TX1',operations:[{path:'a.txt',data:'A'}]});const mf=path.join(r,'.bai-os/security/journal/TX1/manifest.json');const m=JSON.parse(await readFile(mf,'utf8'));m.state='COMMITTING';await writeFile(mf,JSON.stringify(m));await assert.rejects(()=>rollbackJournalTransaction(r,'TX1'),e=>e.code==='SECURITY_JOURNAL_ROLLBACK_UNSAFE');}finally{await rm(r,{recursive:true,force:true});}});
