import { rebuildWorkspaceRegistry, verifyWorkspaceRegistry } from './registry.mjs';
import { resolveRuntimeProfile, resolveEnvironmentCapabilities } from './runtime.mjs';
import { resolveProject, resolveRisk, resolveTaskKnowledge } from './resolution.mjs';
import { buildRoleStartupPackage, validateRoleActivation } from './startup.mjs';
import { compileOrchestratorInstruction, createOwnerAuthorizationProposal } from './instruction.mjs';
import { createAutomationPlan } from './engine.mjs';
import { deepFreeze } from './util.mjs';
export class AutomationServiceError extends Error { constructor(code,message=code){super(message);this.code=code;} }
export async function prepareAutomationRun(input={}){
  const registry=input.registry??await rebuildWorkspaceRegistry(input.project_root,{include_extensions:input.registry_extensions??['.md','.json','.yaml','.mjs']}); await verifyWorkspaceRegistry(input.project_root,registry);
  const runtimeProfile=resolveRuntimeProfile(input.runtime_observation); const runtime=resolveEnvironmentCapabilities({runtime_profile:runtimeProfile,toolchains:input.toolchains??[],required_capabilities:input.required_capabilities??[],required_tools:input.required_tools??[]}); if(runtime.result!=='ENVIRONMENT_CAPABILITY_READY') throw new AutomationServiceError('AUTOMATION_PREP_RUNTIME_BLOCKED');
  const project=resolveProject({project_id:input.project_id,project_root:input.project_root,registry}); const risk=resolveRisk(input.change_profile??{});
  const knowledge=input.knowledge_required===false?{result:'KNOWLEDGE_NOT_REQUIRED',pack:null}:await resolveTaskKnowledge({knowledge_root:input.knowledge_root,request:input.knowledge_request,pack_id:input.pack_id}); if(knowledge.result==='KNOWLEDGE_INTEGRATION_BLOCKED') throw new AutomationServiceError('AUTOMATION_PREP_KNOWLEDGE_BLOCKED');
  const startup=buildRoleStartupPackage({project_id:input.project_id,task_id:input.task_id,role:input.role,phase:input.phase,runtime_resolution:runtime,project_resolution:project,risk_resolution:risk,knowledge_integration:knowledge,lifecycle_snapshot:input.lifecycle_snapshot,model_profiles:input.model_profiles,model_request:input.model_request,canonical_sources:input.canonical_sources??[],optional_sources:input.optional_sources??[],allowed_paths:input.allowed_paths??[],protected_paths:input.protected_paths??[],stop_conditions:input.stop_conditions??[],expected_outputs:input.expected_outputs??[],owner_approval_required:Boolean(input.owner_approval_required),context_token_budget:input.context_token_budget}); validateRoleActivation(startup,{task_id:input.task_id,status_revision:input.lifecycle_snapshot.status_revision,phase:input.phase});
  const instruction=compileOrchestratorInstruction({startup_package:startup,task_definition:input.task_definition,role_specification:input.role_specification,knowledge_summary:input.knowledge_summary??null,additional_constraints:input.additional_constraints??[]}); const plan=createAutomationPlan({startup_package:startup,instruction,actions:input.actions??[]});
  const owner_proposal=plan.owner_approval_required?createOwnerAuthorizationProposal({owner_intent:input.owner_intent??`Authorize ${input.task_id} ${input.phase}`,requested_role:input.role,task_id:input.task_id,phase:input.phase,current_state:input.lifecycle_snapshot,active_gate:input.active_gate??{gate:'UNKNOWN'},runtime_preflight:runtime,risk_profile:risk,allowed_paths:input.allowed_paths??[],protected_paths:input.protected_paths??[],validation_plan:input.validation_plan??[],stop_conditions:input.stop_conditions??[],recommended_model_cost_tier:input.recommended_model_cost_tier??null}):null;
  return deepFreeze({result:'AUTOMATION_RUN_PREPARED',registry,runtime,project,risk,knowledge,startup,instruction,plan,owner_proposal});
}
