import test from 'node:test';import assert from 'node:assert/strict';
import { MigrationRegistry } from '../../src/release/migration.mjs';import { createReleaseManifest } from '../../src/release/manifest.mjs';
const manifest=()=>createReleaseManifest({os_version:'2.0.0',artifacts:[{path:'a',checksum:'sha256:x',size_bytes:1}],migrations:[{migration_id:'m1',component:'knowledge',from_version:'1.0.0',to_version:'2.0.0'}]});
test('register and plan migration',()=>{const r=new MigrationRegistry().register({migration_id:'m1',component:'knowledge',from_version:'1.0.0',to_version:'2.0.0',apply:s=>s});assert.equal(r.plan(manifest(),{knowledge:'1.0.0'}).length,1);});
test('duplicate migration rejected',()=>{const r=new MigrationRegistry().register({migration_id:'m1',component:'k',from_version:'1',to_version:'2',apply:s=>s});assert.throws(()=>r.register({migration_id:'m1',component:'k',from_version:'2',to_version:'3',apply:s=>s}),e=>e.code==='RELEASE_MIGRATION_DUPLICATE');});
test('migration cannot broaden authorization',()=>assert.throws(()=>new MigrationRegistry().register({migration_id:'m',component:'k',from_version:'1',to_version:'2',apply:s=>s,broadens_authorization:true}),e=>e.code==='RELEASE_MIGRATION_AUTHORIZATION_BROADENING'));
test('missing handler blocks required migration',()=>assert.throws(()=>new MigrationRegistry().plan(manifest(),{knowledge:'1.0.0'}),e=>e.code==='RELEASE_MIGRATION_HANDLER_MISSING'));
test('source mismatch blocks migration',()=>{const r=new MigrationRegistry().register({migration_id:'m1',component:'knowledge',from_version:'1.0.0',to_version:'2.0.0',apply:s=>s});assert.throws(()=>r.plan(manifest(),{knowledge:'0.9.0'}),e=>e.code==='RELEASE_MIGRATION_SOURCE_MISMATCH');});
test('apply migration updates state schema version',async()=>{const r=new MigrationRegistry().register({migration_id:'m1',component:'knowledge',from_version:'1.0.0',to_version:'2.0.0',apply:s=>({...s,migrated:true})});const out=await r.apply(manifest(),{schemas:{knowledge:'1.0.0'}});assert.equal(out.schemas.knowledge,'2.0.0');assert.equal(out.migrated,true);});
