import test from 'node:test';import assert from 'node:assert/strict';
import { createUpgradePreview } from '../../src/release/planner.mjs';import { createReleaseManifest } from '../../src/release/manifest.mjs';import { MigrationRegistry } from '../../src/release/migration.mjs';
const a=()=>createReleaseManifest({os_version:'1.0.0',artifacts:[{path:'a',checksum:'sha256:x',size_bytes:1}],schemas:{x:'1.0.0'},security_profile:{signed:true}});
const b=()=>createReleaseManifest({os_version:'2.0.0',artifacts:[{path:'a',checksum:'sha256:x',size_bytes:1}],schemas:{x:'2.0.0'},migrations:[{migration_id:'x12',component:'x',from_version:'1.0.0',to_version:'2.0.0'}],security_profile:{signed:true},rollback_target:'1.0.0'});
test('install preview',()=>assert.equal(createUpgradePreview({target_manifest:a(),consumer_profile:{schemas:{x:'1.0.0'},security_profile:{signed:true}}}).direction,'INSTALL'));
test('upgrade preview with migration',()=>{const r=new MigrationRegistry().register({migration_id:'x12',component:'x',from_version:'1.0.0',to_version:'2.0.0',apply:s=>s});const p=createUpgradePreview({current_state:{os_version:'1.0.0',schemas:{x:'1.0.0'},security_profile:{signed:true}},current_manifest:a(),target_manifest:b(),consumer_profile:{schemas:{x:'1.0.0'},security_profile:{signed:true}},migration_registry:r});assert.equal(p.direction,'UPGRADE');assert.equal(p.migrations.length,1);});
test('downgrade blocked by default',()=>assert.throws(()=>createUpgradePreview({current_state:{os_version:'2.0.0'},target_manifest:a()}),e=>e.code==='RELEASE_DOWNGRADE_NOT_ALLOWED'));
test('downgrade allowed explicitly',()=>assert.equal(createUpgradePreview({current_state:{os_version:'2.0.0'},target_manifest:a(),allow_downgrade:true}).direction,'DOWNGRADE'));
test('security weakening blocks before mutation',()=>{const weak=createReleaseManifest({os_version:'2.0.0',artifacts:[{path:'a',checksum:'sha256:x',size_bytes:1}],security_profile:{signed:false}});assert.throws(()=>createUpgradePreview({current_state:{os_version:'1.0.0'},current_manifest:a(),target_manifest:weak}),e=>e.code==='RELEASE_SECURITY_WEAKENING');});
