import { compareSemver } from '../release/semver.mjs';
import { evaluateExtensionCompatibility } from './compatibility.mjs';
import { LIFECYCLE_STATES, EXTENSION_VERSION } from './constants.mjs';
import { ExtensionError } from './errors.mjs'; import { verifyExtensionManifest } from './manifest.mjs'; import { validateProviderContract } from './provider.mjs'; import { checksumObject, deepFreeze, nowIso } from './util.mjs';
function immutableProvider(provider){if(!provider)return null;const caps={};for(const [cid,ops] of Object.entries(provider.capabilities??{})){caps[cid]=Object.freeze(Object.fromEntries(Object.entries(ops).filter(([,fn])=>typeof fn==='function')));}return Object.freeze({provider_id:provider.provider_id??null,implementation_checksum:provider.implementation_checksum??null,capabilities:Object.freeze(caps)});}
function grantsMap(raw={}){const m=new Map();for(const [id,v] of Object.entries(raw)){const list=Array.isArray(v)?v:(v?.manifest_checksums??[]);m.set(id,new Set(list.map(String)));}return m;}
export class ExtensionRegistry{
  #entries=new Map(); #providers=new Map(); #revision=0;
  constructor({os_version='0.8.0',platform=process.platform,architecture=process.arch,clock=()=>new Date(),trust_policy={}}={}){this.os_version=os_version;this.platform=platform;this.architecture=architecture;this.clock=clock;this.trust_policy={in_process_grants:grantsMap(trust_policy.in_process_grants??{}),in_process_verifier:trust_policy.in_process_verifier??null};}
  static fromSnapshot(snapshot,options={}){const r=new ExtensionRegistry(options);if(!snapshot||snapshot.extension_registry_version!==EXTENSION_VERSION||snapshot.content_checksum!==checksumObject(snapshot))throw new ExtensionError('EXTENSION_REGISTRY_TAMPERED');const ids=new Set();for(const item of snapshot.entries??[]){verifyExtensionManifest(item.manifest);if(ids.has(item.extension_id)||item.extension_id!==item.manifest.extension_id)throw new ExtensionError('EXTENSION_REGISTRY_INVALID');ids.add(item.extension_id);if(!LIFECYCLE_STATES.includes(item.state))throw new ExtensionError('EXTENSION_STATE_CORRUPT');const restoredState=item.state==='ENABLED'&&item.manifest.execution_mode!=='DECLARATIVE'?'DISABLED':item.state;r.#entries.set(item.extension_id,{manifest:item.manifest,state:restoredState,installed_at:item.installed_at,updated_at:item.updated_at,revocation_reason:item.revocation_reason??null});}r.#revision=snapshot.revision??0;return r;}
  install(manifest,{provider=null}={}){verifyExtensionManifest(manifest);if(this.#entries.has(manifest.extension_id))throw new ExtensionError('EXTENSION_ALREADY_INSTALLED');if(provider)validateProviderContract(manifest,provider,{require_handlers:manifest.execution_mode!=='DECLARATIVE'});this.#entries.set(manifest.extension_id,{manifest,state:'INSTALLED',installed_at:nowIso(this.clock),updated_at:nowIso(this.clock),revocation_reason:null});if(provider)this.#providers.set(manifest.extension_id,immutableProvider(provider));this.#revision++;return this.get(manifest.extension_id);}
  attachProvider(id,provider){const e=this.#must(id);if(e.state==='REVOKED')throw new ExtensionError('EXTENSION_REVOKED');validateProviderContract(e.manifest,provider,{require_handlers:e.manifest.execution_mode!=='DECLARATIVE'});this.#providers.set(id,immutableProvider(provider));e.updated_at=nowIso(this.clock);this.#revision++;return this.get(id);}
  validate(id){const e=this.#must(id);const installed=[...this.#entries.keys()].map(x=>this.get(x));const c=evaluateExtensionCompatibility(e.manifest,{os_version:this.os_version,platform:this.platform,architecture:this.architecture,installed_extensions:installed});if(c.status!=='COMPATIBLE')throw new ExtensionError('EXTENSION_INCOMPATIBLE','extension incompatible',c);e.state='VALIDATED';e.updated_at=nowIso(this.clock);this.#revision++;return this.get(id);}
  enable(id){const e=this.#must(id);if(e.state==='REVOKED')throw new ExtensionError('EXTENSION_REVOKED');if(!['VALIDATED','DISABLED'].includes(e.state))throw new ExtensionError('EXTENSION_LIFECYCLE_INVALID');const m=e.manifest;if(m.execution_mode==='IN_PROCESS_TRUSTED'&&!this.#trustedInProcess(m))throw new ExtensionError('EXTENSION_IN_PROCESS_TRUST_DENIED');if(m.execution_mode!=='DECLARATIVE'){const p=this.#providers.get(id);if(!p)throw new ExtensionError('EXTENSION_PROVIDER_MISSING');validateProviderContract(m,p);}this.assertDependencies(id);e.state='ENABLED';e.updated_at=nowIso(this.clock);this.#revision++;return this.get(id);}
  disable(id){const e=this.#must(id);if(e.state!=='ENABLED')throw new ExtensionError('EXTENSION_LIFECYCLE_INVALID');for(const other of this.#entries.values())if(other.state==='ENABLED'&&other.manifest.compatibility.dependencies?.some(d=>d.extension_id===id&&d.require_enabled))throw new ExtensionError('EXTENSION_DEPENDENCY_IN_USE');e.state='DISABLED';e.updated_at=nowIso(this.clock);this.#revision++;return this.get(id);}
  upgrade(id,newManifest,{provider=null,allow_downgrade=false}={}){const e=this.#must(id);verifyExtensionManifest(newManifest);if(newManifest.extension_id!==id)throw new ExtensionError('EXTENSION_ID_MISMATCH');const cmp=compareSemver(newManifest.extension_version,e.manifest.extension_version);if(cmp<0&&!allow_downgrade)throw new ExtensionError('EXTENSION_DOWNGRADE_BLOCKED');if(cmp===0&&newManifest.content_checksum!==e.manifest.content_checksum)throw new ExtensionError('EXTENSION_SAME_VERSION_MUTATION');if(provider)validateProviderContract(newManifest,provider,{require_handlers:newManifest.execution_mode!=='DECLARATIVE'});for(const other of this.#entries.values()){if(other.manifest.extension_id===id)continue;for(const d of other.manifest.compatibility.dependencies??[]){if(d.extension_id!==id)continue;if(other.state==='ENABLED'&&d.require_enabled)throw new ExtensionError('EXTENSION_UPGRADE_REQUIRES_DEPENDENT_DISABLE',other.manifest.extension_id);const testEntry={extension_id:id,manifest:newManifest,state:'INSTALLED'};const c=evaluateExtensionCompatibility(other.manifest,{os_version:this.os_version,platform:this.platform,architecture:this.architecture,installed_extensions:[...this.#entries.keys()].filter(x=>x!==id).map(x=>this.get(x)).concat(testEntry)});if(c.reasons.some(r=>r===`DEPENDENCY_VERSION:${id}`))throw new ExtensionError('EXTENSION_UPGRADE_BREAKS_DEPENDENT',other.manifest.extension_id);}}
    e.manifest=newManifest;e.state='INSTALLED';e.updated_at=nowIso(this.clock);if(provider)this.#providers.set(id,immutableProvider(provider));else this.#providers.delete(id);this.#revision++;return this.get(id);}
  revoke(id,reason='REVOKED'){const e=this.#must(id);e.state='REVOKED';e.revocation_reason=String(reason);e.updated_at=nowIso(this.clock);this.#providers.delete(id);for(const other of this.#entries.values())if(other.state==='ENABLED'&&other.manifest.compatibility.dependencies?.some(d=>d.extension_id===id))other.state='DISABLED';this.#revision++;return this.get(id);}
  uninstall(id){const e=this.#must(id);if(e.state==='ENABLED')throw new ExtensionError('EXTENSION_ENABLED_UNINSTALL_BLOCKED');for(const other of this.#entries.values())if(other.manifest.compatibility.dependencies?.some(d=>d.extension_id===id))throw new ExtensionError('EXTENSION_DEPENDENCY_IN_USE');this.#entries.delete(id);this.#providers.delete(id);this.#revision++;return true;}
  assertDependencies(id){const e=this.#must(id);const c=evaluateExtensionCompatibility(e.manifest,{os_version:this.os_version,platform:this.platform,architecture:this.architecture,installed_extensions:[...this.#entries.keys()].map(x=>this.get(x))});const depReasons=c.reasons.filter(x=>x.startsWith('DEPENDENCY'));if(depReasons.length)throw new ExtensionError('EXTENSION_DEPENDENCY_UNAVAILABLE',id,{reasons:depReasons});return true;}
  get(id){const e=this.#must(id);return deepFreeze(structuredClone({extension_id:id,manifest:e.manifest,state:e.state,installed_at:e.installed_at,updated_at:e.updated_at,revocation_reason:e.revocation_reason}));}
  provider(id){return this.#providers.get(id)??null;}
  snapshot(){const out={extension_registry_version:EXTENSION_VERSION,revision:this.#revision,entries:[...this.#entries.keys()].sort().map(id=>this.get(id))};out.content_checksum=checksumObject(out);return deepFreeze(out);}
  #trustedInProcess(m){const grant=this.trust_policy.in_process_grants.get(m.extension_id);if(grant?.has(m.content_checksum))return true;return this.trust_policy.in_process_verifier?.(m)===true;}
  #must(id){const e=this.#entries.get(id);if(!e)throw new ExtensionError('EXTENSION_NOT_FOUND');if(!LIFECYCLE_STATES.includes(e.state))throw new ExtensionError('EXTENSION_STATE_CORRUPT');return e;}
}
