import { CapabilityBroker } from './broker.mjs';import { ExtensionRegistry } from './registry.mjs';import { buildDomainPackSet,validatePolicyPackFloors,verifyDomainPack } from './packs.mjs';import { evaluateDomainArtifact } from './artifact.mjs';import { executeExtensionHooks } from './hooks.mjs';import { ExtensionError } from './errors.mjs';
export class ExtensionService{
  constructor(options={}){this.registry=options.registry??new ExtensionRegistry(options);this.broker=options.broker??new CapabilityBroker({registry:this.registry,sandbox_runner:options.sandbox_runner,authorization_verifier:options.authorization_verifier,permission_resolver:options.permission_resolver});this.packs=[];this.hooks=[];this.artifact_bindings=new Map();}
  install(manifest,{provider=null}={}){return this.registry.install(manifest,{provider});}
  attachProvider(id,provider){return this.registry.attachProvider(id,provider);}
  validate(id){return this.registry.validate(id);}
  enable(id){return this.registry.enable(id);}
  disable(id){return this.registry.disable(id);}
  upgrade(id,m,opts={}){return this.registry.upgrade(id,m,opts);}
  revoke(id,reason){return this.registry.revoke(id,reason);}
  async invoke(req){return this.broker.invoke(req);}
  addPacks(packs,{required_floors=[]}={}){for(const p of packs){verifyDomainPack(p);const entry=this.registry.get(p.extension_id);if(!entry.manifest.domains.includes(p.domain))throw new ExtensionError('EXTENSION_PACK_DOMAIN_MISMATCH');if(entry.manifest.packs.length&&!entry.manifest.packs.includes(p.pack_id))throw new ExtensionError('EXTENSION_PACK_UNDECLARED');if(p.pack_type.includes('POLICY'))validatePolicyPackFloors(p,{required_floors});}const candidate=[...this.packs,...packs];const set=buildDomainPackSet(candidate);this.packs=candidate;return set;}
  addHook(h){const entry=this.registry.get(h.extension_id);if(!entry.manifest.hook_types.includes(h.hook_type))throw new ExtensionError('EXTENSION_HOOK_UNDECLARED');if(!entry.manifest.capabilities.some(c=>c.capability_id===h.capability_id&&c.operations.includes(h.operation)))throw new ExtensionError('EXTENSION_HOOK_CAPABILITY_UNDECLARED');if(this.hooks.some(x=>x.hook_id===h.hook_id))throw new ExtensionError('EXTENSION_HOOK_DUPLICATE');this.hooks.push(h);return h;}
  async runHooks(type,input,context={}){return executeExtensionHooks({hooks:this.hooks,broker:this.broker,input,hook_type:type,context});}
  registerArtifactExtension(domain,binding){const entry=this.registry.get(binding.extension_id);if(entry.state!=='ENABLED')throw new ExtensionError('EXTENSION_NOT_ENABLED');if(!entry.manifest.domains.includes(domain))throw new ExtensionError('EXTENSION_ARTIFACT_DOMAIN_MISMATCH');if(this.artifact_bindings.has(domain)&&binding.replace!==true)throw new ExtensionError('EXTENSION_ARTIFACT_BINDING_EXISTS');this.artifact_bindings.set(domain,{extension_id:binding.extension_id,validator_capability:binding.validator_capability??'domain.artifact_validator',previewer_capability:binding.previewer_capability??'domain.artifact_previewer',quality_gate_capability:binding.quality_gate_capability??'domain.quality_gate'});}
  async evaluateArtifact(domain,artifact,context={}){const b=this.artifact_bindings.get(domain);if(!b)return evaluateDomainArtifact({artifact,context});const entry=this.registry.get(b.extension_id);const caps=new Set(entry.manifest.capabilities.map(c=>c.capability_id));const validators=caps.has(b.validator_capability)?[async(a)=>{const r=await this.broker.invoke({extension_id:b.extension_id,capability_id:b.validator_capability,operation:'validate',payload:a,context});return {validator_id:`${b.extension_id}:validator`,...(r.result??{})};}]:[];const previewers=caps.has(b.previewer_capability)?[async(a)=>{const r=await this.broker.invoke({extension_id:b.extension_id,capability_id:b.previewer_capability,operation:'preview',payload:a,context});return {previewer_id:`${b.extension_id}:previewer`,value:r.result};}]:[];const quality_gates=caps.has(b.quality_gate_capability)?[async(a)=>{const r=await this.broker.invoke({extension_id:b.extension_id,capability_id:b.quality_gate_capability,operation:'evaluate',payload:a,context});return {gate_id:`${b.extension_id}:quality`,...(r.result??{})};}]:[];return evaluateDomainArtifact({artifact,validators,previewers,quality_gates,context});}
}
