import { DEFAULT_MONITORING_POLICY, SEVERITIES } from './constants.mjs';
import { MonitoringError, checksumObject, deepFreeze, nowIso, shortHash } from './util.mjs';
const rank=(s)=>SEVERITIES.indexOf(s);
function alert({severity,component,code,message,value,threshold,evidence=[],project_id=null,task_id=null,clock}){const created_at=nowIso(clock);const identity={severity,component,code,value,threshold,project_id,task_id,created_at};const a={alert_version:'1.0.0',alert_id:`ALERT-${shortHash(identity)}`,severity,component,code,message,value,threshold,project_id,task_id,evidence:[...evidence],created_at,dashboard_authority:false};a.content_checksum=checksumObject(a);return a;}
export function evaluateMonitoringAlerts(metrics,{policy={},project_id=null,task_id=null,clock=()=>new Date()}={}){
  const p={...DEFAULT_MONITORING_POLICY,...policy};const out=[];const push=(x)=>out.push(alert({...x,project_id,task_id,clock}));
  if((metrics.system?.critical_incident_count??0)>0)push({severity:'CRITICAL',component:'SYSTEM',code:'CRITICAL_SYSTEM_INCIDENT',message:'A critical system incident was observed.',value:metrics.system.critical_incident_count,threshold:1});
  if((metrics.system?.canonical_integrity_failure_count??0)>0)push({severity:'CRITICAL',component:'SYSTEM',code:'CANONICAL_INTEGRITY_FAILURE',message:'Canonical integrity failure was observed.',value:metrics.system.canonical_integrity_failure_count,threshold:1});
  if(metrics.lifecycle.active_phase_age_max_ms>=p.phase_age_high_ms)push({severity:'HIGH',component:'LIFECYCLE',code:'PHASE_LONG_RUNNING_HIGH',message:'A non-terminal phase has exceeded the high age threshold.',value:metrics.lifecycle.active_phase_age_max_ms,threshold:p.phase_age_high_ms});else if(metrics.lifecycle.active_phase_age_max_ms>=p.phase_age_warning_ms)push({severity:'WARNING',component:'LIFECYCLE',code:'PHASE_LONG_RUNNING',message:'A non-terminal phase has exceeded the warning age threshold.',value:metrics.lifecycle.active_phase_age_max_ms,threshold:p.phase_age_warning_ms});
  if(metrics.automation.stall_count>=p.repeated_stall_high_at)push({severity:'HIGH',component:'AUTOMATION',code:'REPEATED_STALL',message:'Repeated stalled execution detected.',value:metrics.automation.stall_count,threshold:p.repeated_stall_high_at});
  if(metrics.quality.test_pass_rate!=null&&metrics.quality.test_pass_rate<p.test_pass_rate_high_below)push({severity:'HIGH',component:'QUALITY',code:'TEST_PASS_RATE_LOW_HIGH',message:'Test pass rate is below the high-risk threshold.',value:metrics.quality.test_pass_rate,threshold:p.test_pass_rate_high_below});else if(metrics.quality.test_pass_rate!=null&&metrics.quality.test_pass_rate<p.test_pass_rate_warning_below)push({severity:'WARNING',component:'QUALITY',code:'TEST_PASS_RATE_LOW',message:'Test pass rate is below the warning threshold.',value:metrics.quality.test_pass_rate,threshold:p.test_pass_rate_warning_below});
  if(metrics.context.mandatory_missing>=p.mandatory_knowledge_missing_high_at)push({severity:'HIGH',component:'CONTEXT',code:'MANDATORY_CONTEXT_MISSING',message:'Mandatory context or knowledge is missing.',value:metrics.context.mandatory_missing,threshold:p.mandatory_knowledge_missing_high_at});
  if(metrics.cost.utilization!=null&&metrics.cost.utilization>=p.cost_utilization_high_at)push({severity:'HIGH',component:'COST',code:'COST_BUDGET_EXHAUSTED',message:'Cost budget utilization reached or exceeded the hard threshold.',value:metrics.cost.utilization,threshold:p.cost_utilization_high_at});else if(metrics.cost.utilization!=null&&metrics.cost.utilization>=p.cost_utilization_warning_at)push({severity:'WARNING',component:'COST',code:'COST_BUDGET_SOFT_LIMIT',message:'Cost budget utilization reached the warning threshold.',value:metrics.cost.utilization,threshold:p.cost_utilization_warning_at});
  if(metrics.model.failure_rate!=null&&metrics.model.failure_rate>=p.model_failure_high_at)push({severity:'HIGH',component:'MODEL',code:'MODEL_FAILURE_RATE_HIGH',message:'Model failure rate is high.',value:metrics.model.failure_rate,threshold:p.model_failure_high_at});else if(metrics.model.failure_rate!=null&&metrics.model.failure_rate>=p.model_failure_warning_at)push({severity:'WARNING',component:'MODEL',code:'MODEL_FAILURE_RATE_ELEVATED',message:'Model failure rate is elevated.',value:metrics.model.failure_rate,threshold:p.model_failure_warning_at});
  if(metrics.knowledge.debt_score>=p.knowledge_debt_high_at)push({severity:'HIGH',component:'KNOWLEDGE',code:'KNOWLEDGE_DEBT_HIGH',message:'Knowledge debt is above the high threshold.',value:metrics.knowledge.debt_score,threshold:p.knowledge_debt_high_at});else if(metrics.knowledge.debt_score>=p.knowledge_debt_warning_at)push({severity:'WARNING',component:'KNOWLEDGE',code:'KNOWLEDGE_DEBT_ELEVATED',message:'Knowledge debt is elevated.',value:metrics.knowledge.debt_score,threshold:p.knowledge_debt_warning_at});
  if(metrics.registry.verify_failure_count>=p.registry_verify_failure_high_at)push({severity:'HIGH',component:'REGISTRY',code:'REGISTRY_VERIFY_FAILURE',message:'Registry verification failure detected.',value:metrics.registry.verify_failure_count,threshold:p.registry_verify_failure_high_at});
  if(metrics.integration.failure_rate!=null&&metrics.integration.failure_rate>=p.integration_failure_high_at)push({severity:'HIGH',component:'INTEGRATION',code:'INTEGRATION_FAILURE_RATE_HIGH',message:'Integration failure rate is high.',value:metrics.integration.failure_rate,threshold:p.integration_failure_high_at});else if(metrics.integration.failure_rate!=null&&metrics.integration.failure_rate>=p.integration_failure_warning_at)push({severity:'WARNING',component:'INTEGRATION',code:'INTEGRATION_FAILURE_RATE_ELEVATED',message:'Integration failure rate is elevated.',value:metrics.integration.failure_rate,threshold:p.integration_failure_warning_at});
  if(metrics.governance.verify_failure_count>=p.governance_verify_failure_high_at)push({severity:'HIGH',component:'GOVERNANCE',code:'GOVERNANCE_VERIFY_FAILURE',message:'Governance verification failure detected.',value:metrics.governance.verify_failure_count,threshold:p.governance_verify_failure_high_at});
  return deepFreeze(out.sort((a,b)=>rank(b.severity)-rank(a.severity)||a.code.localeCompare(b.code)));
}
export function deduplicateAlerts(alerts,previous_alerts=[],{window_ms=DEFAULT_MONITORING_POLICY.alert_dedup_window_ms,clock=()=>new Date()}={}){if(!Array.isArray(alerts)||!Array.isArray(previous_alerts)||!Number.isFinite(window_ms)||window_ms<0)throw new MonitoringError('ALERT_DEDUP_INPUT_INVALID');const now=(clock() instanceof Date?clock():new Date(clock())).getTime();const keys=new Map(previous_alerts.map(a=>[`${a.project_id??''}|${a.task_id??''}|${a.code}|${a.severity}`,a]));return deepFreeze(alerts.filter(a=>{const prior=keys.get(`${a.project_id??''}|${a.task_id??''}|${a.code}|${a.severity}`);return !prior||now-Date.parse(prior.created_at)>window_ms;}));}
