import { checksumObject, deepFreeze, nowIso } from './util.mjs';
export function buildDashboardModel(snapshot,{clock=()=>new Date()}={}){const m=snapshot.metrics;const dashboard={dashboard_version:'1.0.0',project_id:snapshot.project_id,task_id:snapshot.task_id,generated_at:nowIso(clock),health:snapshot.health,cards:[
  {id:'lifecycle',title:'Lifecycle',primary:m.lifecycle.status_counts,secondary:{max_phase_age_ms:m.lifecycle.active_phase_age_max_ms,gate_failures:m.lifecycle.gate_failure_count}},
  {id:'quality',title:'Quality',primary:m.quality.test_pass_percent,unit:'%',secondary:{passed:m.quality.test_pass,failed:m.quality.test_fail,total:m.quality.test_total}},
  {id:'automation',title:'Automation',primary:m.automation.run_count,secondary:{retries:m.automation.retry_count,stalls:m.automation.stall_count,approval_pending:m.automation.owner_approval_pending}},
  {id:'context',title:'Context',primary:m.context.token_count,secondary:{duplicates:m.context.duplicate_count,stale:m.context.stale_count,conflicts:m.context.conflict_count,mandatory_missing:m.context.mandatory_missing}},
  {id:'cost',title:'Cost',primary:m.cost.actual_cost_microusd,unit:'microUSD',secondary:{budget_microusd:m.cost.budget_microusd,utilization_percent:m.cost.utilization_percent}},
  {id:'model',title:'Model',primary:m.model.call_count,secondary:{failure_percent:m.model.failure_percent,latency_avg_ms:m.model.latency_avg_ms,fallbacks:m.model.fallback_count}},
  {id:'knowledge',title:'Knowledge',primary:m.knowledge.debt_score,secondary:{assets:m.knowledge.asset_count,stale:m.knowledge.stale_count,applied:m.knowledge.application_count,verified:m.knowledge.verification_count}},
  {id:'registry',title:'Registry',primary:m.registry.verify_failure_count,secondary:{rebuilds:m.registry.rebuild_count,checksum_failures:m.registry.checksum_failure_count}},
  {id:'integration',title:'Integration',primary:m.integration.event_count,secondary:{failure_percent:m.integration.failure_percent,rate_limits:m.integration.rate_limit_count}},
  {id:'governance',title:'Governance',primary:m.governance.verify_failure_count,secondary:{approval_pending:m.governance.approval_pending_count,deviations:m.governance.deviation_count}},
  {id:'system',title:'System',primary:m.system.critical_incident_count,secondary:{security_incidents:m.system.security_incident_count,canonical_integrity_failures:m.system.canonical_integrity_failure_count}},
],alerts:snapshot.alerts.map(a=>({alert_id:a.alert_id,severity:a.severity,component:a.component,code:a.code,message:a.message,value:a.value,threshold:a.threshold})),canonical_authority:false,derived_rebuildable:true};dashboard.content_checksum=checksumObject(dashboard);return deepFreeze(dashboard);}
export function buildWorkspaceDashboard(snapshots,{clock=()=>new Date()}={}){const order={CRITICAL:3,AT_RISK:2,DEGRADED:1,HEALTHY:0};const rows=[...snapshots].map(s=>({project_id:s.project_id,task_id:s.task_id,health:s.health,alert_count:s.alerts.length,critical_alerts:s.alerts.filter(a=>a.severity==='CRITICAL').length,high_alerts:s.alerts.filter(a=>a.severity==='HIGH').length,knowledge_debt:s.metrics.knowledge.debt_score,cost_utilization_percent:s.metrics.cost.utilization_percent,test_pass_percent:s.metrics.quality.test_pass_percent})).sort((a,b)=>order[b.health]-order[a.health]||a.project_id.localeCompare(b.project_id));const d={workspace_dashboard_version:'1.0.0',generated_at:nowIso(clock),project_count:rows.length,projects:rows,canonical_authority:false,derived_rebuildable:true};d.content_checksum=checksumObject(d);return deepFreeze(d);}
