import { DEFAULT_MONITORING_POLICY, KNOWLEDGE_DEBT_WEIGHTS } from './constants.mjs';
import { MonitoringError, avg, deepFreeze, groupBy, percent, ratio, sum } from './util.mjs';
const terminal=new Set(['COMPLETED','CANCELLED','REJECTED','ARCHIVED']);
const countBy=(items,fn)=>Object.fromEntries([...groupBy(items,fn)].map(([k,v])=>[k,v.length]));
const timeMs=(v)=>{const n=Date.parse(v);return Number.isNaN(n)?null:n;};
const bool=(x)=>Boolean(x);
export function calculateKnowledgeDebt(assets=[]){let score=0;const details={candidate:0,stale:0,duplicate:0,ownerless:0,invalid:0,conflict:0};for(const a of assets){const status=String(a.status??'').toUpperCase();if(status==='CANDIDATE'){details.candidate++;score+=KNOWLEDGE_DEBT_WEIGHTS.CANDIDATE;}if(status==='STALE'||a.freshness_status==='STALE'){details.stale++;score+=KNOWLEDGE_DEBT_WEIGHTS.STALE;}if(bool(a.duplicate)){details.duplicate++;score+=KNOWLEDGE_DEBT_WEIGHTS.DUPLICATE;}if(!a.owner_id&&!a.owner&&!a.owning_role){details.ownerless++;score+=KNOWLEDGE_DEBT_WEIGHTS.OWNERLESS;}if(status==='INVALID'){details.invalid++;score+=KNOWLEDGE_DEBT_WEIGHTS.INVALID;}if(bool(a.conflict)){details.conflict++;score+=KNOWLEDGE_DEBT_WEIGHTS.CONFLICT;}}return deepFreeze({score,details});}
export function computeMonitoringMetrics(sources={}, {clock=()=>new Date(),policy={}}={}){
  const p={...DEFAULT_MONITORING_POLICY,...policy};const now=(clock() instanceof Date?clock():new Date(clock())).getTime();if(Number.isNaN(now))throw new MonitoringError('MONITORING_CLOCK_INVALID');
  const lifecycle=sources.lifecycle_records??[]; const tests=sources.test_results??[]; const automation=sources.automation_runs??[]; const context=sources.context_observations??[]; const cost=sources.cost_events??[]; const models=sources.model_events??[]; const knowledge=sources.knowledge_assets??[]; const usage=sources.knowledge_usage_events??[]; const registry=sources.registry_events??[]; const integration=sources.integration_events??[]; const governance=sources.governance_events??[]; const system=sources.system_events??[];
  const phaseAges=lifecycle.filter(r=>!terminal.has(r.task_status)).map(r=>Math.max(0,now-(timeMs(r.entered_at??r.updated_at)??now)));
  const testPass=tests.filter(t=>t.status==='PASS'||t.result==='PASS').length;const testTotal=tests.length;const retests=tests.filter(t=>(Number(t.attempt??1)>1)||t.retest===true).length;
  const retries=sum(automation.map(a=>Number.isFinite(a.retry_count)?a.retry_count:(a.event_type==='RETRY'?1:0)));const stalls=automation.filter(a=>a.status==='STALLED'||a.event_type==='STALL').length + lifecycle.filter(r=>r.task_status==='STALLED').length;
  const ctxTokens=sum(context.map(x=>Number(x.token_count??x.tokens??0)||0));const ctxDuplicates=sum(context.map(x=>Number(x.duplicate_count??0)||0));const ctxStale=sum(context.map(x=>Number(x.stale_count??0)||0));const ctxConflict=sum(context.map(x=>Number(x.conflict_count??0)||0));const mandatoryMissing=sum(context.map(x=>Number(x.mandatory_missing??0)||0));
  const actualEvents=cost.filter(e=>e.event_type==='ACTUAL_RECORDED'||e.type==='ACTUAL');const actualCost=sum(actualEvents.map(e=>Number(e.cost_microusd??e.cost??0)||0));const budgetValues=cost.map(e=>Number(e.budget_microusd??e.budget??0)).filter(Number.isFinite);const budget=budgetValues.length?Math.max(...budgetValues):null;
  const modelCalls=models.length;const modelFailures=models.filter(e=>e.status==='FAIL'||e.result==='FAIL'||e.success===false).length;const latencies=models.map(e=>Number(e.latency_ms)).filter(Number.isFinite);
  const knowledgeDebt=calculateKnowledgeDebt(knowledge);const applied=usage.filter(e=>e.applied===true||e.result==='APPLIED').length;const verified=usage.filter(e=>e.verification_result==='PASS'||e.verified===true).length;const recurrence=usage.filter(e=>e.recurrence===true||e.failure_recurred===true).length;
  const registryFailures=registry.filter(e=>e.result==='FAIL'||e.status==='FAIL'||e.verified===false).length;const rebuilds=registry.filter(e=>e.event_type==='REBUILD'||e.action==='REBUILD').length;
  const integrationFailures=integration.filter(e=>e.result==='FAIL'||e.status==='FAIL'||e.success===false).length;const rateLimits=integration.filter(e=>e.error_code==='RATE_LIMIT'||e.rate_limited===true).length;
  const governanceVerifyFailures=governance.filter(e=>e.verification_result==='FAIL'||e.event_type==='VERIFY_FAIL').length;const approvalPending=governance.filter(e=>e.status==='PENDING'||e.event_type==='APPROVAL_PENDING').length;
  return deepFreeze({
    lifecycle:{task_count:lifecycle.length,status_counts:countBy(lifecycle,x=>x.task_status??'UNKNOWN'),phase_counts:countBy(lifecycle,x=>x.current_phase??'UNKNOWN'),active_phase_age_max_ms:phaseAges.length?Math.max(...phaseAges):0,active_phase_age_avg_ms:avg(phaseAges)??0,gate_failure_count:lifecycle.filter(x=>x.gate_status==='FAIL').length},
    quality:{test_total:testTotal,test_pass:testPass,test_fail:testTotal-testPass,retest_count:retests,test_pass_rate:ratio(testPass,testTotal),test_pass_percent:percent(ratio(testPass,testTotal))},
    automation:{run_count:automation.length,retry_count:retries,stall_count:stalls,owner_approval_pending:automation.filter(x=>x.owner_approval_required&&x.authorization_status!=='AUTHORIZED').length},
    context:{token_count:ctxTokens,duplicate_count:ctxDuplicates,stale_count:ctxStale,conflict_count:ctxConflict,mandatory_missing:mandatoryMissing,duplicate_ratio:ctxTokens>0?ctxDuplicates/ctxTokens:null},
    cost:{actual_cost_microusd:actualCost,budget_microusd:budget,utilization:budget&&budget>0?actualCost/budget:null,utilization_percent:percent(budget&&budget>0?actualCost/budget:null),by_role:Object.fromEntries([...groupBy(actualEvents,e=>e.role??'UNKNOWN')].map(([k,v])=>[k,sum(v.map(e=>Number(e.cost_microusd??e.cost??0)||0))])),by_model:Object.fromEntries([...groupBy(actualEvents,e=>e.model_id??'UNKNOWN')].map(([k,v])=>[k,sum(v.map(e=>Number(e.cost_microusd??e.cost??0)||0))]))},
    model:{call_count:modelCalls,failure_count:modelFailures,failure_rate:ratio(modelFailures,modelCalls),failure_percent:percent(ratio(modelFailures,modelCalls)),latency_avg_ms:avg(latencies),latency_max_ms:latencies.length?Math.max(...latencies):null,fallback_count:models.filter(e=>e.fallback===true||e.event_type==='FALLBACK').length},
    knowledge:{asset_count:knowledge.length,application_count:applied,application_rate:ratio(applied,usage.length),verification_count:verified,verification_rate:ratio(verified,usage.length),recurrence_count:recurrence,recurrence_rate:ratio(recurrence,usage.length),stale_count:knowledgeDebt.details.stale,stale_rate:ratio(knowledgeDebt.details.stale,knowledge.length),debt_score:knowledgeDebt.score,debt:knowledgeDebt.details},
    registry:{event_count:registry.length,verify_failure_count:registryFailures,rebuild_count:rebuilds,checksum_failure_count:registry.filter(e=>e.error_code==='CHECKSUM_INVALID'||e.error_code==='HASH_MISMATCH').length},
    integration:{event_count:integration.length,failure_count:integrationFailures,failure_rate:ratio(integrationFailures,integration.length),failure_percent:percent(ratio(integrationFailures,integration.length)),rate_limit_count:rateLimits},
    governance:{event_count:governance.length,verify_failure_count:governanceVerifyFailures,approval_pending_count:approvalPending,deviation_count:governance.filter(e=>e.event_type==='DEVIATION'||e.deviation===true).length},
    system:{event_count:system.length,critical_incident_count:system.filter(e=>e.severity==='CRITICAL'||e.severity_hint==='CRITICAL'||e.critical===true).length,security_incident_count:system.filter(e=>e.category==='SECURITY'||e.security_incident===true).length,canonical_integrity_failure_count:system.filter(e=>e.error_code==='CANONICAL_INTEGRITY_FAILURE'||e.canonical_integrity===false).length},
    policy:p,
  });
}
