import { MONITORING_VERSION, SEVERITIES } from './constants.mjs';
import { evaluateMonitoringAlerts } from './alerts.mjs';
import { computeMonitoringMetrics } from './metrics.mjs';
import { checksumObject, deepFreeze, nowIso } from './util.mjs';
import { evaluateSourceProvenance } from './provenance.mjs';
const rank=(s)=>SEVERITIES.indexOf(s);
const healthFrom=(alerts)=>{const top=alerts.reduce((m,a)=>Math.max(m,rank(a.severity)),-1);return top>=3?'CRITICAL':top===2?'AT_RISK':top===1?'DEGRADED':'HEALTHY';};
export function buildMonitoringSnapshot({project_id,task_id=null,sources={},policy={},source_revisions={},source_metadata={},previous_alerts=[]}={}, {clock=()=>new Date()}={}){const metrics=computeMonitoringMetrics(sources,{clock,policy});let alerts=[...evaluateMonitoringAlerts(metrics,{policy,project_id,task_id,clock})];const provenance=evaluateSourceProvenance(source_metadata,{clock,source_stale_ms:policy.source_stale_warning_ms});if(provenance.unverified_count>0)alerts.push({alert_version:'1.0.0',alert_id:'ALERT-SOURCE-UNVERIFIED',severity:'HIGH',component:'SYSTEM',code:'MONITORING_SOURCE_UNVERIFIED',message:'One or more monitoring sources are unverified.',value:provenance.unverified_count,threshold:1,project_id,task_id,evidence:[],created_at:nowIso(clock),dashboard_authority:false,content_checksum:null});if(provenance.stale_count>0)alerts.push({alert_version:'1.0.0',alert_id:'ALERT-SOURCE-STALE',severity:'WARNING',component:'SYSTEM',code:'MONITORING_SOURCE_STALE',message:'One or more monitoring sources are stale.',value:provenance.stale_count,threshold:1,project_id,task_id,evidence:[],created_at:nowIso(clock),dashboard_authority:false,content_checksum:null});alerts=alerts.map(a=>a.content_checksum? a : Object.freeze({...a,content_checksum:checksumObject(a)}));const snapshot={monitoring_snapshot_version:MONITORING_VERSION,project_id,task_id,generated_at:nowIso(clock),health:healthFrom(alerts),metrics,alerts,source_revisions:structuredClone(source_revisions),source_provenance:provenance,canonical_authority:false,derived_rebuildable:true,previous_alert_count:previous_alerts.length};snapshot.content_checksum=checksumObject(snapshot);return deepFreeze(snapshot);}
export function verifyMonitoringSnapshot(snapshot){if(!snapshot||snapshot.monitoring_snapshot_version!==MONITORING_VERSION||snapshot.content_checksum!==checksumObject(snapshot)||snapshot.canonical_authority!==false)throw new Error('MONITORING_SNAPSHOT_INVALID');return true;}
