import { mkdir, open, readFile, rm } from 'node:fs/promises';
import path from 'node:path';
import { atomicWrite, resolveWritableInside, resolveExistingInside } from '../automation/util.mjs';
import { MonitoringError, checksumObject, deepFreeze } from './util.mjs';
import { verifyMonitoringEvent } from './event.mjs';
const ledgerRel='monitoring/events.jsonl'; const lockRel='monitoring/.events.lock';
const recordChecksum=(r)=>checksumObject(r,['record_checksum']);
async function acquire(root){await mkdir(path.join(root,'monitoring'),{recursive:true}); const lock=await resolveWritableInside(root,lockRel,MonitoringError,{escapeCode:'MONITORING_PATH_ESCAPE'}); try{const h=await open(lock,'wx',0o600);await h.writeFile(String(process.pid));await h.sync();await h.close();}catch(e){if(e.code==='EEXIST')throw new MonitoringError('MONITORING_LEDGER_BUSY');throw e;}}
async function release(root){const p=path.join(root,lockRel);await rm(p,{force:true}).catch(()=>{});}
export async function readMonitoringEventLedger(root){let target;try{target=await resolveExistingInside(root,ledgerRel,MonitoringError,{missingCode:'MONITORING_LEDGER_MISSING',escapeCode:'MONITORING_PATH_ESCAPE'});}catch(e){if(e.code==='MONITORING_LEDGER_MISSING')return deepFreeze([]);throw e;}const text=await readFile(target,'utf8');let prev=null;const rows=[];for(const line of text.split('\n').filter(Boolean)){let r;try{r=JSON.parse(line);}catch{throw new MonitoringError('MONITORING_LEDGER_CORRUPT');}if(r.seq!==rows.length+1||r.previous_record_checksum!==prev||r.record_checksum!==recordChecksum(r))throw new MonitoringError('MONITORING_LEDGER_CORRUPT');verifyMonitoringEvent(r.event);prev=r.record_checksum;rows.push(r);}return deepFreeze(rows);}
export async function appendMonitoringEvent(root,event){verifyMonitoringEvent(event);await acquire(root);try{const existing=await readMonitoringEventLedger(root);const rel=ledgerRel;const target=await resolveWritableInside(root,rel,MonitoringError,{escapeCode:'MONITORING_PATH_ESCAPE'});const row={seq:existing.length+1,event,previous_record_checksum:existing.at(-1)?.record_checksum??null};row.record_checksum=recordChecksum(row);await atomicWrite(root,rel,Buffer.from(`${existing.map(x=>JSON.stringify(x)).join('\n')}${existing.length?'\n':''}${JSON.stringify(row)}\n`),MonitoringError);const reread=await readMonitoringEventLedger(root);if(reread.at(-1)?.record_checksum!==row.record_checksum)throw new MonitoringError('MONITORING_LEDGER_VERIFY_FAILED');return deepFreeze(row);}finally{await release(root);}}
export async function verifyMonitoringEventLedger(root){const rows=await readMonitoringEventLedger(root);return deepFreeze({result:'MONITORING_EVENT_LEDGER_VERIFIED',event_count:rows.length,last_checksum:rows.at(-1)?.record_checksum??null});}
