import assert from 'node:assert/strict';import test from 'node:test';import {createHash} from 'node:crypto';import {mkdir,mkdtemp,readFile,rm,writeFile} from 'node:fs/promises';import path from 'node:path';
import {LifecycleStore,checksum} from '../../src/lifecycle/phase1/index.mjs';
const requested={actor_id:'builder',actor_type:'ROLE',role_id:'Builder',session_id:null,run_id:null};const owner={actor_id:'owner',actor_type:'OWNER',role_id:null,session_id:null,run_id:null};const applied={actor_id:'lifecycle',actor_type:'SYSTEM_COMPONENT',role_id:null,session_id:null,run_id:null};
function auth(task='TASK-004'){return {authorization_id:'OWNER-1',authority_type:'OWNER',authority_path:'authority.md',authority_checksum:'sha256:'+ 'a'.repeat(64),decision:'AUTHORIZED',effective_at:'2026-08-08T00:00:00Z',expires_at:'2027-01-01T00:00:00Z',scope:{task_id:task,phases:['CLOSURE','ARCHIVE','IMPLEMENTATION'],operations:['CANONICAL_STATE_COMMIT']}}}
async function fixture(t,overrides={}){const root=await mkdtemp('/mnt/data/task4-late-');t.after(()=>rm(root,{recursive:true,force:true}));const dir=path.join(root,'TASK-004');await mkdir(dir);await writeFile(path.join(root,'evidence.md'),'pass');const ev=[{path:'evidence.md',checksum:`sha256:${createHash('sha256').update('pass').digest('hex')}`,authoring_role:'Builder',result:'PASS',observed_at:'2026-08-08T00:00:00Z'}];const r={record_schema_version:'1.1.0',task_id:'TASK-004',project_id:'bai-development-os',record_revision:1,task_status:'ACTIVE',current_phase:'IMPLEMENTATION',gate_status:'PASS',authorization_status:'AUTHORIZED',archive_status:'NOT_ELIGIBLE',status_reason:'fixture',entered_at:'2026-08-08T00:00:00Z',updated_at:'2026-08-08T00:00:00Z',last_verified_at:'2026-08-08T00:00:00Z',requested_by:requested,authorized_by:owner,applied_by:applied,authorization_reference:auth(),authoritative_evidence:ev,blocking_items:[],next_eligible_phases:[],verification_result:'PASS',last_transition_id:'seed',...overrides};r.content_checksum=checksum(r);const store=new LifecycleStore(dir,{projectRoot:root,clock:()=>new Date('2026-08-08T00:00:01Z')});await store.init(r);return{store,ev,root,dir};}
function req(current,ev,to,extra={}){return{request_id:crypto.randomUUID(),task_id:'TASK-004',expected_revision:current.record_revision,from:Object.fromEntries(['task_status','current_phase','gate_status','authorization_status','archive_status'].map(k=>[k,current[k]])),to:{...Object.fromEntries(['task_status','current_phase','gate_status','authorization_status','archive_status'].map(k=>[k,current[k]])),...to},reason_code:'LATE_PHASE',reason:'late phase integration',requested_by:requested,authorized_by:owner,authorization_reference:auth(),evidence:ev,...extra};}
test('P2 canonical store persists ACTIVE -> BLOCKED -> ACTIVE with recovery contract',async(t)=>{const{store,ev}=await fixture(t);let c=await store.readRecord();c=await store.transition(req(c,ev,{task_status:'BLOCKED'},{operation_domain:'RECOVERY',record_patch:{blocking_items:['API unavailable'],checkpoint_reference:'checkpoint.json'}}),applied);assert.equal(c.task_status,'BLOCKED');assert.deepEqual(c.blocking_items,['API unavailable']);c=await store.transition(req(c,ev,{task_status:'ACTIVE'},{operation_domain:'RECOVERY',condition_verified:true,record_patch:{blocking_items:[],checkpoint_reference:null}}),applied);assert.equal(c.task_status,'ACTIVE');assert.equal(c.record_revision,3);});
test('P2 canonical store refuses blocked resume without condition verification',async(t)=>{const{store,ev}=await fixture(t,{task_status:'BLOCKED',blocking_items:['x']});const c=await store.readRecord();await assert.rejects(()=>store.transition(req(c,ev,{task_status:'ACTIVE'},{operation_domain:'RECOVERY'}),applied),e=>e.code==='NOT_CONFIRMED');});
test('P5 canonical store permits only ready Owner-authorized completion',async(t)=>{const{store,ev}=await fixture(t,{current_phase:'CLOSURE'});const c=await store.readRecord();await assert.rejects(()=>store.transition(req(c,ev,{task_status:'COMPLETED',archive_status:'READY'},{operation_domain:'CLOSURE',closure_ready:true}),applied),e=>e.code==='AUTHORIZATION_MISSING');const done=await store.transition(req(c,ev,{task_status:'COMPLETED',archive_status:'READY'},{operation_domain:'CLOSURE',closure_ready:true,owner_authorized:true}),applied);assert.equal(done.task_status,'COMPLETED');});
test('P5 archive is terminal and cannot reopen',async(t)=>{const{store,ev}=await fixture(t,{task_status:'COMPLETED',current_phase:'ARCHIVE',archive_status:'READY'});let c=await store.readRecord();c=await store.transition(req(c,ev,{task_status:'ARCHIVED',archive_status:'ARCHIVED'},{operation_domain:'ARCHIVE',archive_verified:true,owner_authorized:true}),applied);assert.equal(c.task_status,'ARCHIVED');await assert.rejects(()=>store.transition(req(c,ev,{task_status:'ACTIVE'},{operation_domain:'RECOVERY',owner_authorized:true}),applied),e=>e.code==='TERMINAL_REOPEN_FORBIDDEN');});
