import test from 'node:test'; import assert from 'node:assert/strict'; import { createHmac } from 'node:crypto'; import { mkdtemp, rm } from 'node:fs/promises'; import os from 'node:os'; import path from 'node:path';
import { createCredentialReference } from '../../src/integration/credentials.mjs';
import { verifyAndRecordWebhook } from '../../src/integration/webhook.mjs';
import { buildConnectorRegistry, createConnectorManifest } from '../../src/integration/registry.mjs';
import { createFunctionConnector } from '../../src/integration/adapters.mjs';
import { IntegrationGateway } from '../../src/integration/gateway.mjs';
import { createIntegrationRequest } from '../../src/integration/request.mjs';

test('integration credential metadata cannot hide token',()=>assert.throws(()=>createCredentialReference({credential_ref:'vault://a',provider:'v',metadata:{nested:{token:'abc'}}}),e=>e.code==='CREDENTIAL_INLINE_SECRET_FORBIDDEN'));
test('integration request blocks sensitive outbound payload before connector invocation',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'bai-sec-int-'));try{let called=0;const m=createConnectorManifest({connector_id:'mock',kind:'GENERIC',capabilities:[{name:'op',operations:['run'],side_effect:'NONE'}]});const c=createFunctionConnector(m,async()=>{called++;return{data:{ok:true}}});new IntegrationGateway({root,registry:buildConnectorRegistry([m]),connectors:{mock:c}});assert.throws(()=>createIntegrationRequest({project_id:'P',task_id:'TASK-009',connector_id:'mock',capability:'op',operation:'run',payload:{nested:{token:'secret'}}}),e=>e.code==='INTEGRATION_INLINE_SECRET_FORBIDDEN');assert.equal(called,0);}finally{await rm(root,{recursive:true,force:true});}});
test('webhook signature plus durable replay protection rejects duplicate event',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'bai-sec-hook-'));const body='{"x":1}',secret='abc',sig=createHmac('sha256',secret).update(body).digest('hex');const now=Date.parse('2026-08-08T00:00:00Z');try{await verifyAndRecordWebhook({root,body,signature:sig,secret,timestamp:'2026-08-08T00:00:00Z',event_id:'E1',provider:'p',project_id:'P',now});await assert.rejects(()=>verifyAndRecordWebhook({root,body,signature:sig,secret,timestamp:'2026-08-08T00:00:00Z',event_id:'E1',provider:'p',project_id:'P',now}),e=>e.code==='SECURITY_REPLAY_DETECTED');}finally{await rm(root,{recursive:true,force:true});}});
test('gateway enforces connector egress allowlist with trusted dns evidence',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'bai-sec-egress-'));try{let called=0;const m=createConnectorManifest({connector_id:'mock',kind:'GENERIC',metadata:{endpoint_url:'https://api.example.com/v1',egress_allow_hosts:['api.example.com']},capabilities:[{name:'op',operations:['run'],side_effect:'NONE'}]});const c=createFunctionConnector(m,async()=>{called++;return{data:{ok:true}}});const g=new IntegrationGateway({root,registry:buildConnectorRegistry([m]),connectors:{mock:c},dns_resolver:async()=>['93.184.216.34']});const req=createIntegrationRequest({project_id:'P',task_id:'TASK-009',connector_id:'mock',capability:'op',operation:'run',payload:{x:1}});const out=await g.execute(req);assert.equal(out.ok,true);assert.equal(called,1);}finally{await rm(root,{recursive:true,force:true});}});
test('gateway blocks private resolved connector endpoint',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'bai-sec-egress-'));try{let called=0;const m=createConnectorManifest({connector_id:'mock',kind:'GENERIC',metadata:{endpoint_url:'https://api.example.com/v1',egress_allow_hosts:['api.example.com']},capabilities:[{name:'op',operations:['run'],side_effect:'NONE'}]});const c=createFunctionConnector(m,async()=>{called++;return{data:{ok:true}}});const g=new IntegrationGateway({root,registry:buildConnectorRegistry([m]),connectors:{mock:c},dns_resolver:async()=>['127.0.0.1']});const req=createIntegrationRequest({project_id:'P',task_id:'TASK-009',connector_id:'mock',capability:'op',operation:'run',payload:{x:1}});await assert.rejects(()=>g.execute(req),e=>e.code==='INTEGRATION_EGRESS_POLICY_BLOCKED');assert.equal(called,0);}finally{await rm(root,{recursive:true,force:true});}});
