import test from 'node:test'; import assert from 'node:assert/strict';
import { rebuildWorkspaceRegistry, verifyWorkspaceRegistry, resolveRuntimeProfile, resolveEnvironmentCapabilities, resolveProject, resolveRisk, buildRoleStartupPackage, compileOrchestratorInstruction, createAutomationPlan, executeConditionalAutomation, proposeLifecycleAction, checkCrossFormatConsistency } from '../../src/automation/index.mjs';
const root=process.cwd();
test('TASK-006 end-to-end read/verify automation preserves authority boundaries',async()=>{
 const registry=await rebuildWorkspaceRegistry(root,{include_extensions:['.md','.json','.yaml','.mjs']}); await verifyWorkspaceRegistry(root,registry);
 const runtimeProfile=resolveRuntimeProfile({platform:process.platform,shell:process.platform==='win32'?'powershell':'bash',probe_evidence:`node:${process.version}`,capabilities:['NODE_RUNTIME']}); const runtime=resolveEnvironmentCapabilities({runtime_profile:runtimeProfile,toolchains:[{name:'node',available:true,capabilities:['JS']}],required_capabilities:['NODE_RUNTIME'],required_tools:['node']});
 const project=resolveProject({project_id:'BAI-Development-OS',project_root:root,registry}); const risk=resolveRisk({system_scale:'FOUNDATION',feature_scale:'LARGE',criticality:'FOUNDATION',failure_impact:'CRITICAL',reversibility:'HARD',novelty:'NEW_ARCHITECTURE',change_kind:'ARCHITECTURE',touches_authorization:true,touches_state_machine:true,cross_project_contract:true});
 const startup=buildRoleStartupPackage({project_id:'BAI-Development-OS',task_id:'TASK-006',role:'Builder',phase:'IMPLEMENTATION',runtime_resolution:runtime,project_resolution:project,risk_resolution:risk,knowledge_integration:{result:'KNOWLEDGE_NOT_REQUIRED',pack:null},lifecycle_snapshot:{task_id:'TASK-006',status_revision:1,status:'ACTIVE'},model_profiles:[{model_id:'local-test',capabilities:['code'],context_capacity:10000,tools:['shell'],max_sensitivity:'RESTRICTED',reliability:1,estimated_cost_microusd:0}],model_request:{capabilities:['code'],context_tokens:10,required_tools:['shell'],sensitivity:'INTERNAL'},allowed_paths:['src/automation/**'],protected_paths:['tasks/TASK-004/**','tasks/TASK-005/**'],stop_conditions:['NOT_AUTHORIZED'],expected_outputs:['implementation','tests']});
 const instruction=compileOrchestratorInstruction({startup_package:startup,task_definition:'Implement TASK-006',role_specification:'Builder must preserve lifecycle and knowledge authority boundaries'}); const plan=createAutomationPlan({startup_package:startup,instruction,actions:[{action_id:'verify-registry',kind:'VERIFY'}]}); const result=await executeConditionalAutomation(plan,{startup_package:startup,executor:async()=>({ok:true})}); assert.equal(result.result,'AUTOMATION_RUN_COMPLETE'); assert.equal(plan.lifecycle_mutation_authority,false); assert.equal(plan.knowledge_content_authority,false); const proposal=proposeLifecycleAction({task_id:'TASK-006',current_status:'ACTIVE',target_status:'PAUSED',reason:'example'}); assert.equal(proposal.applied,false);
});
test('cross-format checker explicitly safe-stops on absent marker',()=>assert.equal(checkCrossFormatConsistency({markdown_text:'TASK-006',summary_text:'TASK-006',required_markers:['CURRENT_CANONICAL']}).result,'DOCUMENT_CONSISTENCY_UNKNOWN'));
