export const DESIGN_GOVERNANCE_SCHEMA_VERSION = '1.0.0';

export const INTAKE_STATES = Object.freeze([
  'RECEIVED', 'INTEGRITY_VERIFIED', 'CURATED', 'REVALIDATED',
  'COVERAGE_MAPPED', 'GAPS_ADJUDICATED', 'DESIGN_REVIEWED',
  'OWNER_DECISION_REQUIRED', 'AUTHORIZED', 'DEFERRED', 'REJECTED',
  'QUARANTINED', 'PARKED', 'STALE',
]);

export const TERMINAL_INTAKE_STATES = Object.freeze([
  'AUTHORIZED', 'DEFERRED', 'REJECTED', 'QUARANTINED', 'PARKED', 'STALE',
]);

export const INTAKE_TRANSITIONS = Object.freeze({
  RECEIVED: ['INTEGRITY_VERIFIED', 'QUARANTINED', 'PARKED'],
  INTEGRITY_VERIFIED: ['CURATED', 'QUARANTINED', 'PARKED', 'STALE'],
  CURATED: ['REVALIDATED', 'QUARANTINED', 'PARKED', 'STALE'],
  REVALIDATED: ['COVERAGE_MAPPED', 'QUARANTINED', 'PARKED', 'STALE'],
  COVERAGE_MAPPED: ['GAPS_ADJUDICATED', 'QUARANTINED', 'PARKED', 'STALE'],
  GAPS_ADJUDICATED: ['DESIGN_REVIEWED', 'QUARANTINED', 'PARKED', 'STALE'],
  DESIGN_REVIEWED: ['OWNER_DECISION_REQUIRED', 'QUARANTINED', 'PARKED', 'STALE'],
  OWNER_DECISION_REQUIRED: ['AUTHORIZED', 'DEFERRED', 'REJECTED', 'STALE'],
});

export const CLAIM_RESULTS = Object.freeze([
  'CONFIRMED_CURRENT', 'CONFIRMED_HISTORICAL', 'ALREADY_IMPLEMENTED',
  'PARTIALLY_IMPLEMENTED', 'SUPERSEDED', 'CONFLICTS_WITH_CURRENT_CANONICAL',
  'UNVERIFIED', 'MISSING_EVIDENCE',
]);

export const BLOCKING_CLAIM_RESULTS = Object.freeze([
  'SUPERSEDED', 'CONFLICTS_WITH_CURRENT_CANONICAL', 'UNVERIFIED', 'MISSING_EVIDENCE',
]);

export const COVERAGE_STATES = Object.freeze(['IMPLEMENTED', 'PARTIAL', 'MISSING', 'NOT_APPLICABLE']);
export const SEVERITIES = Object.freeze(['INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL']);
export const COMPLETENESS_RESULTS = Object.freeze(['PASS', 'FAIL', 'STALE', 'OWNER_DECISION_REQUIRED']);
export const CANDIDATE_ROUTES = Object.freeze(['TASK', 'KNOWLEDGE', 'REJECT', 'DEFER']);
export const OWNERSHIP_CLASSES = Object.freeze(['OS', 'CONSUMER', 'SHARED_REFERENCE', 'UNKNOWN']);
export const SENSITIVITY_CLASSES = Object.freeze(['PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED']);
export const DESIGN_SECTION_COUNT = 30;
