import { COMPATIBILITY_LEVEL, CONFORMANCE_STATUS, EVIDENCE_LEVEL } from './constants.mjs';
import { ConformanceError } from './errors.mjs';
import { deepFreeze, newId, nowIso, sha256, stable } from './util.mjs';

const levels=Object.values(COMPATIBILITY_LEVEL); const evidenceRank={DECLARED:1,SIMULATED:2,SANDBOX:3,REAL:4};
export function deriveCompatibilityLevel({verified_execution_count=0,isolation=false,portability=false,adversarial=false,contract=false}={}){ if(adversarial&&portability&&isolation&&verified_execution_count>=2)return COMPATIBILITY_LEVEL.C5_ADVERSARIAL; if(portability&&isolation&&verified_execution_count>=2)return COMPATIBILITY_LEVEL.C4_PORTABLE; if(isolation&&verified_execution_count>=2)return COMPATIBILITY_LEVEL.C3_MULTI_PROJECT; if(verified_execution_count>=1)return COMPATIBILITY_LEVEL.C2_SINGLE_PROJECT; if(contract)return COMPATIBILITY_LEVEL.C1_CONTRACT; return COMPATIBILITY_LEVEL.C0_UNVERIFIED; }
export function createCertification({subject,results=[],matrix=null,scope={},clock=()=>new Date(),required_level='C1_CONTRACT'}={}){
  if(!levels.includes(required_level))throw new ConformanceError('CONFORMANCE_LEVEL_INVALID'); const fail=results.filter(r=>r.status===CONFORMANCE_STATUS.FAIL); const conditional=results.filter(r=>r.status===CONFORMANCE_STATUS.CONDITIONAL); const evidenceLevels=(scope.fixtures??[]).map(f=>f.evidence_level); const real=evidenceLevels.filter(x=>x===EVIDENCE_LEVEL.REAL||x===EVIDENCE_LEVEL.SANDBOX).length;
  const flags={contract:results.some(r=>r.category==='CONTRACT'&&r.status==='PASS'),isolation:results.some(r=>r.category==='ISOLATION'&&r.status==='PASS'),portability:results.some(r=>r.category==='PORTABILITY'&&r.status==='PASS'),adversarial:results.some(r=>r.category==='ADVERSARIAL'&&r.status==='PASS')};
  const executedProjects=new Set(results.filter(r=>r.category==='EXECUTION'&&r.status==='PASS'&&(r.evidence_level==='REAL'||r.evidence_level==='SANDBOX')).map(r=>r.project_id).filter(Boolean)); const level=deriveCompatibilityLevel({verified_execution_count:executedProjects.size,...flags}); const levelOk=levels.indexOf(level)>=levels.indexOf(required_level); const status=fail.length||!levelOk?CONFORMANCE_STATUS.FAIL:(conditional.length||evidenceLevels.some(x=>evidenceRank[x]<3)?CONFORMANCE_STATUS.CONDITIONAL:CONFORMANCE_STATUS.PASS);
  const body={certification_version:'1.0.0',certification_id:newId('cert'),subject,generated_at:nowIso(clock),status,compatibility_level:level,required_level,matrix_id:matrix?.matrix_id??null,scope:{...scope,fixtures:(scope.fixtures??[]).map(f=>({fixture_id:f.fixture_id,project_id:f.project_id,evidence_level:f.evidence_level}))},execution_summary:{verified_projects:[...executedProjects].sort(),verified_count:executedProjects.size},result_summary:{total:results.length,pass:results.filter(r=>r.status==='PASS').length,conditional:conditional.length,fail:fail.length,not_applicable:results.filter(r=>r.status==='NOT_APPLICABLE').length},limitations:[...conditional.map(r=>r.limitation).filter(Boolean),...(evidenceLevels.includes('DECLARED')?['DECLARED_FIXTURES_ARE_NOT_EXECUTION_EVIDENCE']:[])],results:structuredClone(results)}; return deepFreeze({...body,certification_checksum:sha256(stable(body))});
}
