export const CONFORMANCE_STATUS = Object.freeze({ PASS:'PASS', CONDITIONAL:'CONDITIONAL', FAIL:'FAIL', NOT_APPLICABLE:'NOT_APPLICABLE' });
export const EVIDENCE_LEVEL = Object.freeze({ REAL:'REAL', SANDBOX:'SANDBOX', SIMULATED:'SIMULATED', DECLARED:'DECLARED' });
export const COMPATIBILITY_LEVEL = Object.freeze({
  C0_UNVERIFIED:'C0_UNVERIFIED',
  C1_CONTRACT:'C1_CONTRACT',
  C2_SINGLE_PROJECT:'C2_SINGLE_PROJECT',
  C3_MULTI_PROJECT:'C3_MULTI_PROJECT',
  C4_PORTABLE:'C4_PORTABLE',
  C5_ADVERSARIAL:'C5_ADVERSARIAL'
});
export const RESOURCE_TYPES = Object.freeze(['KNOWLEDGE','AUTHORIZATION','STARTUP','OUTBOX','MONITORING','CREDENTIAL','IDEMPOTENCY','WEBHOOK','VAULT','SIGNER','TRUST_ANCHOR','SECURITY_POLICY','RELEASE_STATE']);
export const SCALES = Object.freeze(['SMALL','MEDIUM','LARGE']);
export const RISK_TIERS = Object.freeze(['LOW','STANDARD','CORE_CRITICAL','FOUNDATION_CRITICAL']);
