import { CONFORMANCE_STATUS, EVIDENCE_LEVEL, RISK_TIERS, SCALES } from './constants.mjs';
import { ConformanceError } from './errors.mjs';
import { deepFreeze, safeId, requireString, sortStrings, uniq } from './util.mjs';

const evidenceLevels = new Set(Object.values(EVIDENCE_LEVEL));
const scales = new Set(SCALES);
const risks = new Set(RISK_TIERS);
function evidence(value, fallback='DECLARED'){ const v=(value??fallback).toUpperCase(); if(!evidenceLevels.has(v)) throw new ConformanceError('CONFORMANCE_EVIDENCE_LEVEL_INVALID'); return v; }
function stringArray(value,name){ if(!Array.isArray(value)||value.length===0) throw new ConformanceError('CONFORMANCE_FIXTURE_INVALID',`${name} must be a non-empty array`); return sortStrings(uniq(value.map((x)=>requireString(x,name)))); }
function normalizeConsumerContract(value={mode:'NONE'}){ const mode=(value.mode??'NONE').toUpperCase(); const trust=(value.trust??'DECLARED_ONLY').toUpperCase(); if(!['DECLARED_ONLY','TRUSTED_LOCAL','SANDBOXED'].includes(trust)) throw new ConformanceError('CONFORMANCE_CONTRACT_INVALID','invalid consumer contract trust'); if(!['NONE','NODE_TEST','NODE_SCRIPT','NPM_SCRIPT'].includes(mode)) throw new ConformanceError('CONFORMANCE_CONTRACT_INVALID','unsupported consumer contract mode'); if(mode==='NODE_TEST'||mode==='NODE_SCRIPT'){ const target=requireString(value.target,'consumer contract target').replaceAll('\\','/'); if(target.startsWith('/')||target.split('/').includes('..')) throw new ConformanceError('CONFORMANCE_CONTRACT_INVALID','consumer contract target must be relative'); return deepFreeze({mode,target,trust}); } if(mode==='NPM_SCRIPT') return deepFreeze({mode,script:safeId(value.script,'consumer contract script'),trust}); return deepFreeze({mode:'NONE',trust}); }
function normalizeProviders(items=[]){ if(!Array.isArray(items)) throw new ConformanceError('CONFORMANCE_FIXTURE_INVALID','providers must be an array'); return items.map((p)=>deepFreeze({capability:safeId(p.capability,'provider capability'),provider_id:safeId(p.provider_id,'provider id'),evidence_level:evidence(p.evidence_level,'SIMULATED'),region:p.region?requireString(p.region,'provider region'):null})).sort((a,b)=>`${a.capability}:${a.provider_id}`.localeCompare(`${b.capability}:${b.provider_id}`)); }
export function createConformanceFixture(input={}){
  const fixture_id=safeId(input.fixture_id,'fixture_id'); const project_id=safeId(input.project_id,'project_id');
  const scale=(input.scale??'SMALL').toUpperCase(); const risk_tier=(input.risk_tier??'STANDARD').toUpperCase(); if(!scales.has(scale)||!risks.has(risk_tier)) throw new ConformanceError('CONFORMANCE_FIXTURE_INVALID','scale or risk tier invalid');
  const p=input.platform??{}; const platform={os:requireString(p.os??process.platform,'platform.os').toLowerCase(),arch:requireString(p.arch??process.arch,'platform.arch').toLowerCase(),filesystem:requireString(p.filesystem??'generic','platform.filesystem').toLowerCase(),evidence_level:evidence(p.evidence_level,'DECLARED')};
  const runtime=input.runtime??{}; const security=input.security??{};
  const fixture={fixture_schema_version:'1.0.0',fixture_id,project_id,name:requireString(input.name??project_id,'name'),scale,risk_tier,domains:stringArray(input.domains??['software'],'domains'),languages:stringArray(input.languages??['javascript'],'languages'),runtime:{name:requireString(runtime.name??'node','runtime.name'),version:runtime.version?requireString(runtime.version,'runtime.version'):null,shell:requireString(runtime.shell??'sh','runtime.shell')},platform,providers:normalizeProviders(input.providers),consumer_contract:normalizeConsumerContract(input.consumer_contract),security:{vault_namespace:safeId(security.vault_namespace??`${project_id}:vault`,'vault namespace'),signer_namespace:safeId(security.signer_namespace??`${project_id}:signer`,'signer namespace'),trust_namespace:safeId(security.trust_namespace??`${project_id}:trust`,'trust namespace'),policy_namespace:safeId(security.policy_namespace??`${project_id}:policy`,'policy namespace')},release:{current_version:input.release?.current_version??null,supported_versions:sortStrings(input.release?.supported_versions??[])},capabilities:sortStrings(uniq(input.capabilities??[])),tags:sortStrings(uniq(input.tags??[])),evidence_level:evidence(input.evidence_level??platform.evidence_level,'DECLARED')};
  return deepFreeze(fixture);
}
export function fixtureEvidenceStatus(fixture){ if(fixture.evidence_level==='REAL'||fixture.evidence_level==='SANDBOX') return CONFORMANCE_STATUS.PASS; if(fixture.evidence_level==='SIMULATED') return CONFORMANCE_STATUS.CONDITIONAL; return CONFORMANCE_STATUS.CONDITIONAL; }
export const referenceFixtures=()=>deepFreeze([
  createConformanceFixture({fixture_id:'javascript-roulette',project_id:'javascript-roulette',name:'JavaScript Roulette Reference Consumer',scale:'SMALL',risk_tier:'STANDARD',domains:['software','automation'],languages:['javascript'],platform:{os:process.platform,arch:process.arch,filesystem:'local',evidence_level:'REAL'},runtime:{name:'node',version:process.versions.node,shell:process.platform==='win32'?'powershell':'sh'},evidence_level:'REAL',consumer_contract:{mode:'NODE_TEST',target:'tests/roulette-core.test.mjs',trust:'TRUSTED_LOCAL'},capabilities:['consumer-contract','release-upgrade','boundary']}),
  createConformanceFixture({fixture_id:'make-tiktok-gift-master-declared',project_id:'makeTikTokGiftMaster',name:'makeTikTokGiftMaster Declared Reference',scale:'MEDIUM',risk_tier:'CORE_CRITICAL',domains:['software','streaming','automation'],languages:['javascript','java'],platform:{os:'multi',arch:'multi',filesystem:'mixed',evidence_level:'DECLARED'},runtime:{name:'heterogeneous',shell:'mixed'},evidence_level:'DECLARED',consumer_contract:{mode:'NONE'},capabilities:['external-integration','creator-tech']})
]);
