export const CONTEXT_ERROR_CODES = Object.freeze([
  'CONTEXT_INVENTORY_INCOMPLETE', 'CONTEXT_HARD_STOP', 'CONTEXT_PATH_NOT_ABSOLUTE',
  'CONTEXT_PATH_TRAVERSAL_DETECTED', 'CONTEXT_PATH_OUTSIDE_ALLOWED_ROOT',
  'CONTEXT_PATH_PREFIX_SPOOF_DETECTED', 'CONTEXT_SYMLINK_INPUT_REJECTED',
  'CONTEXT_SYMLINK_BROKEN', 'CONTEXT_SYMLINK_LOOP', 'CONTEXT_FILESYSTEM_OBJECT_UNSUPPORTED',
  'CONTEXT_PATH_CHANGED_BEFORE_READ', 'CONTEXT_PATH_CHANGED_DURING_READ',
  'CONTEXT_INPUT_IDENTITY_MISMATCH', 'CONTEXT_ALLOWED_ROOT_INVALID',
  'CONTEXT_OWNER_OVERRIDE_INVALID', 'CONTEXT_EVIDENCE_SESSION_EXISTS',
  'CONTEXT_EVIDENCE_CORRUPT', 'CONTEXT_PERMIT_REUSED',
  'CONTEXT_PREFLIGHT_RESULT_REQUIRED', 'CONTEXT_PREFLIGHT_EVIDENCE_REQUIRED',
  'CONTEXT_PREFLIGHT_RESULT_INVALID', 'CONTEXT_PREFLIGHT_CHECKSUM_MISMATCH',
  'CONTEXT_PREFLIGHT_BINDING_MISMATCH', 'CONTEXT_OUTPUT_ESTIMATION_REQUIRED',
  'CONTEXT_OUTPUT_ESTIMATION_INVALID', 'CONTEXT_PERMIT_DECISION_INELIGIBLE',
  'CONTEXT_PERMIT_PREFLIGHT_BINDING_MISSING',
  'CONTEXT_GATEWAY_PREFLIGHT_VERIFICATION_FAILED', 'CONTEXT_LEGACY_PERMIT_REJECTED',
  'CONTEXT_ROLE_ACTIVATION_PERMIT_MISSING', 'CONTEXT_ROLE_ACTIVATION_PERMIT_INVALID',
  'CONTEXT_ROLE_ACTIVATION_PERMIT_EXPIRED', 'CONTEXT_ROLE_ACTIVATION_PERMIT_ALREADY_CONSUMED',
  'CONTEXT_ROLE_ACTIVATION_PERMIT_EVENT_CHAIN_INVALID',
  'CONTEXT_ROLE_ACTIVATION_PERMIT_LOCK_CONFLICT',
  'CONTEXT_ROLE_ACTIVATION_PERMIT_LOCK_UNCERTAIN',
  'CONTEXT_ROLE_ACTIVATION_PERMIT_LEDGER_SYNC_FAILED',
  'CONTEXT_ROLE_ACTIVATION_PERMIT_LEDGER_VERIFY_FAILED',
  'CONTEXT_ROLE_ACTIVATION_PERMIT_STALE_LEASE',
  'CONTEXT_ROLE_ACTIVATION_ENTRY_UNCLASSIFIED',
  'CONTEXT_ROLE_ACTIVATION_DIRECT_EXECUTOR_ACCESS',
  'OVERRIDE_SCHEMA_REQUIRED_FIELD_MISSING', 'OVERRIDE_SCHEMA_TYPE_INVALID',
  'OVERRIDE_SCHEMA_ENUM_INVALID', 'OVERRIDE_SCHEMA_MINIMUM_VIOLATION',
  'OVERRIDE_SCHEMA_UNKNOWN_FIELD', 'OVERRIDE_SCHEMA_CONSTRAINT_VIOLATION',
  'OVERRIDE_SCHEMA_TIMESTAMP_INVALID', 'OVERRIDE_SCHEMA_TEMPORAL_ORDER_INVALID',
  'ROLE_ACTIVATION_STATE_UNKNOWN',
]);

export class ContextGuardError extends Error {
  constructor(code, message = code) {
    super(message);
    this.name = 'ContextGuardError';
    this.code = code;
  }
}

export const fail = (code, message) => { throw new ContextGuardError(code, message); };
