import test from 'node:test'; import assert from 'node:assert/strict';
import { createDistributedEventEnvelope, verifyDistributedEventEnvelope, createWorkerAdvertisement, verifyWorkerAdvertisement, evaluateWorkerEligibility, issueDistributedLease, renewDistributedLease, verifyDistributedLease, DistributedError } from '../../src/distributed/index.mjs';
import { fixedClock } from './helpers.mjs';

test('event envelope is checksummed and verified',()=>{ const e=createDistributedEventEnvelope({event_type:'work',project_id:'p1',payload:{x:1}},{clock:fixedClock()}); assert.equal(verifyDistributedEventEnvelope(e),true); assert.equal(e.project_id,'p1'); });
test('event envelope tamper is rejected',()=>{ const e=createDistributedEventEnvelope({event_type:'work',project_id:'p1',payload:{x:1}}); assert.throws(()=>verifyDistributedEventEnvelope({...e,payload:{x:2}}),/DISTRIBUTED_EVENT_TAMPERED/); });
test('event payload ceiling enforced',()=>assert.throws(()=>createDistributedEventEnvelope({event_type:'work',project_id:'p1',payload:{x:'12345'}},{max_payload_bytes:3}),/DISTRIBUTED_PAYLOAD_TOO_LARGE/));
test('evidence class is preserved',()=>{ const e=createDistributedEventEnvelope({event_type:'metric',project_id:'p1',evidence_class:'SIMULATED'}); assert.equal(e.evidence_class,'SIMULATED'); });
test('invalid evidence class rejected',()=>assert.throws(()=>createDistributedEventEnvelope({event_type:'metric',project_id:'p1',evidence_class:'SUPERREAL'}),/DISTRIBUTED_ENUM_INVALID/));
test('worker advertisement requires attestation for ATTESTED',()=>assert.throws(()=>createWorkerAdvertisement({worker_id:'w1',trust_state:'ATTESTED'}),/DISTRIBUTED_WORKER_ATTESTATION_REQUIRED/));
test('worker advertisement verifies checksum',()=>{ const w=createWorkerAdvertisement({worker_id:'w1',trust_state:'ATTESTED',attestation_ref:'att:1',capabilities:['node-test','sandbox']}); assert.equal(verifyWorkerAdvertisement(w),true); });
test('worker eligibility checks capability',()=>{ const w=createWorkerAdvertisement({worker_id:'w1',trust_state:'ATTESTED',attestation_ref:'att:1',capabilities:['node-test']}); assert.equal(evaluateWorkerEligibility(w,{capabilities:['node-test'],require_attested:true}).result,'ELIGIBLE'); assert.equal(evaluateWorkerEligibility(w,{capabilities:['gpu']}).result,'INELIGIBLE'); });
test('worker eligibility checks provider checksum',()=>{ const w=createWorkerAdvertisement({worker_id:'w1',provider_checksums:{p:'sha256:a'}}); assert.equal(evaluateWorkerEligibility(w,{provider_checksums:{p:'sha256:b'}}).provider_mismatches[0],'p'); });
test('revoked worker is ineligible',()=>{ const w=createWorkerAdvertisement({worker_id:'w1',trust_state:'REVOKED'}); assert.equal(evaluateWorkerEligibility(w,{}).result,'INELIGIBLE'); });
test('lease validates owner scope and token',()=>{ const l=issueDistributedLease({scope:'job:1',owner_id:'w1',epoch:1,ttl_ms:60000},{clock:fixedClock()}); assert.equal(verifyDistributedLease(l,{now:Date.parse('2026-08-08T12:00:30Z'),scope:'job:1',owner_id:'w1',fencing_token:l.fencing_token}),true); });
test('expired lease fails closed',()=>{ const l=issueDistributedLease({scope:'job:1',owner_id:'w1',ttl_ms:1000},{clock:fixedClock()}); assert.throws(()=>verifyDistributedLease(l,{now:Date.parse('2026-08-08T12:00:02Z')}),/DISTRIBUTED_LEASE_EXPIRED/); });
test('lease renewal advances epoch and fencing',()=>{ const l=issueDistributedLease({scope:'job:1',owner_id:'w1',epoch:1}); const n=renewDistributedLease(l); assert.equal(n.epoch,2); assert.notEqual(n.fencing_token,l.fencing_token); });
test('non-advanced lease epoch rejected',()=>{ const l=issueDistributedLease({scope:'job:1',owner_id:'w1',epoch:2}); assert.throws(()=>issueDistributedLease({scope:'job:1',owner_id:'w2',epoch:2,previous_lease:l}),/DISTRIBUTED_LEASE_EPOCH_NOT_ADVANCED/); });
test('DistributedError includes code in message',()=>{ const e=new DistributedError('D_CODE','detail'); assert.match(e.message,/D_CODE/); assert.equal(e.code,'D_CODE'); });
