import test from 'node:test';import assert from 'node:assert/strict';
import { compareDevelopmentProfiles, detectGovernanceImbalance, detectPolicyOscillation, rankCalibrationOpportunities } from '../../src/calibration/diagnostics.mjs';

test('profile outcomes compare cost quality and owner friction',()=>{const r=compareDevelopmentProfiles([{profile_id:'DEV_1_LIGHT',token_cost:10,lead_time_ms:100,defect_escape:0,critic_findings:0,test_failures:0,owner_override:0},{profile_id:'DEV_1_LIGHT',token_cost:20,lead_time_ms:200,defect_escape:0,critic_findings:1,test_failures:0,owner_override:1}]);assert.equal(r.profiles[0].avg_token_cost,15);assert.equal(r.profiles[0].owner_override_rate,.5);});
test('possible over-governance is advisory not automatic de-escalation',()=>{const r=detectGovernanceImbalance([{run_id:'r1',profile_id:'DEV_3_HIGH_ASSURANCE',criticality:'STANDARD',failure_impact:'LOW',reversible:true,critic_findings:0,test_failures:0,defect_escape:0}]);assert.equal(r.findings[0].finding,'POSSIBLE_OVER_GOVERNANCE');assert.equal(r.blocking_count,0);});
test('foundation under-assurance is blocking',()=>{const r=detectGovernanceImbalance([{run_id:'r1',profile_id:'DEV_3_HIGH_ASSURANCE',criticality:'FOUNDATION',failure_impact:'HIGH'}]);assert.equal(r.blocking_count,1);});
test('core under-assurance is blocking',()=>{const r=detectGovernanceImbalance([{run_id:'r1',profile_id:'DEV_2_STANDARD',criticality:'CORE',failure_impact:'MODERATE'}]);assert.equal(r.blocking_count,1);});
test('policy ABAB oscillation is detected',()=>{const r=detectPolicyOscillation([{policy_key:'x',value:1},{policy_key:'x',value:2},{policy_key:'x',value:1},{policy_key:'x',value:2}],{policy_key:'x'});assert.equal(r.result,'POLICY_OSCILLATION_DETECTED');});
test('stable policy does not fabricate oscillation',()=>{const r=detectPolicyOscillation([{policy_key:'x',value:1},{policy_key:'x',value:1},{policy_key:'x',value:1},{policy_key:'x',value:1}],{policy_key:'x'});assert.equal(r.result,'NO_POLICY_OSCILLATION');});
test('maintenance/calibration work can be ranked by risk reduction per cost/time',()=>{const r=rankCalibrationOpportunities([{id:'low',risk_reduction:2,cost:5,time:5},{id:'high',risk_reduction:10,cost:1,time:1}]);assert.equal(r[0].id,'high');});
