import test from 'node:test';import assert from 'node:assert/strict';import { mkdtemp } from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import { CalibrationService } from '../../src/calibration/service.mjs';
import { evaluator, fixedClock } from './helpers.mjs';

async function seededService({applier=null}={}){const root=await mkdtemp(path.join(os.tmpdir(),'cal-service-'));const s=new CalibrationService({root,clock:fixedClock,policy_applier:applier});for(const [i,v] of [0,1,1,1,2,1,0,1,1,2].entries())await s.recordEvidence({evidence_id:`CE-${i}`,project_id:'p',task_id:'TASK-014',subsystem:'GOVERNANCE',metric:'review_cycles_used',value:v,source:'TEST'});return s;}
const cases=[1,2,3].map(i=>({case_id:`c${i}`,baseCost:10,proposedCost:8,baseQuality:10,proposedQuality:10,baseRisk:1,proposedRisk:1}));
test('service executes evidence -> report -> candidate -> replay/shadow -> activation',async()=>{let applied=null;const s=await seededService({applier:async x=>{applied=x;}});const report=await s.analyze();const candidate=await s.propose({report,selected_policy_keys:['governance.review_cycle_cap']});const ev=await s.evaluate(candidate,{counterfactual_cases:cases,shadow_cases:cases,evaluator});const activation=await s.activate(candidate,{evaluations:ev,owner_authorization_ref:'OWNER-1',policy_authorization_ref:'POLICY-1'});assert.equal(activation.authority_effect,'AUTHORIZED_ADVISORY_POLICY_ACTIVATION_ONLY');assert.ok(applied);assert.equal((await s.snapshot()).active_advisory_policy['governance.review_cycle_cap'],candidate.adjustments[0].proposed_value);});
test('activation requires Owner authorization',async()=>{const s=await seededService();const c=await s.propose({selected_policy_keys:['governance.review_cycle_cap']});const ev=await s.evaluate(c,{counterfactual_cases:cases,shadow_cases:cases,evaluator});await assert.rejects(()=>s.activate(c,{evaluations:ev,policy_authorization_ref:'P'}),/owner_authorization_ref/);});
test('activation requires Policy authorization',async()=>{const s=await seededService();const c=await s.propose({selected_policy_keys:['governance.review_cycle_cap']});const ev=await s.evaluate(c,{counterfactual_cases:cases,shadow_cases:cases,evaluator});await assert.rejects(()=>s.activate(c,{evaluations:ev,owner_authorization_ref:'O'}),/policy_authorization_ref/);});
test('activation refuses failed shadow/counterfactual gate',async()=>{const s=await seededService();const c=await s.propose({selected_policy_keys:['governance.review_cycle_cap']});const ev=await s.evaluate(c,{counterfactual_cases:cases,shadow_cases:[{...cases[0],proposedRisk:9},cases[1],cases[2]],evaluator});await assert.rejects(()=>s.activate(c,{evaluations:ev,owner_authorization_ref:'O',policy_authorization_ref:'P'}),/GATE_NOT_PASSED/);});
test('store verification succeeds after workflow',async()=>{const s=await seededService();assert.match((await s.verifyStore()).result,/VERIFIED/);});
