import test from 'node:test';import assert from 'node:assert/strict';import { mkdtemp, rm } from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import { buildConnectorRegistry, createConnectorManifest, createCredentialReference, createFunctionConnector, createIntegrationRequest, IntegrationGateway, readIntegrationAudit } from '../../src/integration/index.mjs';
const clock=()=>new Date('2026-08-08T00:00:00Z');
function setup({invoke=async({payload})=>({data:{echo:payload}}),side_effect='NONE',retry_safe=undefined,required_scopes=[],metadata={},trust='REFERENCE'}={}){const m=createConnectorManifest({connector_id:'mock',kind:'GENERIC',response_trust:trust,metadata,capabilities:[{name:'op',operations:['run'],side_effect,retry_safe,required_scopes}]});const c=createFunctionConnector(m,invoke);return{m,c,registry:buildConnectorRegistry([m])};}
const req=(extra={})=>createIntegrationRequest({project_id:'P1',task_id:'TASK-008',run_id:'R1',connector_id:'mock',capability:'op',operation:'run',payload:{x:1},...extra});
test('successful read executes and returns noncanonical reference',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'bai-int-'));try{const s=setup();const g=new IntegrationGateway({root,registry:s.registry,connectors:{mock:s.c},clock});const r=await g.execute(req());assert.equal(r.ok,true);assert.equal(r.canonical,false);assert.equal(r.trust,'REFERENCE');}finally{await rm(root,{recursive:true,force:true});}});
test('verified connector can mark response verified but still noncanonical',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'bai-int-'));try{const s=setup({trust:'VERIFIED'});const r=await new IntegrationGateway({root,registry:s.registry,connectors:{mock:s.c},clock}).execute(req());assert.equal(r.trust,'VERIFIED');assert.equal(r.canonical,false);assert.equal(r.requires_review_for_canonicalization,false);}finally{await rm(root,{recursive:true,force:true});}});
test('missing runtime connector blocks',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'bai-int-'));try{const s=setup();await assert.rejects(()=>new IntegrationGateway({root,registry:s.registry,connectors:{},clock}).execute(req()),e=>e.code==='CONNECTOR_RUNTIME_NOT_AVAILABLE');}finally{await rm(root,{recursive:true,force:true});}});
test('credential resolver receives reference and secret not in audit',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'bai-int-'));try{let seen;const s=setup({required_scopes:['x'],invoke:async({credential})=>({data:{credential_seen:credential==='secret-value'}})});const cr=createCredentialReference({credential_ref:'vault://1',provider:'v',scopes:['x']});const g=new IntegrationGateway({root,registry:s.registry,connectors:{mock:s.c},credential_resolver:async(ref)=>{seen=ref.credential_ref;return 'secret-value';},clock});const r=await g.execute(req({credential_ref:cr}));assert.equal(seen,'vault://1');assert.equal(r.data.credential_seen,true);assert.equal(JSON.stringify(await readIntegrationAudit(root)).includes('secret-value'),false);}finally{await rm(root,{recursive:true,force:true});}});
test('transient read error retries',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'bai-int-'));try{let n=0;const s=setup({invoke:async()=>{n++;if(n===1){const e=new Error('timeout');e.code='ETIMEDOUT';throw e;}return{data:{ok:true}};}});const r=await new IntegrationGateway({root,registry:s.registry,connectors:{mock:s.c},clock,max_retries:2}).execute(req());assert.equal(n,2);assert.equal(r.attempt,2);}finally{await rm(root,{recursive:true,force:true});}});
test('permanent error does not retry',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'bai-int-'));try{let n=0;const s=setup({invoke:async()=>{n++;throw new Error('boom');}});await assert.rejects(()=>new IntegrationGateway({root,registry:s.registry,connectors:{mock:s.c},clock,max_retries:2}).execute(req()),e=>e.code==='INTEGRATION_EXECUTION_FAILED');assert.equal(n,1);}finally{await rm(root,{recursive:true,force:true});}});
test('external side effect with idempotency can retry transient failure',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'bai-int-'));try{let n=0;const s=setup({side_effect:'EXTERNAL',invoke:async()=>{n++;if(n===1){const e=new Error('reset');e.code='ECONNRESET';throw e;}return{data:{ok:true}};}});const r=req({idempotency_key:'K',authorization:{authorized:true,task_id:'TASK-008',connector_id:'mock',capability:'op',operation:'run'}});const out=await new IntegrationGateway({root,registry:s.registry,connectors:{mock:s.c},clock,max_retries:2}).execute(r);assert.equal(out.ok,true);assert.equal(n,2);}finally{await rm(root,{recursive:true,force:true});}});
test('idempotent replay does not invoke twice',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'bai-int-'));try{let n=0;const s=setup({side_effect:'EXTERNAL',invoke:async()=>{n++;return{data:{n}};}});const r=req({idempotency_key:'K',authorization:{authorized:true,task_id:'TASK-008',connector_id:'mock',capability:'op',operation:'run'}});const g=new IntegrationGateway({root,registry:s.registry,connectors:{mock:s.c},clock});const a=await g.execute(r);const b=await g.execute(r);assert.equal(n,1);assert.equal(a.data.n,1);assert.equal(b.replayed,true);}finally{await rm(root,{recursive:true,force:true});}});
test('same idempotency key on different operation binding not reused',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'bai-int-'));try{let n=0;const m=createConnectorManifest({connector_id:'mock',kind:'GENERIC',capabilities:[{name:'op',operations:['run','run2'],side_effect:'EXTERNAL'}]});const c=createFunctionConnector(m,async()=>({data:{n:++n}}));const g=new IntegrationGateway({root,registry:buildConnectorRegistry([m]),connectors:{mock:c},clock});await g.execute(req({idempotency_key:'K',authorization:{authorized:true,task_id:'TASK-008',connector_id:'mock',capability:'op',operation:'run'}}));await g.execute(createIntegrationRequest({project_id:'P1',task_id:'TASK-008',connector_id:'mock',capability:'op',operation:'run2',idempotency_key:'K',authorization:{authorized:true,task_id:'TASK-008',connector_id:'mock',capability:'op',operation:'run2'}}));assert.equal(n,2);}finally{await rm(root,{recursive:true,force:true});}});
test('local rate limit blocks excessive calls',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'bai-int-'));try{const s=setup({metadata:{rate_limit_per_window:1,rate_limit_window_ms:60000}});const g=new IntegrationGateway({root,registry:s.registry,connectors:{mock:s.c},clock});await g.execute(req({request_id:'a'}));await assert.rejects(()=>g.execute(req({request_id:'b'})),e=>e.code==='INTEGRATION_RATE_LIMIT_LOCAL');}finally{await rm(root,{recursive:true,force:true});}});
test('monitoring sink receives success event',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'bai-int-'));try{const events=[];const s=setup();await new IntegrationGateway({root,registry:s.registry,connectors:{mock:s.c},clock,monitoring_sink:async e=>events.push(e)}).execute(req());assert.equal(events.some(e=>e.metric==='integration.success'),true);assert.equal(events[0].component,'INTEGRATION');}finally{await rm(root,{recursive:true,force:true});}});
test('blocked policy emits high monitoring event',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'bai-int-'));try{const events=[];const s=setup({side_effect:'EXTERNAL'});const g=new IntegrationGateway({root,registry:s.registry,connectors:{mock:s.c},clock,monitoring_sink:async e=>events.push(e)});await assert.rejects(()=>g.execute(req()),e=>e.code==='INTEGRATION_AUTHORIZATION_REQUIRED');assert.equal(events.at(-1).metric,'integration.blocked');assert.equal(events.at(-1).severity_hint,'HIGH');}finally{await rm(root,{recursive:true,force:true});}});
test('execution failure emits high monitoring event',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'bai-int-'));try{const events=[];const s=setup({invoke:async()=>{throw new Error('x')}});const g=new IntegrationGateway({root,registry:s.registry,connectors:{mock:s.c},clock,monitoring_sink:async e=>events.push(e)});await assert.rejects(()=>g.execute(req()),e=>e.code==='INTEGRATION_EXECUTION_FAILED');assert.equal(events.at(-1).metric,'integration.failure');}finally{await rm(root,{recursive:true,force:true});}});
test('audit records accepted started success',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'bai-int-'));try{const s=setup();await new IntegrationGateway({root,registry:s.registry,connectors:{mock:s.c},clock}).execute(req());const types=(await readIntegrationAudit(root)).map(x=>x.event_type);assert.deepEqual(types,['REQUEST_ACCEPTED','EXECUTION_STARTED','EXECUTION_SUCCEEDED']);}finally{await rm(root,{recursive:true,force:true});}});

test('authorization must bind all external operation fields',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'bai-int-'));try{const s=setup({side_effect:'EXTERNAL'});const r=req({idempotency_key:'K',authorization:{authorized:true,task_id:'TASK-008'}});await assert.rejects(()=>new IntegrationGateway({root,registry:s.registry,connectors:{mock:s.c},clock}).execute(r),e=>e.code==='INTEGRATION_AUTHORIZATION_BINDING_MISMATCH');}finally{await rm(root,{recursive:true,force:true});}});
test('idempotency key collision with changed payload blocks',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'bai-int-'));try{let n=0;const s=setup({side_effect:'EXTERNAL',invoke:async()=>({data:{n:++n}})});const auth={authorized:true,task_id:'TASK-008',connector_id:'mock',capability:'op',operation:'run'};const g=new IntegrationGateway({root,registry:s.registry,connectors:{mock:s.c},clock});await g.execute(req({idempotency_key:'K',authorization:auth,payload:{x:1}}));await assert.rejects(()=>g.execute(req({request_id:'IR-2',idempotency_key:'K',authorization:auth,payload:{x:2}})),e=>e.code==='INTEGRATION_IDEMPOTENCY_CONFLICT');assert.equal(n,1);}finally{await rm(root,{recursive:true,force:true});}});
test('same idempotency key and semantic request with new request id replays',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'bai-int-'));try{let n=0;const s=setup({side_effect:'EXTERNAL',invoke:async()=>({data:{n:++n}})});const auth={authorized:true,task_id:'TASK-008',connector_id:'mock',capability:'op',operation:'run'};const g=new IntegrationGateway({root,registry:s.registry,connectors:{mock:s.c},clock});await g.execute(req({request_id:'IR-1',idempotency_key:'K',authorization:auth}));const b=await g.execute(req({request_id:'IR-2',idempotency_key:'K',authorization:auth}));assert.equal(n,1);assert.equal(b.replayed,true);}finally{await rm(root,{recursive:true,force:true});}});
test('connector echoing resolved credential is blocked',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'bai-int-'));try{const s=setup({required_scopes:['x'],invoke:async({credential})=>({data:{value:credential}})});const cr=createCredentialReference({credential_ref:'vault://1',provider:'v',scopes:['x']});const g=new IntegrationGateway({root,registry:s.registry,connectors:{mock:s.c},credential_resolver:async()=> 'super-secret-value',clock});await assert.rejects(()=>g.execute(req({credential_ref:cr})),e=>e.code==='INTEGRATION_EXECUTION_FAILED'&&e.details?.cause_code==='INTEGRATION_CREDENTIAL_LEAK_DETECTED');}finally{await rm(root,{recursive:true,force:true});}});
test('capability timeout turns into bounded integration failure',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'bai-int-'));try{const m=createConnectorManifest({connector_id:'mock',kind:'GENERIC',capabilities:[{name:'op',operations:['run'],side_effect:'NONE',max_timeout_ms:5}]});const c=createFunctionConnector(m,async()=>new Promise(r=>setTimeout(()=>r({data:{ok:true}}),30)));const g=new IntegrationGateway({root,registry:buildConnectorRegistry([m]),connectors:{mock:c},clock,max_retries:0});await assert.rejects(()=>g.execute(req()),e=>e.code==='INTEGRATION_EXECUTION_FAILED'&&e.details?.class==='TRANSIENT');}finally{await rm(root,{recursive:true,force:true});}});
test('cost guard reserves and records connector actual cost',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'bai-int-'));try{const s=setup({invoke:async()=>({data:{ok:true},metadata:{actual_cost_microusd:80}})});const budgets={task:{max_cost_microusd:1000},role:{max_cost_microusd:1000},session:{max_cost_microusd:1000},soft_limit_ratio:0.8};const g=new IntegrationGateway({root,registry:s.registry,connectors:{mock:s.c},clock,cost_budgets:budgets});const r=await g.execute(req({role:'Builder',session_id:'S1',estimated_cost_microusd:100}));assert.equal(r.ok,true);const {readCostLedger}=await import('../../src/cost-guard/index.mjs');const rows=await readCostLedger(root);assert.equal(rows.some(x=>x.event_type==='RESERVATION_CREATED'),true);assert.equal(rows.some(x=>x.event_type==='ACTUAL_RECORDED'&&x.cost_microusd===80),true);}finally{await rm(root,{recursive:true,force:true});}});
test('cost guard releases reservation when integration fails',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'bai-int-'));try{const s=setup({invoke:async()=>{throw new Error('boom')}});const budgets={task:{max_cost_microusd:1000},role:{max_cost_microusd:1000},session:{max_cost_microusd:1000},soft_limit_ratio:0.8};const g=new IntegrationGateway({root,registry:s.registry,connectors:{mock:s.c},clock,cost_budgets:budgets,max_retries:0});await assert.rejects(()=>g.execute(req({role:'Builder',session_id:'S1',estimated_cost_microusd:100})),e=>e.code==='INTEGRATION_EXECUTION_FAILED');const {readCostLedger}=await import('../../src/cost-guard/index.mjs');const rows=await readCostLedger(root);assert.equal(rows.some(x=>x.event_type==='RESERVATION_RELEASED'),true);}finally{await rm(root,{recursive:true,force:true});}});
test('timeout aborts connector context signal',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'bai-int-'));try{let aborted=false;const m=createConnectorManifest({connector_id:'mock',kind:'GENERIC',capabilities:[{name:'op',operations:['run'],side_effect:'NONE',max_timeout_ms:5}]});const c=createFunctionConnector(m,async({context})=>new Promise((resolve,reject)=>{context.signal.addEventListener('abort',()=>{aborted=true;const e=new Error('aborted');e.code='ETIMEDOUT';reject(e);});}));const g=new IntegrationGateway({root,registry:buildConnectorRegistry([m]),connectors:{mock:c},clock,max_retries:0});await assert.rejects(()=>g.execute(req()),e=>e.code==='INTEGRATION_EXECUTION_FAILED');assert.equal(aborted,true);}finally{await rm(root,{recursive:true,force:true});}});
