import test from 'node:test';import assert from 'node:assert/strict';
import { buildConnectorRegistry, createConnectorManifest, createGitHubManifest, createCommunicationManifest, createExternalAIManifest, createStorageManifest, createMcpManifest, resolveCapability, verifyConnectorManifest } from '../../src/integration/index.mjs';
const cap={name:'read',operations:['get'],side_effect:'NONE'};
test('manifest is immutable and checksummed',()=>{const m=createConnectorManifest({connector_id:'c',kind:'GENERIC',capabilities:[cap]});assert.equal(verifyConnectorManifest(m),true);assert.equal(Object.isFrozen(m),true);});
test('manifest rejects unknown kind',()=>assert.throws(()=>createConnectorManifest({connector_id:'c',kind:'MAGIC',capabilities:[cap]}),e=>e.code==='CONNECTOR_KIND_INVALID'));
test('manifest rejects no capabilities',()=>assert.throws(()=>createConnectorManifest({connector_id:'c',kind:'GENERIC'}),e=>e.code==='CONNECTOR_CAPABILITY_INVALID'));
test('manifest rejects duplicate capabilities',()=>assert.throws(()=>createConnectorManifest({connector_id:'c',kind:'GENERIC',capabilities:[cap,cap]}),e=>e.code==='CONNECTOR_CAPABILITY_INVALID'));
test('manifest rejects invalid side effect',()=>assert.throws(()=>createConnectorManifest({connector_id:'c',kind:'GENERIC',capabilities:[{...cap,side_effect:'MAGIC'}]}),e=>e.code==='CONNECTOR_SIDE_EFFECT_INVALID'));
test('manifest tamper is detected',()=>{const m=structuredClone(createConnectorManifest({connector_id:'c',kind:'GENERIC',capabilities:[cap]}));m.kind='MCP';assert.throws(()=>verifyConnectorManifest(m),e=>e.code==='CONNECTOR_MANIFEST_TAMPERED');});
test('registry sorts connectors',()=>{const a=createConnectorManifest({connector_id:'z',kind:'GENERIC',capabilities:[cap]});const b=createConnectorManifest({connector_id:'a',kind:'GENERIC',capabilities:[cap]});assert.deepEqual(Object.keys(buildConnectorRegistry([a,b]).connectors),['a','z']);});
test('registry rejects duplicate ids',()=>{const a=createConnectorManifest({connector_id:'a',kind:'GENERIC',capabilities:[cap]});assert.throws(()=>buildConnectorRegistry([a,a]),e=>e.code==='CONNECTOR_DUPLICATE');});
test('resolve capability and operation',()=>{const m=createConnectorManifest({connector_id:'a',kind:'GENERIC',capabilities:[cap]});const x=resolveCapability(buildConnectorRegistry([m]),'a','read','get');assert.equal(x.capability.name,'read');});
test('unknown connector blocks',()=>assert.throws(()=>resolveCapability(buildConnectorRegistry([]),'x','read','get'),e=>e.code==='CONNECTOR_NOT_FOUND'));
test('disabled connector blocks',()=>{const m=createConnectorManifest({connector_id:'a',kind:'GENERIC',status:'DISABLED',capabilities:[cap]});assert.throws(()=>resolveCapability(buildConnectorRegistry([m]),'a','read','get'),e=>e.code==='CONNECTOR_NOT_ENABLED');});
test('unknown operation blocks',()=>{const m=createConnectorManifest({connector_id:'a',kind:'GENERIC',capabilities:[cap]});assert.throws(()=>resolveCapability(buildConnectorRegistry([m]),'a','read','write'),e=>e.code==='CONNECTOR_OPERATION_NOT_ALLOWED');});
test('GitHub profile has read and write capability',()=>{const m=createGitHubManifest();assert.equal(m.kind,'GITHUB');assert.equal(m.capabilities.length,2);});
test('communication profile defines send',()=>assert.equal(createCommunicationManifest().capabilities[0].operations.includes('send'),true));
test('external AI is cost and license sensitive',()=>{const c=createExternalAIManifest().capabilities[0];assert.equal(c.cost_metered,true);assert.equal(c.license_sensitive,true);});
test('storage profile separates read/write',()=>assert.equal(createStorageManifest().capabilities.length,2));
test('mcp defaults external side effect',()=>assert.equal(createMcpManifest().capabilities[0].side_effect,'EXTERNAL'));
test('NONE side effect defaults retry safe',()=>{const m=createConnectorManifest({connector_id:'a',kind:'GENERIC',capabilities:[cap]});assert.equal(m.capabilities[0].retry_safe,true);});
test('EXTERNAL defaults auth/idempotency',()=>{const m=createConnectorManifest({connector_id:'a',kind:'GENERIC',capabilities:[{name:'send',operations:['send'],side_effect:'EXTERNAL'}]});assert.equal(m.capabilities[0].requires_authorization,true);assert.equal(m.capabilities[0].idempotency_required,true);});
