import test from 'node:test';import assert from 'node:assert/strict';
import { ExtensionRegistry,CapabilityBroker } from '../../src/extension/index.mjs';import { baseManifest,providerFor } from './helpers.mjs';
function setup({manifest=baseManifest({execution_mode:'IN_PROCESS_TRUSTED'}),provider=providerFor(),broker={}}={}){const r=new ExtensionRegistry({os_version:'0.8.0',trust_policy:{in_process_grants:{[manifest.extension_id]:[manifest.content_checksum]}}});r.install(manifest,{provider});r.validate(manifest.extension_id);r.enable(manifest.extension_id);return new CapabilityBroker({registry:r,...broker});}
test('trusted in-process invocation succeeds',async()=>{const b=setup();const r=await b.invoke({extension_id:'ext.test',capability_id:'domain.artifact_validator',operation:'validate',payload:{x:1}});assert.equal(r.status,'SUCCESS');assert.equal(r.result.payload.x,1);});
test('not enabled extension is denied',async()=>{const r=new ExtensionRegistry({os_version:'0.8.0'});const m=baseManifest({execution_mode:'IN_PROCESS_TRUSTED'});r.install(m,{provider:providerFor()});r.validate('ext.test');const b=new CapabilityBroker({registry:r});await assert.rejects(()=>b.invoke({extension_id:'ext.test',capability_id:'domain.artifact_validator',operation:'validate'}),e=>e.code==='EXTENSION_NOT_ENABLED');});
test('unknown capability denied',async()=>{const b=setup();await assert.rejects(()=>b.invoke({extension_id:'ext.test',capability_id:'x',operation:'validate'}),e=>e.code==='EXTENSION_CAPABILITY_NOT_FOUND');});
test('unknown operation denied',async()=>{const b=setup();await assert.rejects(()=>b.invoke({extension_id:'ext.test',capability_id:'domain.artifact_validator',operation:'write'}),e=>e.code==='EXTENSION_OPERATION_DENIED');});
test('payload budget enforced',async()=>{const m=baseManifest({execution_mode:'IN_PROCESS_TRUSTED',capabilities:[{capability_id:'x',operations:['go'],max_payload_bytes:10}]});const b=setup({manifest:m,provider:providerFor('x','go')});await assert.rejects(()=>b.invoke({extension_id:'ext.test',capability_id:'x',operation:'go',payload:'123456789012'}),e=>e.code==='EXTENSION_PAYLOAD_TOO_LARGE');});
test('authorization required for external action',async()=>{const m=baseManifest({execution_mode:'IN_PROCESS_TRUSTED',capabilities:[{capability_id:'x',operations:['go'],side_effect:'IRREVERSIBLE_LOCAL',sandbox_required:false}]});const b=setup({manifest:m,provider:providerFor('x','go')});await assert.rejects(()=>b.invoke({extension_id:'ext.test',capability_id:'x',operation:'go'}),e=>e.code==='EXTENSION_AUTHORIZATION_REQUIRED');});
test('authorization verifier can reject reference',async()=>{const m=baseManifest({execution_mode:'IN_PROCESS_TRUSTED',capabilities:[{capability_id:'x',operations:['go'],side_effect:'IRREVERSIBLE_LOCAL',sandbox_required:false}]});const b=setup({manifest:m,provider:providerFor('x','go'),broker:{authorization_verifier:async()=>false}});await assert.rejects(()=>b.invoke({extension_id:'ext.test',capability_id:'x',operation:'go',authorization_ref:'auth:1'}),e=>e.code==='EXTENSION_AUTHORIZATION_INVALID');});
test('authorization verifier can approve reference',async()=>{const m=baseManifest({execution_mode:'IN_PROCESS_TRUSTED',capabilities:[{capability_id:'x',operations:['go'],side_effect:'IRREVERSIBLE_LOCAL',sandbox_required:false}]});const b=setup({manifest:m,provider:providerFor('x','go'),broker:{authorization_verifier:async()=>true}});assert.equal((await b.invoke({extension_id:'ext.test',capability_id:'x',operation:'go',authorization_ref:'auth:1'})).status,'SUCCESS');});
test('permission resolver can block',async()=>{const m=baseManifest({execution_mode:'IN_PROCESS_TRUSTED',permissions:['FILESYSTEM_WRITE'],capabilities:[{capability_id:'x',operations:['go'],permissions:['FILESYSTEM_WRITE']}]});const b=setup({manifest:m,provider:providerFor('x','go'),broker:{permission_resolver:async()=>false}});await assert.rejects(()=>b.invoke({extension_id:'ext.test',capability_id:'x',operation:'go'}),e=>e.code==='EXTENSION_PERMISSION_DENIED');});
test('missing handler is rejected at provider contract boundary',()=>{const m=baseManifest({execution_mode:'IN_PROCESS_TRUSTED'});const r=new ExtensionRegistry({os_version:'0.8.0'});assert.throws(()=>r.install(m,{provider:{implementation_checksum:m.execution_contract.implementation_checksum,capabilities:{}}}),e=>e.code==='EXTENSION_PROVIDER_CONTRACT_INCOMPLETE');});
test('declarative extension cannot execute',async()=>{const r=new ExtensionRegistry({os_version:'0.8.0'});const m=baseManifest();r.install(m);r.validate('ext.test');r.enable('ext.test');const b=new CapabilityBroker({registry:r});await assert.rejects(()=>b.invoke({extension_id:'ext.test',capability_id:'domain.artifact_validator',operation:'validate'}),e=>e.code==='EXTENSION_DECLARATIVE_NOT_EXECUTABLE');});
test('sandboxed extension requires sandbox runner at invocation',async()=>{const m=baseManifest({execution_mode:'SANDBOXED'});const b=setup({manifest:m});await assert.rejects(()=>b.invoke({extension_id:'ext.test',capability_id:'domain.artifact_validator',operation:'validate'}),e=>e.code==='EXTENSION_SANDBOX_RUNNER_REQUIRED');});
test('sandbox runner mediates provider execution',async()=>{const m=baseManifest({execution_mode:'SANDBOXED'});let seen=false;const b=setup({manifest:m,broker:{sandbox_runner:async({request})=>{seen=true;return {sandbox:true,payload:request.payload};}}});const r=await b.invoke({extension_id:'ext.test',capability_id:'domain.artifact_validator',operation:'validate',payload:{a:1}});assert.equal(seen,true);assert.equal(r.result.sandbox,true);});
test('runtime timeout is enforced',async()=>{const m=baseManifest({execution_mode:'IN_PROCESS_TRUSTED',capabilities:[{capability_id:'x',operations:['go'],max_runtime_ms:10}]});const p=providerFor('x','go',async()=>new Promise(res=>setTimeout(()=>res(true),50)));const b=setup({manifest:m,provider:p});await assert.rejects(()=>b.invoke({extension_id:'ext.test',capability_id:'x',operation:'go'}),e=>e.code==='EXTENSION_RUNTIME_TIMEOUT');});
test('already aborted signal is rejected',async()=>{const b=setup();const c=new AbortController();c.abort();await assert.rejects(()=>b.invoke({extension_id:'ext.test',capability_id:'domain.artifact_validator',operation:'validate',signal:c.signal}),e=>e.code==='EXTENSION_ABORTED');});
test('result is deeply frozen',async()=>{const r=await setup().invoke({extension_id:'ext.test',capability_id:'domain.artifact_validator',operation:'validate'});assert(Object.isFrozen(r));assert(Object.isFrozen(r.result));});
test('request context is cloned',async()=>{let seen;const p=providerFor('domain.artifact_validator','validate',async req=>{seen=req;return {};});const b=setup({provider:p});const ctx={a:{b:1}};await b.invoke({extension_id:'ext.test',capability_id:'domain.artifact_validator',operation:'validate',context:ctx});ctx.a.b=2;assert.equal(seen.context.a.b,1);});

test('sandbox-required capability cannot run in-process even when trusted',async()=>{const m=baseManifest({execution_mode:'IN_PROCESS_TRUSTED',capabilities:[{capability_id:'x',operations:['go'],sandbox_required:true}]});const b=setup({manifest:m,provider:providerFor('x','go')});await assert.rejects(()=>b.invoke({extension_id:'ext.test',capability_id:'x',operation:'go'}),e=>e.code==='EXTENSION_SANDBOX_REQUIRED');});
test('external capability runs only through sandbox and authorization',async()=>{const m=baseManifest({execution_mode:'SANDBOXED',capabilities:[{capability_id:'x',operations:['go'],side_effect:'EXTERNAL'}]});const b=setup({manifest:m,provider:providerFor('x','go'),broker:{authorization_verifier:async()=>true,sandbox_runner:async()=>({ok:true})}});assert.equal((await b.invoke({extension_id:'ext.test',capability_id:'x',operation:'go',authorization_ref:'auth:1'})).status,'SUCCESS');});
test('timeout aborts provider signal',async()=>{let aborted=false;const m=baseManifest({execution_mode:'IN_PROCESS_TRUSTED',capabilities:[{capability_id:'x',operations:['go'],max_runtime_ms:10}]});const p=providerFor('x','go',async(_req,{signal})=>new Promise(resolve=>{signal.addEventListener('abort',()=>{aborted=true;resolve('late');},{once:true});}));const b=setup({manifest:m,provider:p});await assert.rejects(()=>b.invoke({extension_id:'ext.test',capability_id:'x',operation:'go'}),e=>e.code==='EXTENSION_RUNTIME_TIMEOUT');assert.equal(aborted,true);});
test('mid-execution caller abort rejects invocation and forwards abort',async()=>{let aborted=false;const p=providerFor('domain.artifact_validator','validate',async(_req,{signal})=>new Promise(resolve=>{signal.addEventListener('abort',()=>{aborted=true;resolve('late');},{once:true});}));const b=setup({provider:p});const c=new AbortController();const promise=b.invoke({extension_id:'ext.test',capability_id:'domain.artifact_validator',operation:'validate',signal:c.signal});setTimeout(()=>c.abort(),5);await assert.rejects(()=>promise,e=>e.code==='EXTENSION_ABORTED');assert.equal(aborted,true);});
