import test from 'node:test';import assert from 'node:assert/strict';
import { ExtensionService,createExtensionHook,createDomainPack } from '../../src/extension/index.mjs';import { baseManifest,providerFor,TEST_IMPLEMENTATION_CHECKSUM } from './helpers.mjs';
const trusted=(m)=>new ExtensionService({os_version:'0.8.0',trust_policy:{in_process_grants:{[m.extension_id]:[m.content_checksum]}}});
test('service manages declarative lifecycle',()=>{const s=new ExtensionService({os_version:'0.8.0'});s.install(baseManifest());s.validate('ext.test');assert.equal(s.enable('ext.test').state,'ENABLED');});
test('service invokes explicitly trusted plugin',async()=>{const m=baseManifest({execution_mode:'IN_PROCESS_TRUSTED'});const s=trusted(m);s.install(m,{provider:providerFor()});s.validate('ext.test');s.enable('ext.test');assert.equal((await s.invoke({extension_id:'ext.test',capability_id:'domain.artifact_validator',operation:'validate'})).status,'SUCCESS');});
test('service policy pack preserves floors and binds to installed extension',()=>{const s=new ExtensionService({os_version:'0.8.0'});s.install(baseManifest());const p=createDomainPack({pack_id:'p',extension_id:'ext.test',domain:'WEB',pack_type:'PROJECT_POLICY',mandatory_floors:['AUTHORITY']});assert.equal(s.addPacks([p],{required_floors:['AUTHORITY']}).packs.length,1);});
test('service rejects weak policy pack',()=>{const s=new ExtensionService({os_version:'0.8.0'});s.install(baseManifest());const p=createDomainPack({pack_id:'p',extension_id:'ext.test',domain:'WEB',pack_type:'PROJECT_POLICY'});assert.throws(()=>s.addPacks([p],{required_floors:['AUTHORITY']}),e=>e.code==='EXTENSION_POLICY_FLOOR_WEAKENING');});
test('service rejects orphan pack',()=>{const s=new ExtensionService({os_version:'0.8.0'});const p=createDomainPack({pack_id:'p',extension_id:'ext.test',domain:'WEB',pack_type:'TEST'});assert.throws(()=>s.addPacks([p]),e=>e.code==='EXTENSION_NOT_FOUND');});
test('service rejects pack for undeclared domain',()=>{const s=new ExtensionService({os_version:'0.8.0'});s.install(baseManifest());const p=createDomainPack({pack_id:'p',extension_id:'ext.test',domain:'VIDEO',pack_type:'TEST'});assert.throws(()=>s.addPacks([p]),e=>e.code==='EXTENSION_PACK_DOMAIN_MISMATCH');});
test('service rejects undeclared pack id when manifest declares pack list',()=>{const s=new ExtensionService({os_version:'0.8.0'});s.install(baseManifest({packs:['allowed']}));const p=createDomainPack({pack_id:'other',extension_id:'ext.test',domain:'WEB',pack_type:'TEST'});assert.throws(()=>s.addPacks([p]),e=>e.code==='EXTENSION_PACK_UNDECLARED');});
test('service artifact extension executes through capability broker',async()=>{const m=baseManifest({execution_mode:'IN_PROCESS_TRUSTED',capabilities:[{capability_id:'domain.artifact_validator',operations:['validate']},{capability_id:'domain.artifact_previewer',operations:['preview']},{capability_id:'domain.quality_gate',operations:['evaluate']}]});const s=trusted(m);const p={implementation_checksum:TEST_IMPLEMENTATION_CHECKSUM,capabilities:{'domain.artifact_validator':{validate:async()=>({status:'PASS'})},'domain.artifact_previewer':{preview:async()=>({url:'preview'})},'domain.quality_gate':{evaluate:async()=>({status:'PASS'})}}};s.install(m,{provider:p});s.validate('ext.test');s.enable('ext.test');s.registerArtifactExtension('WEB',{extension_id:'ext.test'});const r=await s.evaluateArtifact('WEB',{frame:1});assert.equal(r.status,'PASS');assert.equal(r.previews[0].status,'DERIVED_NON_CANONICAL');});
test('artifact binding requires enabled extension',()=>{const m=baseManifest({execution_mode:'IN_PROCESS_TRUSTED'});const s=trusted(m);s.install(m,{provider:providerFor()});assert.throws(()=>s.registerArtifactExtension('WEB',{extension_id:'ext.test'}),e=>e.code==='EXTENSION_NOT_ENABLED');});
test('artifact binding rejects wrong domain',()=>{const m=baseManifest({execution_mode:'IN_PROCESS_TRUSTED'});const s=trusted(m);s.install(m,{provider:providerFor()});s.validate('ext.test');s.enable('ext.test');assert.throws(()=>s.registerArtifactExtension('VIDEO',{extension_id:'ext.test'}),e=>e.code==='EXTENSION_ARTIFACT_DOMAIN_MISMATCH');});
test('service hooks execute through broker',async()=>{const m=baseManifest({execution_mode:'IN_PROCESS_TRUSTED',hook_types:['KNOWLEDGE'],capabilities:[{capability_id:'knowledge.hook',operations:['execute']}]});const s=trusted(m);s.install(m,{provider:providerFor('knowledge.hook','execute',async({payload})=>({...payload,enriched:true}))});s.validate('ext.test');s.enable('ext.test');s.addHook(createExtensionHook({hook_id:'h',extension_id:'ext.test',hook_type:'KNOWLEDGE'}));assert.equal((await s.runHooks('KNOWLEDGE',{x:1})).value.enriched,true);});
test('service rejects hook type not declared by manifest',()=>{const s=new ExtensionService({os_version:'0.8.0'});s.install(baseManifest());assert.throws(()=>s.addHook(createExtensionHook({hook_id:'h',extension_id:'ext.test',hook_type:'KNOWLEDGE'})),e=>e.code==='EXTENSION_HOOK_UNDECLARED');});
test('service rejects hook capability not declared by manifest',()=>{const s=new ExtensionService({os_version:'0.8.0'});s.install(baseManifest({hook_types:['KNOWLEDGE']}));assert.throws(()=>s.addHook(createExtensionHook({hook_id:'h',extension_id:'ext.test',hook_type:'KNOWLEDGE'})),e=>e.code==='EXTENSION_HOOK_CAPABILITY_UNDECLARED');});

test('failed pack batch does not partially mutate service pack set',()=>{const s=new ExtensionService({os_version:'0.8.0'});s.install(baseManifest());const good=createDomainPack({pack_id:'p',extension_id:'ext.test',domain:'WEB',pack_type:'TEST'});s.addPacks([good]);assert.throws(()=>s.addPacks([good]),e=>e.code==='EXTENSION_PACK_DUPLICATE');assert.equal(s.packs.length,1);});
test('duplicate hook id is rejected',()=>{const m=baseManifest({hook_types:['KNOWLEDGE'],capabilities:[{capability_id:'knowledge.hook',operations:['execute']}]});const s=new ExtensionService({os_version:'0.8.0'});s.install(m);const h=createExtensionHook({hook_id:'h',extension_id:'ext.test',hook_type:'KNOWLEDGE'});s.addHook(h);assert.throws(()=>s.addHook(h),e=>e.code==='EXTENSION_HOOK_DUPLICATE');});
