import test from 'node:test'; import assert from 'node:assert/strict'; import { optimizeContext, selectModelWithPolicy, compressPrompt, optimizeDynamicBudget } from '../../src/automation/index.mjs';
const source=(id,tokens,extra={})=>({source_id:id,canonical_identity:id,trust_level:'TRUSTED',priority:1,token_estimate:tokens,content_checksum:'sha256:'+'a'.repeat(64),...extra});

test('context optimization fits priority sources to token budget',()=>{const r=optimizeContext({sources:[source('a',50),source('b',60,{priority:0})],token_budget:70});assert.deepEqual(r.selected.map(x=>x.source_id),['a']);});
test('required canonical context cannot be silently dropped',()=>assert.throws(()=>optimizeContext({sources:[source('a',100,{trust_level:'CANONICAL',required:true})],token_budget:50}),e=>e.code==='ADVANCED_CONTEXT_BUDGET_BLOCKED'));
test('model policy blocks unauthorized escalation',()=>assert.throws(()=>selectModelWithPolicy({request:{capabilities:['x']},profiles:[{model_id:'m',capabilities:['y'],context_capacity:1,tools:[],max_sensitivity:'INTERNAL',reliability:1,estimated_cost_microusd:1}],policy:{allow_escalation:false}}),e=>e.code==='ADVANCED_MODEL_ESCALATION_BLOCKED'));
test('model selection can return eligible route',()=>{const r=selectModelWithPolicy({request:{capabilities:['x'],context_tokens:1,required_tools:[],sensitivity:'INTERNAL'},profiles:[{model_id:'m',capabilities:['x'],context_capacity:10,tools:[],max_sensitivity:'INTERNAL',reliability:1,estimated_cost_microusd:1}]});assert.equal(r.model.model_id,'m');});
test('prompt compression keeps mandatory and best optional',()=>{const r=compressPrompt({sections:[{id:'m',text:'must',required:true},{id:'a',text:'aaaa',priority:2},{id:'b',text:'bbbbbbbb',priority:1}],max_chars:12});assert.ok(r.included.includes('m'));assert.ok(r.included.includes('a'));});
test('mandatory prompt over limit fails closed',()=>assert.throws(()=>compressPrompt({sections:[{id:'m',text:'x'.repeat(200),required:true}],max_chars:100}),e=>e.code==='MANDATORY_PROMPT_EXCEEDS_LIMIT'));
test('dynamic budget reserves safety margin',()=>{const r=optimizeDynamicBudget({profile_id:'DEV_2_STANDARD',remaining_microusd:1000,estimated_next_microusd:850,reserve_ratio:.1});assert.equal(r.result,'DYNAMIC_BUDGET_READY');assert.equal(r.reserve_microusd,100);});
test('dynamic budget blocks spend beyond spendable',()=>assert.equal(optimizeDynamicBudget({profile_id:'DEV_2_STANDARD',remaining_microusd:1000,estimated_next_microusd:901,reserve_ratio:.1}).result,'DYNAMIC_BUDGET_BLOCKED'));
