import test from 'node:test'; import assert from 'node:assert/strict'; import { readFile, writeFile, mkdir, symlink } from 'node:fs/promises'; import path from 'node:path'; import { createHash } from 'node:crypto';
import { resolveCanonicalDocument, verifyCanonicalDocumentSet, checkCrossFormatConsistency, createDocumentationSyncProposal, applyAuthorizedDocumentationSync } from '../../src/automation/index.mjs'; import { miniWorkspace } from './helpers.mjs';
const h=b=>`sha256:${createHash('sha256').update(b).digest('hex')}`;
async function manifest(root){await mkdir(path.join(root,'docs'),{recursive:true});const md=Buffer.from('ID X VERSION 1\n');const sum=Buffer.from('ID X VERSION 1\n');await writeFile(path.join(root,'docs/x.md'),md);await writeFile(path.join(root,'docs/x.summary.md'),sum);return {documents:[{document_id:'X',version:'1.0',status:'CURRENT_CANONICAL',markdown_path:'docs/x.md',summary_path:'docs/x.summary.md',sha256:{markdown:h(md),summary:h(sum)}}]};}

test('canonical resolver requires exactly one current document',async()=>{const root=await miniWorkspace();const m=await manifest(root);assert.equal(resolveCanonicalDocument(m,{document_id:'X'}).version,'1.0');});
test('missing canonical document safe-stops',()=>assert.throws(()=>resolveCanonicalDocument({documents:[]},{document_id:'X'}),e=>e.code==='DOCUMENT_CANONICAL_NOT_FOUND'));
test('ambiguous canonical document safe-stops',()=>assert.throws(()=>resolveCanonicalDocument({documents:[{document_id:'X',version:'1',status:'CURRENT_CANONICAL',markdown_path:'a',summary_path:'b',sha256:{markdown:'x'}},{document_id:'X',version:'2',status:'CURRENT_CANONICAL',markdown_path:'c',summary_path:'d',sha256:{markdown:'x'}}]},{document_id:'X'}),e=>e.code==='DOCUMENT_CANONICAL_AMBIGUOUS'));
test('document set verifies hashes',async()=>{const root=await miniWorkspace();const m=await manifest(root);assert.equal((await verifyCanonicalDocumentSet(root,resolveCanonicalDocument(m,{document_id:'X'}))).result,'CANONICAL_DOCUMENT_SET_VERIFIED');});
test('document set detects content drift',async()=>{const root=await miniWorkspace();const m=await manifest(root);const d=resolveCanonicalDocument(m,{document_id:'X'});await writeFile(path.join(root,'docs/x.md'),'changed');await assert.rejects(()=>verifyCanonicalDocumentSet(root,d),e=>e.code==='DOCUMENT_HASH_MISMATCH');});
test('cross-format marker check passes aligned copies',()=>assert.equal(checkCrossFormatConsistency({markdown_text:'A V1',summary_text:'A V1',required_markers:['A','V1']}).result,'CROSS_FORMAT_CONSISTENCY_PASS'));
test('cross-format marker check returns unknown on mismatch',()=>assert.equal(checkCrossFormatConsistency({markdown_text:'A',summary_text:'B',required_markers:['A']}).result,'DOCUMENT_CONSISTENCY_UNKNOWN'));
test('documentation sync proposal is derived-only and approval required',()=>{const p=createDocumentationSyncProposal({updates:[{path:'registry/x.md',content:'x'}],source_evidence:['e'],requested_by:'O'});assert.equal(p.derived_views_only,true);assert.equal(p.owner_approval_required,true);});
test('documentation sync rejects canonical write',async()=>{const root=await miniWorkspace();const p=createDocumentationSyncProposal({updates:[{path:'architecture/x.md',content:'x',authority:'MACHINE_CANONICAL'}],source_evidence:['e'],requested_by:'O'});await assert.rejects(()=>applyAuthorizedDocumentationSync(root,p,{authorized:true}),e=>e.code==='DOCUMENT_SYNC_CANONICAL_WRITE_FORBIDDEN');});
test('authorized derived sync writes and verifies derived view',async()=>{const root=await miniWorkspace();const p=createDocumentationSyncProposal({updates:[{path:'registry/generated.md',content:'generated',authority:'INDEX_OR_DERIVED_VIEW',kind:'REGISTRY'}],source_evidence:['e'],requested_by:'O'});const r=await applyAuthorizedDocumentationSync(root,p,{authorized:true});assert.equal(r.result,'DOCUMENT_SYNC_APPLIED_AND_VERIFIED');assert.equal(await readFile(path.join(root,'registry/generated.md'),'utf8'),'generated');});
test('symlinked target escapes are rejected',async()=>{const root=await miniWorkspace();await symlink('/tmp',path.join(root,'registry/link'));const p=createDocumentationSyncProposal({updates:[{path:'registry/link/x.md',content:'x',authority:'INDEX_OR_DERIVED_VIEW'}],source_evidence:['e'],requested_by:'O'});await assert.rejects(()=>applyAuthorizedDocumentationSync(root,p,{authorized:true}),e=>e.code==='PATH_ESCAPE'||e.code==='DOCUMENT_PATH_ESCAPE');});
test('canonical document manifest rejects multiple current versions',async()=>{const {buildCanonicalDocumentManifest}=await import('../../src/automation/index.mjs');assert.throws(()=>buildCanonicalDocumentManifest([{document_id:'X',version:'1',status:'CURRENT_CANONICAL',markdown_path:'a',summary_path:'b'},{document_id:'X',version:'2',status:'CURRENT_CANONICAL',markdown_path:'c',summary_path:'d'}]),e=>e.code==='DOCUMENT_MANIFEST_MULTIPLE_CURRENT');});
test('canonical document manifest is index metadata not content authority',async()=>{const {buildCanonicalDocumentManifest}=await import('../../src/automation/index.mjs');const m=buildCanonicalDocumentManifest([{document_id:'X',version:'1',status:'CURRENT_CANONICAL',markdown_path:'a',summary_path:'b'}]);assert.equal(m.content_authority,false);assert.match(m.content_checksum,/^sha256:/);});
