import test from 'node:test'; import assert from 'node:assert/strict'; import { buildRoleStartupPackage, compileOrchestratorInstruction, createAutomationPlan, classifyAutomationAction, executeConditionalAutomation, evaluateAutomationResult, proposeLifecycleAction, createOwnerAuthorizationProposal } from '../../src/automation/index.mjs'; import { runtimeReady,projectResolved,riskResolved,noKnowledge,lifecycle,modelProfiles,modelRequest } from './helpers.mjs';
function fixture(){const startup=buildRoleStartupPackage({project_id:'P1',task_id:'TASK-006',role:'Builder',phase:'IMPLEMENTATION',runtime_resolution:runtimeReady,project_resolution:projectResolved,risk_resolution:riskResolved,knowledge_integration:noKnowledge,lifecycle_snapshot:lifecycle,model_profiles:modelProfiles,model_request:modelRequest});const instruction=compileOrchestratorInstruction({startup_package:startup,task_definition:'x',role_specification:'y'});return{startup,instruction};}

test('read actions can automate',()=>assert.equal(classifyAutomationAction({kind:'READ'}).classification,'AUTOMATION_ALLOWED'));
test('write actions require owner approval',()=>assert.equal(classifyAutomationAction({kind:'IMPLEMENT_WRITE'}).classification,'OWNER_APPROVAL_REQUIRED'));
test('unknown actions safe-stop',()=>assert.equal(classifyAutomationAction({kind:'MAGIC'}).classification,'SAFE_STOP_UNKNOWN_ACTION'));
test('automation plan never gains lifecycle mutation authority',()=>{const {startup,instruction}=fixture();const p=createAutomationPlan({startup_package:startup,instruction,actions:[{kind:'READ'}]});assert.equal(p.lifecycle_mutation_authority,false);assert.equal(p.knowledge_content_authority,false);});
test('read-only automation executes without owner approval',async()=>{const {startup,instruction}=fixture();const p=createAutomationPlan({startup_package:startup,instruction,actions:[{action_id:'a',kind:'READ'}]});const r=await executeConditionalAutomation(p,{startup_package:startup,executor:async()=>({ok:true})});assert.equal(r.result,'AUTOMATION_RUN_COMPLETE');});
test('write automation is blocked without proposal',async()=>{const {startup,instruction}=fixture();const p=createAutomationPlan({startup_package:startup,instruction,actions:[{kind:'IMPLEMENT_WRITE'}]});await assert.rejects(()=>executeConditionalAutomation(p,{startup_package:startup,executor:async()=>({})}),e=>e.code==='AUTOMATION_OWNER_PROPOSAL_REQUIRED');});
test('write automation executes with matching owner approval',async()=>{const {startup,instruction}=fixture();const p=createAutomationPlan({startup_package:startup,instruction,actions:[{kind:'IMPLEMENT_WRITE'}]});const proposal=createOwnerAuthorizationProposal({owner_intent:'write',requested_role:'Builder',task_id:'TASK-006',phase:'IMPLEMENTATION',current_state:{},active_gate:{},runtime_preflight:{}});const approval={authorized:true,task_id:'TASK-006',phase:'IMPLEMENTATION',role:'Builder'};const r=await executeConditionalAutomation(p,{startup_package:startup,proposal,approval,executor:async()=>({ok:true})});assert.equal(r.result,'AUTOMATION_RUN_COMPLETE');});
test('automation result retries transient failures within bound',()=>assert.equal(evaluateAutomationResult({result:{ok:false},error:{class:'NETWORK'},attempt:0,retry_limit:1}).decision,'RETRY'));
test('automation result safe-stops deterministic repeat',()=>assert.equal(evaluateAutomationResult({result:{ok:false},error:{class:'SCHEMA'},attempt:0,retry_limit:2}).decision,'SAFE_STOP_OR_ESCALATE'));
test('lifecycle action is proposal only',()=>{const p=proposeLifecycleAction({task_id:'T',current_status:'ACTIVE',target_status:'PAUSED',reason:'r'});assert.equal(p.applied,false);assert.equal(p.requires_lifecycle_authority,true);});
test('already authorized reversible scope-bound implementation can run without a second Owner gate',()=>{const r=classifyAutomationAction({kind:'IMPLEMENT_WRITE',authorization_status:'AUTHORIZED',scope_bound:true,reversible:true,external_side_effect:false});assert.equal(r.classification,'AUTOMATION_ALLOWED_AUTHORIZED_SCOPE');assert.equal(r.owner_approval_required,false);});
test('irreversible implementation still requires Owner approval even when scope is authorized',()=>assert.equal(classifyAutomationAction({kind:'IMPLEMENT_WRITE',authorization_status:'AUTHORIZED',scope_bound:true,reversible:false}).owner_approval_required,true));
