import test from 'node:test'; import assert from 'node:assert/strict'; import { buildRoleStartupPackage, compileOrchestratorInstruction, createOwnerAuthorizationProposal, validateOwnerApproval } from '../../src/automation/index.mjs'; import { runtimeReady,projectResolved,riskResolved,noKnowledge,lifecycle,modelProfiles,modelRequest } from './helpers.mjs';
function startup(){return buildRoleStartupPackage({project_id:'P1',task_id:'TASK-006',role:'Builder',phase:'IMPLEMENTATION',runtime_resolution:runtimeReady,project_resolution:projectResolved,risk_resolution:riskResolved,knowledge_integration:noKnowledge,lifecycle_snapshot:lifecycle,model_profiles:modelProfiles,model_request:modelRequest,allowed_paths:['src/**'],protected_paths:['registry/**'],stop_conditions:['NO_AUTH'],expected_outputs:['code']});}

test('compiler emits deterministic authority and prompt binding',()=>{const i=compileOrchestratorInstruction({startup_package:startup(),task_definition:'build x',role_specification:'builder rules'});assert.match(i.compiled_text,/TASK-006/);assert.match(i.prompt_checksum,/^sha256:/);});
test('compiler requires startup package',()=>assert.throws(()=>compileOrchestratorInstruction({task_definition:'x',role_specification:'y'}),e=>e.code==='INSTRUCTION_STARTUP_REQUIRED'));
test('owner proposal never grants authorization',()=>{const p=createOwnerAuthorizationProposal({owner_intent:'implement',requested_role:'Builder',task_id:'TASK-006',phase:'IMPLEMENTATION',current_state:{status:'ACTIVE'},active_gate:{name:'DESIGN'},runtime_preflight:{result:'PASS'}});assert.equal(p.owner_approval_required,true);assert.equal(p.authorization_granted,false);});
test('approval missing is rejected',()=>{const p=createOwnerAuthorizationProposal({owner_intent:'x',requested_role:'Builder',task_id:'T',phase:'P',current_state:{},active_gate:{},runtime_preflight:{}});assert.throws(()=>validateOwnerApproval(p,null),e=>e.code==='NOT_AUTHORIZED');});
test('approval scope mismatch rejected',()=>{const p=createOwnerAuthorizationProposal({owner_intent:'x',requested_role:'Builder',task_id:'T',phase:'P',current_state:{},active_gate:{},runtime_preflight:{}});assert.throws(()=>validateOwnerApproval(p,{authorized:true,task_id:'X',phase:'P',role:'Builder'}),e=>e.code==='AUTHORIZATION_SCOPE_MISMATCH');});
test('expired approval rejected',()=>{const p=createOwnerAuthorizationProposal({owner_intent:'x',requested_role:'Builder',task_id:'T',phase:'P',current_state:{},active_gate:{},runtime_preflight:{}});assert.throws(()=>validateOwnerApproval(p,{authorized:true,task_id:'T',phase:'P',role:'Builder',expires_at:'2020-01-01T00:00:00Z'}),e=>e.code==='AUTHORIZATION_EXPIRED');});
test('matching approval validates',()=>{const p=createOwnerAuthorizationProposal({owner_intent:'x',requested_role:'Builder',task_id:'T',phase:'P',current_state:{},active_gate:{},runtime_preflight:{}});assert.equal(validateOwnerApproval(p,{authorized:true,task_id:'T',phase:'P',role:'Builder'}).result,'OWNER_APPROVAL_VALID');});
test('invalid approval expiry timestamp is rejected',()=>{const p=createOwnerAuthorizationProposal({owner_intent:'x',requested_role:'Builder',task_id:'T',phase:'P',current_state:{},active_gate:{},runtime_preflight:{}});assert.throws(()=>validateOwnerApproval(p,{authorized:true,task_id:'T',phase:'P',role:'Builder',expires_at:'not-a-date'}),e=>e.code==='AUTHORIZATION_EXPIRED');});
