import test from 'node:test'; import assert from 'node:assert/strict'; import { runRuntimeProbeSet, executeSandboxMutationProbe, runFaultInjection, validateVerifiedOutboxEvent, consumeDerivedSyncOutbox, orderAutomationActions, selectRunnableActions, normalizeExecutionResult, evaluateGate } from '../../src/automation/index.mjs'; import { miniWorkspace } from './helpers.mjs';

test('probe set reports pass/fail without inventing facts',async()=>{const r=await runRuntimeProbeSet([{probe_id:'a',run:async()=>1},{probe_id:'b',run:async()=>{throw new Error('x')}}]);assert.equal(r.result,'PROBE_SET_HAS_FAILURES');});
test('mutation probe requires authorization',async()=>{const root=await miniWorkspace();await assert.rejects(()=>executeSandboxMutationProbe(root),e=>e.code==='MUTATION_PROBE_NOT_AUTHORIZED');});
test('authorized mutation probe is sandbox-only',async()=>{const root=await miniWorkspace();const r=await executeSandboxMutationProbe(root,{authorized:true});assert.equal(r.production_mutation,false);});
test('fault injection refuses production mode',async()=>await assert.rejects(()=>runFaultInjection({fault_id:'x',authorized:true,sandbox_only:false,inject:async()=>{},verify:async()=>true}),e=>e.code==='FAULT_INJECTION_PRODUCTION_FORBIDDEN'));
test('fault injection verifies expected failure',async()=>{const r=await runFaultInjection({fault_id:'x',authorized:true,inject:async()=>{throw Object.assign(new Error('boom'),{code:'X'})},verify:async o=>o.threw&&o.code==='X'});assert.equal(r.result,'FAULT_INJECTION_PASS');});
const event={source:'VERIFIED_DURABLE_OUTBOX',gate_result:'PASS',idempotency_key:'k',task_id:'T',completed_revision:4,canonical_checksum:'sha256:'+'a'.repeat(64)};const read={result:'CANONICAL_READ_VERIFIED',task_id:'T',revision:4,checksum:'sha256:'+'a'.repeat(64)};
test('verified outbox binds canonical read',()=>assert.equal(validateVerifiedOutboxEvent(event,read).result,'OUTBOX_EVENT_VERIFIED'));
test('raw or unverified outbox rejected',()=>assert.throws(()=>validateVerifiedOutboxEvent({...event,source:'RAW_STATUS'},read),e=>e.code==='OUTBOX_EVENT_UNVERIFIED'));
test('outbox consumer failure remains sync pending without completion rollback',async()=>{const root=await miniWorkspace();const r=await consumeDerivedSyncOutbox(root,{event,canonical_read:read,owner_authorized:true,consumer:async()=>{throw new Error('sync fail')}});assert.equal(r.result,'DERIVED_SYNC_PENDING');assert.equal(r.canonical_completion_rolled_back,false);});
test('outbox ack is idempotent',async()=>{const root=await miniWorkspace();const first=await consumeDerivedSyncOutbox(root,{event,canonical_read:read,owner_authorized:true,consumer:async()=>({ok:true})});const second=await consumeDerivedSyncOutbox(root,{event,canonical_read:read,owner_authorized:true,consumer:async()=>({ok:true})});assert.equal(first.result,'DERIVED_SYNC_ACKNOWLEDGED');assert.equal(second.result,'DERIVED_SYNC_ALREADY_ACKNOWLEDGED');});
test('scheduler topologically orders dependencies',()=>assert.deepEqual(orderAutomationActions([{action_id:'b',depends_on:['a']},{action_id:'a'}]).map(x=>x.action_id),['a','b']));
test('scheduler detects dependency cycle',()=>assert.throws(()=>orderAutomationActions([{action_id:'a',depends_on:['b']},{action_id:'b',depends_on:['a']}]),e=>e.code==='SCHEDULER_DEPENDENCY_CYCLE'));
test('scheduler separates waiting dependencies',()=>{const r=selectRunnableActions([{action_id:'a'},{action_id:'b',depends_on:['a']}]);assert.deepEqual(r.runnable.map(x=>x.action_id),['a']);assert.deepEqual(r.waiting.map(x=>x.action_id),['b']);});
test('result normalizer fails schema-invalid artifact',()=>assert.equal(normalizeExecutionResult({action_id:'a',raw_result:{ok:true,schema_valid:false},expected_schema:'X'}).status,'FAIL'));
test('gate evaluator requires pass results and evidence',()=>assert.equal(evaluateGate({results:[{action_id:'a',status:'PASS',evidence:['e']}],required_evidence_count:1}).result,'GATE_PASS'));
