import test from 'node:test'; import assert from 'node:assert/strict'; import { writeFile, symlink, mkdir, readFile } from 'node:fs/promises'; import path from 'node:path';
import { rebuildWorkspaceRegistry, verifyWorkspaceRegistry, resolveRegistryEntries, createRegistryUpdateProposal, persistWorkspaceRegistry, diffWorkspaceRegistry } from '../../src/automation/index.mjs'; import { miniWorkspace } from './helpers.mjs';

test('rebuild discovers indexed asset classes and is not content authority',async()=>{const root=await miniWorkspace();const r=await rebuildWorkspaceRegistry(root);assert.equal(r.content_authority,false);assert.ok(r.entries.some(x=>x.category==='TASK'));assert.ok(r.entries.some(x=>x.category==='ROLE'));assert.match(r.content_checksum,/^sha256:/);});
test('verify detects current registry integrity',async()=>{const root=await miniWorkspace();const r=await rebuildWorkspaceRegistry(root);const v=await verifyWorkspaceRegistry(root,r);assert.equal(v.result,'WORKSPACE_REGISTRY_VERIFIED');assert.equal(v.entry_count,r.entries.length);});
test('verify fails when indexed source changes',async()=>{const root=await miniWorkspace();const r=await rebuildWorkspaceRegistry(root);await writeFile(path.join(root,'PROJECT.md'),'changed');await assert.rejects(()=>verifyWorkspaceRegistry(root,r),e=>e.code==='REGISTRY_HASH_MISMATCH');});
test('registry query resolves category',async()=>{const root=await miniWorkspace();const r=await rebuildWorkspaceRegistry(root);const rows=resolveRegistryEntries(r,{category:'SPECIFICATION'});assert.equal(rows.length,1);});
test('registry query rejects invalid limit',async()=>{const root=await miniWorkspace();const r=await rebuildWorkspaceRegistry(root);assert.throws(()=>resolveRegistryEntries(r,{limit:0}),e=>e.code==='REGISTRY_QUERY_INVALID');});
test('update proposal cannot be empty',()=>assert.throws(()=>createRegistryUpdateProposal({}),e=>e.code==='REGISTRY_UPDATE_PROPOSAL_INVALID'));
test('update proposal explicitly requires approval',()=>{const p=createRegistryUpdateProposal({reason:'new file',changes:[{op:'ADD'}],requested_by:'Orchestrator'});assert.equal(p.owner_approval_required,true);assert.equal(p.registry_is_content_authority,false);});
test('persistence requires authorization',async()=>{const root=await miniWorkspace();const r=await rebuildWorkspaceRegistry(root);await assert.rejects(()=>persistWorkspaceRegistry(root,r),e=>e.code==='REGISTRY_WRITE_NOT_AUTHORIZED');});
test('authorized persistence writes runtime snapshot',async()=>{const root=await miniWorkspace();const r=await rebuildWorkspaceRegistry(root);const out=await persistWorkspaceRegistry(root,r,{authorized:true});assert.equal(out.result,'WORKSPACE_REGISTRY_SNAPSHOT_PERSISTED');const body=JSON.parse(await readFile(path.join(root,'.bai-os/workspace-registry.json'),'utf8'));assert.equal(body.content_checksum,r.content_checksum);});
test('registry diff reports additions without mutating source authority',async()=>{const root=await miniWorkspace();const a=await rebuildWorkspaceRegistry(root);await writeFile(path.join(root,'templates','new.md'),'x');const b=await rebuildWorkspaceRegistry(root);const d=diffWorkspaceRegistry(a,b);assert.equal(d.added.length,1);assert.equal(d.requires_authorized_update,true);});
test('symlinked discovered file is not followed as ordinary file',async()=>{const root=await miniWorkspace();await symlink('/etc/passwd',path.join(root,'templates','escape.md'));const r=await rebuildWorkspaceRegistry(root);assert.equal(r.entries.some(x=>x.path==='templates/escape.md'),false);});
test('multi-project index requires explicit unique project identity and roots',async()=>{const workspace=await miniWorkspace();const p2=path.join(workspace,'consumer');await mkdir(p2);await writeFile(path.join(p2,'PROJECT.md'),'# Consumer\n');const {buildWorkspaceProjectIndex,resolveWorkspaceProject}=await import('../../src/automation/index.mjs');const idx=await buildWorkspaceProjectIndex({workspace_root:workspace,projects:[{project_id:'OS',root:workspace},{project_id:'CONSUMER',root:p2}]});assert.equal(idx.projects.length,2);assert.equal(resolveWorkspaceProject(idx,'CONSUMER').root,p2);});
test('multi-project index rejects root outside workspace',async()=>{const workspace=await miniWorkspace();const {buildWorkspaceProjectIndex}=await import('../../src/automation/index.mjs');await assert.rejects(()=>buildWorkspaceProjectIndex({workspace_root:workspace,projects:[{project_id:'BAD',root:'/tmp'}]}),e=>e.code==='PROJECT_INDEX_ROOT_ESCAPE');});
