import test from 'node:test'; import assert from 'node:assert/strict'; import { mkdtemp } from 'node:fs/promises'; import os from 'node:os'; import path from 'node:path';
import { rebuildWorkspaceRegistry, resolveProject, resolveRisk, resolveTaskKnowledge } from '../../src/automation/index.mjs'; import { initializeKnowledgeRepository, saveKnowledgeAssetRevision } from '../../src/knowledge/index.mjs'; import { miniWorkspace } from './helpers.mjs'; import { asset } from '../knowledge/helpers.mjs';

test('project resolver binds explicit id to discovered project manifest',async()=>{const root=await miniWorkspace();const reg=await rebuildWorkspaceRegistry(root);const r=resolveProject({project_id:'P1',project_root:root,registry:reg});assert.equal(r.result,'PROJECT_RESOLVED');});
test('project resolver does not invent missing manifest',()=>assert.throws(()=>resolveProject({project_id:'P1',project_root:'/x',registry:{entries:[]}}),e=>e.code==='PROJECT_MANIFEST_NOT_DISCOVERED'));
test('risk resolver delegates to adaptive governance',()=>{const r=resolveRisk({system_scale:'FOUNDATION',criticality:'FOUNDATION',failure_impact:'CRITICAL'});assert.equal(r.profile_id,'DEV_4_FOUNDATION_CRITICAL');});
test('invalid risk input safe-stops',()=>assert.throws(()=>resolveRisk({system_scale:'planet'}),e=>e.code==='RISK_RESOLUTION_INVALID'));
test('knowledge integration resolves active asset and returns pack',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'bai-k-'));await initializeKnowledgeRepository(root);await saveKnowledgeAssetRevision(root,asset('K1'),{import_authorized:true});const r=await resolveTaskKnowledge({knowledge_root:root,request:{task_id:'T1',role:'Builder',phase:'DESIGN',scope:{level:'GLOBAL'},sensitivity:'INTERNAL',token_budget:10000}});assert.equal(r.result,'KNOWLEDGE_INTEGRATION_READY');assert.equal(r.context_ingestion_required,true);assert.equal(r.registry_is_knowledge_authority,false);});
test('knowledge integration blocks mandatory missing request',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'bai-k-'));await initializeKnowledgeRepository(root);const r=await resolveTaskKnowledge({knowledge_root:root,request:{task_id:'T1',role:'Builder',phase:'DESIGN',scope:{level:'GLOBAL'},sensitivity:'INTERNAL',token_budget:10000,required_asset_ids:['MISSING']}});assert.equal(r.result,'KNOWLEDGE_INTEGRATION_BLOCKED');});
