import { readdir, readFile, stat } from 'node:fs/promises';
import path from 'node:path';
import { hostname } from 'node:os';
import { listJournalTransactions } from '../security/journal.mjs';
import { resolveExistingInside } from '../security/path.mjs';
import { ARTIFACT_CLASS, MAINTENANCE_SEVERITY, REPAIR_CLASS } from './constants.mjs';
import { createMaintenanceFinding } from './finding.mjs';
import { createMaintenanceAdapter } from './fsck.mjs';
import { ageMs, sha256, stable } from './util.mjs';

export function securityJournalMaintenanceAdapter({stale_after_ms=60*60*1000}={}){return createMaintenanceAdapter({adapter_id:'security-journal',repair_actions:['ROLLBACK_PREPARED','COMPLETE_COMMITTING'],scan:async({root,clock})=>{const txs=await listJournalTransactions(root);const out=[];for(const tx of txs){if(tx.state==='PREPARED'&&ageMs(tx.prepared_at,clock)>=stale_after_ms)out.push(createMaintenanceFinding({adapter_id:'security-journal',code:'STALE_PREPARED_TRANSACTION',severity:MAINTENANCE_SEVERITY.HIGH,subject:tx.tx_id,artifact_class:ARTIFACT_CLASS.DERIVED,repair_class:REPAIR_CLASS.AUTO_REVERSIBLE,reversible:true,repair_action:'ROLLBACK_PREPARED',evidence:{tx_id:tx.tx_id,state:tx.state}}, {clock}));if(tx.state==='COMMITTING')out.push(createMaintenanceFinding({adapter_id:'security-journal',code:'INTERRUPTED_COMMITTING_TRANSACTION',severity:MAINTENANCE_SEVERITY.CRITICAL,subject:tx.tx_id,artifact_class:ARTIFACT_CLASS.CANONICAL,repair_class:REPAIR_CLASS.OWNER_REQUIRED,reversible:false,canonical_impact:true,repair_action:'COMPLETE_COMMITTING',evidence:{tx_id:tx.tx_id,state:tx.state}}, {clock}));}return out;}});}

async function pidAlive(pid){const n=Number(pid);if(!Number.isInteger(n)||n<=0)return false;try{process.kill(n,0);return true;}catch(e){return e.code==='EPERM';}}
export function releaseLockMaintenanceAdapter({stale_after_ms=30*60*1000,process_alive=pidAlive}={}){return createMaintenanceAdapter({adapter_id:'release-lock',repair_actions:['REMOVE_STALE_RELEASE_LOCK'],scan:async({root,clock})=>{let dir;try{dir=await resolveExistingInside(root,'.bai-os/release/locks');}catch(e){if(e.code==='SECURITY_PATH_MISSING')return [];throw e;}const entries=await readdir(dir,{withFileTypes:true});const out=[];for(const ent of entries.filter(e=>e.isFile()&&e.name.endsWith('.lock'))){const rel=`.bai-os/release/locks/${ent.name}`;const p=await resolveExistingInside(root,rel);const info=await stat(p);const raw=(await readFile(p,'utf8')).trim();let record;try{record=JSON.parse(raw);}catch{record={release_lock_version:'LEGACY',pid:Number(raw),host:null,owner_token:null,acquired_at:null};}const pid=record.pid;const sameHost=record.host===hostname();const alive=sameHost?await process_alive(pid):null;const basis=record.acquired_at?Date.parse(record.acquired_at):info.mtimeMs;const age=Math.max(0,(clock() instanceof Date?clock():new Date(clock())).getTime()-basis);const verifiable=record.release_lock_version!=='LEGACY'&&sameHost&&record.owner_token&&Number.isInteger(pid);if(verifiable&&alive===false&&age>=stale_after_ms)out.push(createMaintenanceFinding({adapter_id:'release-lock',code:'STALE_RELEASE_LOCK',severity:MAINTENANCE_SEVERITY.HIGH,subject:rel,artifact_class:ARTIFACT_CLASS.DERIVED,repair_class:REPAIR_CLASS.AUTO_REVERSIBLE,reversible:true,repair_action:'REMOVE_STALE_RELEASE_LOCK',evidence:{path:rel,pid,host:record.host,owner_token:record.owner_token,age_ms:age,process_alive:false,lock_version:record.release_lock_version}},{clock}));else if(alive!==true)out.push(createMaintenanceFinding({adapter_id:'release-lock',code:'AMBIGUOUS_RELEASE_LOCK',severity:MAINTENANCE_SEVERITY.WARNING,subject:rel,artifact_class:ARTIFACT_CLASS.DERIVED,repair_class:REPAIR_CLASS.QUARANTINE_ONLY,reversible:true,repair_action:'QUARANTINE_RELEASE_LOCK',evidence:{path:rel,pid,host:record.host??null,age_ms:age,process_alive:alive,lock_version:record.release_lock_version}},{clock}));}return out;}});}

export function manifestMaintenanceAdapter(entries=[]){return createMaintenanceAdapter({adapter_id:'manifest-integrity',scan:async({root,clock})=>{const out=[];for(const e of entries){try{const p=await resolveExistingInside(root,e.path);const bytes=await readFile(p);if(e.checksum&&sha256(bytes)!==e.checksum)out.push(createMaintenanceFinding({adapter_id:'manifest-integrity',code:'MANIFEST_CHECKSUM_MISMATCH',severity:MAINTENANCE_SEVERITY.CRITICAL,subject:e.path,artifact_class:e.artifact_class??ARTIFACT_CLASS.CANONICAL,repair_class:REPAIR_CLASS.OWNER_REQUIRED,reversible:false,canonical_impact:(e.artifact_class??ARTIFACT_CLASS.CANONICAL)===ARTIFACT_CLASS.CANONICAL,evidence:{path:e.path,expected:e.checksum,actual:sha256(bytes)}},{clock}));}catch(err){if(err.code==='SECURITY_PATH_MISSING')out.push(createMaintenanceFinding({adapter_id:'manifest-integrity',code:'MANIFEST_FILE_MISSING',severity:MAINTENANCE_SEVERITY.HIGH,subject:e.path,artifact_class:e.artifact_class??ARTIFACT_CLASS.DERIVED,repair_class:e.rebuildable?REPAIR_CLASS.AUTO_REVERSIBLE:REPAIR_CLASS.OWNER_REQUIRED,reversible:Boolean(e.rebuildable),canonical_impact:!e.rebuildable,repair_action:e.rebuildable?'REBUILD_MANIFEST_FILE':null,evidence:{path:e.path}},{clock}));else throw err;}}return out;}});}

export function conformanceEvidenceMaintenanceAdapter({certifications=[],current_fingerprints={},max_age_ms=24*60*60*1000}={}){return createMaintenanceAdapter({adapter_id:'conformance-evidence',scan:async({clock})=>{const out=[];for(const c of certifications){const expected=c.certification_checksum;const body=Object.fromEntries(Object.entries(c).filter(([k])=>k!=='certification_checksum'));if(expected&&sha256(stable(body))!==expected)out.push(createMaintenanceFinding({adapter_id:'conformance-evidence',code:'CONFORMANCE_CERTIFICATION_CHECKSUM_MISMATCH',severity:MAINTENANCE_SEVERITY.CRITICAL,subject:c.certification_id??'unknown',artifact_class:ARTIFACT_CLASS.DERIVED,repair_class:REPAIR_CLASS.NONE,reversible:false,evidence:{certification_id:c.certification_id??null}},{clock}));const age=ageMs(c.generated_at,clock);if(age>max_age_ms)out.push(createMaintenanceFinding({adapter_id:'conformance-evidence',code:'CONFORMANCE_EVIDENCE_STALE',severity:MAINTENANCE_SEVERITY.WARNING,subject:c.certification_id??'unknown',artifact_class:ARTIFACT_CLASS.DERIVED,repair_class:REPAIR_CLASS.NONE,reversible:true,evidence:{generated_at:c.generated_at,age_ms:age}},{clock}));for(const f of c.scope?.fixtures??[]){const now=current_fingerprints[f.fixture_id];const old=f.environment_fingerprint;if(now&&old&&now!==old)out.push(createMaintenanceFinding({adapter_id:'conformance-evidence',code:'CONFORMANCE_ENVIRONMENT_DRIFT',severity:MAINTENANCE_SEVERITY.HIGH,subject:f.fixture_id,artifact_class:ARTIFACT_CLASS.DERIVED,repair_class:REPAIR_CLASS.NONE,reversible:true,evidence:{fixture_id:f.fixture_id,previous:old,current:now}},{clock}));}}return out;}});}

export function verifierMaintenanceAdapter({adapter_id,verify,severity=MAINTENANCE_SEVERITY.CRITICAL,artifact_class=ARTIFACT_CLASS.CANONICAL,repair_class=REPAIR_CLASS.OWNER_REQUIRED,repair_action=null}={}){return createMaintenanceAdapter({adapter_id,repair_actions:repair_action?[repair_action]:[],scan:async({root,context,clock})=>{try{await verify(root,context);return [];}catch(error){return [createMaintenanceFinding({adapter_id,code:error.code??'VERIFICATION_FAILED',severity,subject:context.subject??adapter_id,artifact_class,repair_class,reversible:false,canonical_impact:artifact_class===ARTIFACT_CLASS.CANONICAL,trust_impact:artifact_class===ARTIFACT_CLASS.TRUST,repair_action,evidence:{error_code:error.code??null,message:error.message}}, {clock})];}}});}

export async function createBuiltinRepairHandlers({stale_lock_min_age_ms=30*60*1000,process_alive=pidAlive,rebuilders={},clock=()=>new Date()}={}){
  const { recoverJournalTransaction } = await import('../security/journal.mjs');
  const { rm } = await import('node:fs/promises');
  const { quarantineArtifact } = await import('./quarantine.mjs');
  return {
    ROLLBACK_PREPARED:{revalidate:async({root,operation})=>(await import('../security/journal.mjs')).readJournalTransaction(root,operation.subject).then(x=>x.state==='PREPARED'),execute:async({root,operation})=>recoverJournalTransaction(root,operation.subject,{strategy:'ROLLBACK'}),verify:async({root,operation})=>(await import('../security/journal.mjs')).readJournalTransaction(root,operation.subject).then(x=>x.state==='ROLLED_BACK')},
    COMPLETE_COMMITTING:{execute:async({root,operation})=>recoverJournalTransaction(root,operation.subject,{strategy:'COMPLETE'}),verify:async({root,operation})=>(await import('../security/journal.mjs')).readJournalTransaction(root,operation.subject).then(x=>x.state==='COMMITTED')},
    REMOVE_STALE_RELEASE_LOCK:{revalidate:async({root,operation})=>{const p=await resolveExistingInside(root,operation.subject);const info=await stat(p);const raw=(await readFile(p,'utf8')).trim();let record;try{record=JSON.parse(raw);}catch{return false;}if(record.host!==hostname()||!record.owner_token||!Number.isInteger(record.pid))return false;if(await process_alive(record.pid))return false;const basis=record.acquired_at?Date.parse(record.acquired_at):info.mtimeMs;const now=(clock() instanceof Date?clock():new Date(clock())).getTime();return now-basis>=stale_lock_min_age_ms;},execute:async({root,operation})=>{const p=await resolveExistingInside(root,operation.subject);const raw=(await readFile(p,'utf8')).trim();const record=JSON.parse(raw);await rm(p,{force:true});return {removed:operation.subject,pid:record.pid,owner_token:record.owner_token};},verify:async({root,operation})=>{try{await resolveExistingInside(root,operation.subject);return false;}catch(e){return e.code==='SECURITY_PATH_MISSING';}}},
    QUARANTINE_RELEASE_LOCK:{revalidate:async({root,operation})=>{try{await resolveExistingInside(root,operation.subject);return true;}catch{return false;}},execute:async({root,operation})=>quarantineArtifact(root,operation.subject,{reason:'AMBIGUOUS_RELEASE_LOCK'}),verify:async({root,operation})=>{try{await resolveExistingInside(root,operation.subject);return false;}catch(e){return e.code==='SECURITY_PATH_MISSING';}}},
    REBUILD_MANIFEST_FILE:{revalidate:async()=>true,execute:async(ctx)=>{const fn=rebuilders[ctx.operation.subject];if(typeof fn!=='function')throw new Error('MAINTENANCE_REBUILDER_MISSING');return fn(ctx);},verify:async()=>true}
  };
}
