export const MAINTENANCE_SEVERITY = Object.freeze({ INFO:'INFO', WARNING:'WARNING', HIGH:'HIGH', CRITICAL:'CRITICAL' });
export const MAINTENANCE_STATUS = Object.freeze({ PASS:'PASS', DEGRADED:'DEGRADED', BLOCKED:'BLOCKED' });
export const REPAIR_CLASS = Object.freeze({ NONE:'NONE', AUTO_REVERSIBLE:'AUTO_REVERSIBLE', OWNER_REQUIRED:'OWNER_REQUIRED', QUARANTINE_ONLY:'QUARANTINE_ONLY' });
export const REPAIR_RESULT = Object.freeze({ PLANNED:'PLANNED', SKIPPED:'SKIPPED', REPAIRED:'REPAIRED', ROLLED_BACK:'ROLLED_BACK', QUARANTINED:'QUARANTINED', OWNER_REQUIRED:'OWNER_REQUIRED', FAILED:'FAILED' });
export const FINDING_STATE = Object.freeze({ OPEN:'OPEN', REPAIRED:'REPAIRED', QUARANTINED:'QUARANTINED', ESCALATED:'ESCALATED' });
export const ARTIFACT_CLASS = Object.freeze({ CANONICAL:'CANONICAL', AUTHORITY:'AUTHORITY', TRUST:'TRUST', DERIVED:'DERIVED', CACHE:'CACHE', TEMPORARY:'TEMPORARY', EXTERNAL:'EXTERNAL' });
