import { verifyKnowledgeRepository } from '../knowledge/repository.mjs';
import { verifyMonitoringEventLedger } from '../monitoring/store.mjs';
import { readIntegrationAudit } from '../integration/audit.mjs';
import { readSecurityLedger } from '../security/ledger.mjs';
import { readConsumerReleaseState } from '../release/installer.mjs';
import { verifyInstallationAttestation } from '../release/attestation.mjs';
import { resolveExistingInside } from '../security/path.mjs';
import { readFile } from 'node:fs/promises';
import { ARTIFACT_CLASS, MAINTENANCE_SEVERITY, REPAIR_CLASS } from './constants.mjs';
import { createMaintenanceFinding } from './finding.mjs';
import { createMaintenanceAdapter } from './fsck.mjs';
import { verifierMaintenanceAdapter } from './builtins.mjs';

export function knowledgeRepositoryMaintenanceAdapter(){return createMaintenanceAdapter({adapter_id:'knowledge-repository',scan:async({root,context,clock})=>{const knowledgeRoot=context.knowledge_root??root;try{await verifyKnowledgeRepository(knowledgeRoot);return [];}catch(error){return [createMaintenanceFinding({adapter_id:'knowledge-repository',code:error.code??'KNOWLEDGE_VERIFY_FAILED',severity:MAINTENANCE_SEVERITY.CRITICAL,subject:knowledgeRoot,artifact_class:ARTIFACT_CLASS.CANONICAL,repair_class:REPAIR_CLASS.OWNER_REQUIRED,reversible:false,canonical_impact:true,evidence:{error_code:error.code??null,message:error.message,details:error.details??null}},{clock})];}}});}

export function monitoringLedgerMaintenanceAdapter(){return verifierMaintenanceAdapter({adapter_id:'monitoring-ledger',verify:async(root)=>verifyMonitoringEventLedger(root),severity:MAINTENANCE_SEVERITY.HIGH,artifact_class:ARTIFACT_CLASS.DERIVED,repair_class:REPAIR_CLASS.QUARANTINE_ONLY,repair_action:'QUARANTINE_MONITORING_TAIL'});}

export function integrationAuditMaintenanceAdapter(){return verifierMaintenanceAdapter({adapter_id:'integration-audit',verify:async(root)=>readIntegrationAudit(root),severity:MAINTENANCE_SEVERITY.CRITICAL,artifact_class:ARTIFACT_CLASS.AUTHORITY,repair_class:REPAIR_CLASS.OWNER_REQUIRED});}

export function securityLedgerMaintenanceAdapter({ledgers=[]}={}){return createMaintenanceAdapter({adapter_id:'security-ledgers',scan:async({root,clock})=>{const out=[];for(const l of ledgers){try{await readSecurityLedger(root,l.name,{public_key:l.public_key??null,expected_key_id:l.expected_key_id??null,require_signature:Boolean(l.require_signature)});}catch(error){out.push(createMaintenanceFinding({adapter_id:'security-ledgers',code:error.code??'SECURITY_LEDGER_VERIFY_FAILED',severity:MAINTENANCE_SEVERITY.CRITICAL,subject:l.name,artifact_class:ARTIFACT_CLASS.TRUST,repair_class:REPAIR_CLASS.OWNER_REQUIRED,reversible:false,trust_impact:true,evidence:{ledger:l.name,error_code:error.code??null,message:error.message}},{clock}));}}return out;}});}

export function releaseStateMaintenanceAdapter(){return createMaintenanceAdapter({adapter_id:'release-state',scan:async({root,context,clock})=>{const out=[];const state=await readConsumerReleaseState(root);if(!state)return out;if(state.rollback_checkpoint_id){try{await resolveExistingInside(root,`.bai-os/release/checkpoints/${state.rollback_checkpoint_id}.json`);}catch(error){if(error.code==='SECURITY_PATH_MISSING')out.push(createMaintenanceFinding({adapter_id:'release-state',code:'RELEASE_ROLLBACK_CHECKPOINT_MISSING',severity:MAINTENANCE_SEVERITY.HIGH,subject:state.rollback_checkpoint_id,artifact_class:ARTIFACT_CLASS.DERIVED,repair_class:REPAIR_CLASS.NONE,reversible:false,evidence:{checkpoint_id:state.rollback_checkpoint_id,os_version:state.os_version}},{clock}));else throw error;}}
if(context.release_manifest&&context.installation_attestation){try{verifyInstallationAttestation(context.installation_attestation,context.release_manifest,{public_key:context.attestation_public_key??null,expected_key_id:context.attestation_key_id??null,require_signature:Boolean(context.require_attestation_signature)});}catch(error){out.push(createMaintenanceFinding({adapter_id:'release-state',code:error.code??'RELEASE_ATTESTATION_VERIFY_FAILED',severity:MAINTENANCE_SEVERITY.CRITICAL,subject:state.os_version,artifact_class:ARTIFACT_CLASS.TRUST,repair_class:REPAIR_CLASS.OWNER_REQUIRED,reversible:false,trust_impact:true,evidence:{error_code:error.code??null,message:error.message}},{clock}));}}
return out;}});}

export function jsonArtifactMaintenanceAdapter({adapter_id,path,artifact_class=ARTIFACT_CLASS.DERIVED,validate}={}){return createMaintenanceAdapter({adapter_id,scan:async({root,clock})=>{try{const p=await resolveExistingInside(root,path);const parsed=JSON.parse(await readFile(p,'utf8'));await validate(parsed);return [];}catch(error){return [createMaintenanceFinding({adapter_id,code:error.code??(error instanceof SyntaxError?'JSON_ARTIFACT_CORRUPT':'ARTIFACT_VERIFY_FAILED'),severity:[ARTIFACT_CLASS.DERIVED,ARTIFACT_CLASS.CACHE,ARTIFACT_CLASS.TEMPORARY].includes(artifact_class)?MAINTENANCE_SEVERITY.HIGH:MAINTENANCE_SEVERITY.CRITICAL,subject:path,artifact_class,repair_class:[ARTIFACT_CLASS.DERIVED,ARTIFACT_CLASS.CACHE,ARTIFACT_CLASS.TEMPORARY].includes(artifact_class)?REPAIR_CLASS.QUARANTINE_ONLY:REPAIR_CLASS.OWNER_REQUIRED,reversible:[ARTIFACT_CLASS.DERIVED,ARTIFACT_CLASS.CACHE,ARTIFACT_CLASS.TEMPORARY].includes(artifact_class),canonical_impact:artifact_class===ARTIFACT_CLASS.CANONICAL,trust_impact:artifact_class===ARTIFACT_CLASS.TRUST,evidence:{error_code:error.code??null,message:error.message}},{clock})];}}});}
