import { createConnectorManifest } from './registry.mjs';
import { IntegrationError, deepFreeze } from './util.mjs';
export function createFunctionConnector(manifestInput,invoke){const manifest=manifestInput.content_checksum?manifestInput:createConnectorManifest(manifestInput);if(typeof invoke!=='function')throw new IntegrationError('CONNECTOR_INVOKER_REQUIRED');return deepFreeze({manifest,invoke});}
function profile(kind,connector_id,capabilities,extra={}){return createConnectorManifest({connector_id,kind,connector_version:extra.connector_version??'1.0.0',response_trust:extra.response_trust??'UNTRUSTED',credential_provider:extra.credential_provider??null,capabilities,metadata:extra.metadata??{}});}
export const createGitHubManifest=(id='github',extra={})=>profile('GITHUB',id,[{name:'repository',operations:['read','commit','pull_request','issue','release'],side_effect:'EXTERNAL',requires_authorization:true,idempotency_required:true,required_scopes:['repo:write']},{name:'repository_read',operations:['read','search'],side_effect:'NONE',required_scopes:['repo:read']}],extra);
export const createCommunicationManifest=(id='communication',extra={})=>profile('COMMUNICATION',id,[{name:'message',operations:['send'],side_effect:'EXTERNAL',requires_authorization:true,idempotency_required:true,required_scopes:['message:send']},{name:'message_read',operations:['search','read'],side_effect:'NONE',required_scopes:['message:read']}],extra);
export const createExternalAIManifest=(id='external-ai',extra={})=>profile('EXTERNAL_AI',id,[{name:'generate',operations:['image','video','audio','text'],side_effect:'EXTERNAL',requires_authorization:true,idempotency_required:true,cost_metered:true,license_sensitive:true,max_cost_microusd:extra.max_cost_microusd??10000000,max_timeout_ms:extra.max_timeout_ms??1800000}],extra);
export const createStorageManifest=(id='storage',extra={})=>profile('STORAGE',id,[{name:'object_read',operations:['read','list'],side_effect:'NONE',required_scopes:['storage:read']},{name:'object_write',operations:['write','delete'],side_effect:'EXTERNAL',requires_authorization:true,idempotency_required:true,required_scopes:['storage:write']}],extra);
export const createMcpManifest=(id='mcp',extra={})=>profile('MCP',id,[{name:'tool',operations:['invoke'],side_effect:extra.side_effect??'EXTERNAL',requires_authorization:extra.requires_authorization??true,idempotency_required:extra.idempotency_required??true}],extra);
