import { mkdir, open, readFile, rm } from 'node:fs/promises';
import path from 'node:path';
import { resolveExistingInside, resolveWritableInside } from '../automation/util.mjs';
import { AUDIT_EVENTS, SENSITIVE_KEYS } from './constants.mjs';
import { IntegrationError, checksumObject, deepFreeze, redact, sha256, stable } from './util.mjs';
const rel='integration/audit.jsonl', lock='integration/.audit.lock'; const checksum=r=>checksumObject(r,['record_checksum']);
async function acquire(root){await mkdir(path.join(root,'integration'),{recursive:true});const p=await resolveWritableInside(root,lock,IntegrationError,{escapeCode:'INTEGRATION_PATH_ESCAPE'});try{const h=await open(p,'wx',0o600);await h.writeFile(String(process.pid));await h.sync();await h.close();}catch(e){if(e.code==='EEXIST')throw new IntegrationError('INTEGRATION_AUDIT_BUSY');throw e;}}
async function release(root){await rm(path.join(root,lock),{force:true}).catch(()=>{});}
export function sanitizeAuditDetails(details){return redact(structuredClone(details??{}),SENSITIVE_KEYS);}
export async function readIntegrationAudit(root){let p;try{p=await resolveExistingInside(root,rel,IntegrationError,{missingCode:'INTEGRATION_AUDIT_MISSING',escapeCode:'INTEGRATION_PATH_ESCAPE'});}catch(e){if(e.code==='INTEGRATION_AUDIT_MISSING')return deepFreeze([]);throw e;}const text=await readFile(p,'utf8');const rows=[];let prev=null;for(const line of text.split('\n').filter(Boolean)){let r;try{r=JSON.parse(line);}catch{throw new IntegrationError('INTEGRATION_AUDIT_CORRUPT');}if(r.seq!==rows.length+1||r.previous_record_checksum!==prev||r.record_checksum!==checksum(r)||!AUDIT_EVENTS.includes(r.event_type))throw new IntegrationError('INTEGRATION_AUDIT_CORRUPT');prev=r.record_checksum;rows.push(r);}return deepFreeze(rows);}
export async function appendIntegrationAudit(root,event={}){if(!AUDIT_EVENTS.includes(event.event_type))throw new IntegrationError('INTEGRATION_AUDIT_EVENT_INVALID');await acquire(root);try{const rows=await readIntegrationAudit(root);const p=await resolveWritableInside(root,rel,IntegrationError,{escapeCode:'INTEGRATION_PATH_ESCAPE'});const row={seq:rows.length+1,event_type:event.event_type,at:event.at,request_id:event.request_id??null,connector_id:event.connector_id??null,capability:event.capability??null,operation:event.operation??null,idempotency_key:event.idempotency_key??null,details:sanitizeAuditDetails(event.details),previous_record_checksum:rows.at(-1)?.record_checksum??null};row.record_checksum=checksum(row);const h=await open(p,'a',0o600);try{await h.writeFile(JSON.stringify(row)+'\n');await h.sync();}finally{await h.close();}const reread=await readIntegrationAudit(root);if(reread.at(-1)?.record_checksum!==row.record_checksum)throw new IntegrationError('INTEGRATION_AUDIT_VERIFY_FAILED');return deepFreeze(row);}finally{await release(root);}}
export function integrationIdempotencyFingerprint(request={}){return sha256(stable({project_id:request.project_id,task_id:request.task_id,connector_id:request.connector_id,capability:request.capability,operation:request.operation,payload:request.payload,data_classification:request.data_classification,estimated_cost_microusd:request.estimated_cost_microusd,license_context:request.license_context}));}
export async function findSuccessfulIdempotentResult(root,request={}){if(!request.idempotency_key)return null;const fp=integrationIdempotencyFingerprint(request);const rows=await readIntegrationAudit(root);for(let i=rows.length-1;i>=0;i--){const r=rows[i];if(r.event_type==='EXECUTION_SUCCEEDED'&&r.connector_id===request.connector_id&&r.capability===request.capability&&r.operation===request.operation&&r.idempotency_key===request.idempotency_key){if(r.details?.request_fingerprint!==fp)throw new IntegrationError('INTEGRATION_IDEMPOTENCY_CONFLICT');return r.details?.response??null;}}return null;}
