import { createMonitoringEvent } from '../monitoring/event.mjs';
import { recordActualCost, releaseCostReservation, reserveCost } from '../cost-guard/index.mjs';
import { appendIntegrationAudit, findSuccessfulIdempotentResult, integrationIdempotencyFingerprint } from './audit.mjs';
import { resolveCredentialSecret } from './credentials.mjs';
import { evaluateIntegrationPolicy } from './policy.mjs';
import { verifyIntegrationRequest } from './request.mjs';
import { IntegrationError, containsExactSecret, deepFreeze, nowIso, redact, sleep } from './util.mjs';
import { SENSITIVE_KEYS } from './constants.mjs';
import { scanSensitiveData } from '../security/dlp.mjs';
import { evaluateEgressTarget } from '../security/network.mjs';
function classify(error){const code=error?.code??'';if(['RATE_LIMIT','ETIMEDOUT','ECONNRESET','EAI_AGAIN'].some(x=>code.includes(x)))return 'TRANSIENT';if(code.includes('AUTH')||code.includes('CREDENTIAL'))return 'AUTH';if(code.includes('SCHEMA')||code.includes('INVALID'))return 'SCHEMA';return 'PERMANENT';}

async function invokeWithTimeout(factory,timeoutMs){let timer;const controller=new AbortController();try{return await Promise.race([Promise.resolve().then(()=>factory(controller.signal)),new Promise((_,reject)=>{timer=setTimeout(()=>{controller.abort();const e=new Error('connector timeout');e.code='ETIMEDOUT';reject(e);},timeoutMs);})]);}finally{if(timer)clearTimeout(timer);}}
function normalizeResponse(raw,{manifest,request,attempt,at}){return deepFreeze({integration_response_version:'1.0.0',request_id:request.request_id,connector_id:request.connector_id,capability:request.capability,operation:request.operation,ok:true,trust:manifest.response_trust,canonical:false,requires_review_for_canonicalization:manifest.response_trust!=='VERIFIED',attempt,received_at:at,data:structuredClone(raw?.data??raw??null),metadata:structuredClone(raw?.metadata??{})});}
export class IntegrationGateway{
  constructor({root,registry,connectors={},credential_resolver=null,monitoring_sink=null,clock=()=>new Date(),max_retries=2,retry_delay_ms=0,cost_budgets=null,dns_resolver=null}={}){if(!root||!registry)throw new IntegrationError('INTEGRATION_GATEWAY_CONFIG_INVALID');this.root=root;this.registry=registry;this.connectors=connectors;this.credential_resolver=credential_resolver;this.monitoring_sink=monitoring_sink;this.clock=clock;this.max_retries=max_retries;this.retry_delay_ms=retry_delay_ms;this.cost_budgets=cost_budgets;this.dns_resolver=dns_resolver;this.rate=new Map();}
  async audit(event_type,request,details={}){return appendIntegrationAudit(this.root,{event_type,at:nowIso(this.clock),request_id:request.request_id,connector_id:request.connector_id,capability:request.capability,operation:request.operation,idempotency_key:request.idempotency_key,details});}
  async monitor(request,metric,value,severity_hint='INFO',attributes={}){if(typeof this.monitoring_sink!=='function')return;const e=createMonitoringEvent({project_id:request.project_id,task_id:request.task_id,run_id:request.run_id,component:'INTEGRATION',metric,value,severity_hint,attributes},{clock:this.clock});await this.monitoring_sink(e);}
  enforceRate(request,manifest){const limit=manifest.metadata?.rate_limit_per_window??null;if(!limit)return;const windowMs=manifest.metadata?.rate_limit_window_ms??60000;const key=`${request.connector_id}:${request.capability}`;const now=this.clock().getTime();let xs=(this.rate.get(key)??[]).filter(t=>now-t<windowMs);if(xs.length>=limit)throw new IntegrationError('INTEGRATION_RATE_LIMIT_LOCAL');xs.push(now);this.rate.set(key,xs);}
  async execute(request){verifyIntegrationRequest(request);const dlpFindings=scanSensitiveData(request.payload);if(dlpFindings.length)throw new IntegrationError('INTEGRATION_OUTBOUND_DLP_BLOCKED','sensitive material in outbound payload',{findings:dlpFindings});let credentialRef=request.credential_ref;let policy;try{policy=evaluateIntegrationPolicy({request,registry:this.registry,credential_ref:credentialRef,now:this.clock().getTime()});this.enforceRate(request,policy.manifest);await this.audit('REQUEST_ACCEPTED',request,{policy:{decision:policy.decision,payload_bytes:policy.payload_bytes}});}catch(error){await this.audit('REQUEST_BLOCKED',request,{error:{code:error.code??'ERROR',message:error.message}}).catch(()=>{});await this.monitor(request,'integration.blocked',1,'HIGH',{code:error.code??'ERROR'}).catch(()=>{});throw error;}
    if(policy.manifest.metadata?.endpoint_url){const endpoint=new URL(policy.manifest.metadata.endpoint_url);if(!Array.isArray(policy.manifest.metadata.egress_allow_hosts)||!policy.manifest.metadata.egress_allow_hosts.length)throw new IntegrationError('INTEGRATION_EGRESS_ALLOWLIST_REQUIRED');if(typeof this.dns_resolver!=='function')throw new IntegrationError('INTEGRATION_EGRESS_DNS_RESOLVER_REQUIRED');const resolved=await this.dns_resolver(endpoint.hostname);try{evaluateEgressTarget({url:policy.manifest.metadata.endpoint_url,allow_hosts:policy.manifest.metadata.egress_allow_hosts,allow_protocols:policy.manifest.metadata.egress_allow_protocols??['https:'],resolved_addresses:resolved});}catch(error){throw new IntegrationError('INTEGRATION_EGRESS_POLICY_BLOCKED',error.message,{cause_code:error.code});}}
    if(request.idempotency_key){const existing=await findSuccessfulIdempotentResult(this.root,request);if(existing){await this.audit('IDEMPOTENT_REPLAY',request,{response:existing});await this.monitor(request,'integration.idempotent_replay',1,'INFO');return deepFreeze({...structuredClone(existing),replayed:true});}}
    const connector=this.connectors[request.connector_id];if(!connector||typeof connector.invoke!=='function')throw new IntegrationError('CONNECTOR_RUNTIME_NOT_AVAILABLE');const credential=await resolveCredentialSecret(credentialRef,this.credential_resolver);let costReservation=null;if(this.cost_budgets&&request.estimated_cost_microusd>0){if(!request.role||!request.session_id)throw new IntegrationError('INTEGRATION_COST_BINDING_REQUIRED');costReservation=await reserveCost({root:this.root,budgets:this.cost_budgets,task_id:request.task_id,role:request.role,session_id:request.session_id,model_id:`connector:${request.connector_id}`,cost_microusd:request.estimated_cost_microusd});}let last;
    for(let attempt=1;attempt<=this.max_retries+1;attempt++){await this.audit('EXECUTION_STARTED',request,{attempt});const started=Date.now();try{const timeoutMs=policy.capability.max_timeout_ms;const raw=await invokeWithTimeout((signal)=>connector.invoke({operation:request.operation,payload:structuredClone(request.payload),credential,context:{project_id:request.project_id,task_id:request.task_id,run_id:request.run_id,request_id:request.request_id,idempotency_key:request.idempotency_key,signal}}),timeoutMs);if(containsExactSecret(raw,credential))throw new IntegrationError('INTEGRATION_CREDENTIAL_LEAK_DETECTED');const response=normalizeResponse(raw,{manifest:policy.manifest,request,attempt,at:nowIso(this.clock)});if(costReservation){const actual=Number.isSafeInteger(raw?.metadata?.actual_cost_microusd)&&raw.metadata.actual_cost_microusd>=0?raw.metadata.actual_cost_microusd:request.estimated_cost_microusd;await recordActualCost({root:this.root,reservation_id:costReservation.reservation_id,task_id:request.task_id,role:request.role,session_id:request.session_id,model_id:`connector:${request.connector_id}`,cost_microusd:actual});costReservation=null;}await this.audit('EXECUTION_SUCCEEDED',request,{attempt,duration_ms:Date.now()-started,request_fingerprint:integrationIdempotencyFingerprint(request),response:redact(response,SENSITIVE_KEYS)});await this.monitor(request,'integration.success',1,'INFO',{connector_kind:policy.manifest.kind,attempt});return response;}catch(error){last=error;const kind=classify(error);await this.audit('EXECUTION_FAILED',request,{attempt,error:{code:error.code??'ERROR',class:kind,message:error.message}});const retry=attempt<=this.max_retries&&policy.retry_safe&&kind==='TRANSIENT';if(retry){await this.audit('RETRY_SCHEDULED',request,{attempt,next_attempt:attempt+1});await this.monitor(request,'integration.retry',1,'WARNING',{attempt});if(this.retry_delay_ms)await sleep(this.retry_delay_ms);continue;}if(costReservation){await releaseCostReservation({root:this.root,reservation_id:costReservation.reservation_id,task_id:request.task_id,role:request.role,session_id:request.session_id,reason:'INTEGRATION_FAILED'}).catch(()=>{});costReservation=null;}await this.monitor(request,'integration.failure',1,'HIGH',{code:error.code??'ERROR',class:kind,attempt});throw new IntegrationError('INTEGRATION_EXECUTION_FAILED',error.message,{cause_code:error.code??null,class:kind,attempt});}}
    throw last;
  }
}
