import assert from 'node:assert/strict';
import test from 'node:test';
import {intersectClientPolicies,mapConsumerEventToKnowledgeEvidence,sanitizeConsumerEvidencePayload,validateConsumerEvidenceBatch,validateConsumerEvidenceEvent} from '../../src/knowledge-evolution/index.mjs';
import {validEvent} from './helpers.mjs';

test('valid P0 event is normalized',()=>{const e=validateConsumerEvidenceEvent(validEvent());assert.equal(e.product.product_id,'bai-video-production');assert.equal(e.occurred_at,'2026-08-11T00:00:00.000Z');});
test('P3 raw content is rejected',()=>assert.throws(()=>validateConsumerEvidenceEvent(validEvent({privacy_level:'P3'})),e=>e.code==='CONSUMER_EVIDENCE_PRIVACY_LEVEL_INVALID'));
test('secret-like payload is rejected without echoing secret',()=>{const secret='sk-'+'A'.repeat(24);assert.throws(()=>sanitizeConsumerEvidencePayload('user_feedback','P2',{feature:'x',rating:2,category:'u',comment:secret}),e=>e.code==='CONSUMER_EVIDENCE_SECRET_DETECTED'&&!String(e.message).includes(secret));});
test('sensitive payload key is rejected',()=>assert.throws(()=>validateConsumerEvidenceEvent(validEvent({payload:{feature:'x',result:'success',api_key:'x'}})),e=>['CONSUMER_EVIDENCE_SENSITIVE_KEY_FORBIDDEN','CONSUMER_EVIDENCE_SECRET_DETECTED'].includes(e.code)));
test('unknown payload key is rejected',()=>assert.throws(()=>validateConsumerEvidenceEvent(validEvent({payload:{feature:'x',result:'success',clickstream:'x'}})),e=>e.code==='KNOWLEDGE_EVOLUTION_SCHEMA_INVALID'));
test('feedback free text redacts paths and email',()=>{const p=sanitizeConsumerEvidencePayload('user_feedback','P2',{feature:'ui',rating:2,category:'usability',comment:'C:\\Users\\alice\\video.mp4 alice@example.com'});assert.match(p.comment,/REDACTED_PATH/);assert.match(p.comment,/REDACTED_EMAIL/);});
test('batch rejects duplicate ids',()=>assert.throws(()=>validateConsumerEvidenceBatch({schema_version:'1.0',events:[validEvent(),validEvent()]}),e=>e.code==='CONSUMER_EVIDENCE_BATCH_DUPLICATE_EVENT_ID'));
test('client policy intersection cannot raise privacy',()=>{const p=intersectClientPolicies({max_privacy_level:'P0',enabled_features:['a','b'],max_batch_events:10,max_payload_bytes:5000,max_outbox_bytes:1000,policy_version:'L'},{max_privacy_level:'P2',enabled_features:['b','c'],max_batch_events:100,max_payload_bytes:10000,max_outbox_bytes:2000,policy_version:'S'});assert.equal(p.max_privacy_level,'P0');assert.deepEqual(p.enabled_features,['b']);assert.equal(p.max_batch_events,10);});
test('client policy rejects invalid sampling or oversized limits',()=>{assert.throws(()=>intersectClientPolicies({sampling:{diagnostic:1.1}},{}),e=>e.code==='CONSUMER_EVIDENCE_POLICY_INVALID');assert.throws(()=>intersectClientPolicies({max_batch_events:101},{}),e=>e.code==='CONSUMER_EVIDENCE_POLICY_INVALID');});
test('runtime event maps to Knowledge Evidence without raw payload',()=>{const e=mapConsumerEventToKnowledgeEvidence(validEvent());assert.equal(e.evidence_type,'success_pattern');assert.equal(e.producer.project_id,'bai-video-production');assert.ok(e.payload_hash.startsWith('sha256:'));assert.equal(Object.hasOwn(e,'payload'),false);});
test('client cannot self-declare trust because event schema is closed',()=>assert.throws(()=>validateConsumerEvidenceEvent({...validEvent(),trust_level:'TRUSTED_OS'}),e=>e.code==='KNOWLEDGE_EVOLUTION_SCHEMA_INVALID'));
