import assert from 'node:assert/strict';
import test from 'node:test';
import {assertConsumerEvidencePrivacySafe,computeConsumerEvidenceBatchSha256,intersectClientPolicies,mapConsumerBatchToKnowledgeEvidence,validateConsumerEvidenceBatch,validateConsumerEvidenceEvent,validateDeliveryReceipt,withConsumerEvidenceBatchSha256} from '../../src/knowledge-evolution/index.mjs';
import {validBatch,validEvent} from './helpers.mjs';

test('canonical pilot P0 event is normalized and catalog validated',()=>{const e=validateConsumerEvidenceEvent(validEvent());assert.equal(e.feature,'subtitle_import');assert.equal(e.occurred_at,'2026-08-11T00:00:00.000Z');assert.equal(e.properties.cue_count,42);});
test('P3 raw content is rejected',()=>assert.throws(()=>validateConsumerEvidenceEvent(validEvent({privacy_level:'P3'})),e=>e.code==='CONSUMER_EVIDENCE_PRIVACY_LEVEL_INVALID'));
test('unknown event field and unknown catalog property fail closed',()=>{assert.throws(()=>validateConsumerEvidenceEvent({...validEvent(),trust_level:'TRUSTED_OS'}),e=>e.code==='KNOWLEDGE_EVOLUTION_SCHEMA_INVALID');assert.throws(()=>validateConsumerEvidenceEvent({...validEvent(),properties:{cue_count:1,clickstream:2}}),e=>e.code==='CONSUMER_EVIDENCE_CATALOG_PROPERTY_FORBIDDEN');});
test('absolute path, email and secret-like values are rejected',()=>{assert.throws(()=>assertConsumerEvidencePrivacySafe({error:'C:\\Users\\alice\\video.mp4'}),e=>e.code==='CONSUMER_EVIDENCE_ABSOLUTE_PATH_FORBIDDEN');assert.throws(()=>assertConsumerEvidencePrivacySafe({error:'alice@example.com'}),e=>e.code==='CONSUMER_EVIDENCE_PERSONAL_DATA_FORBIDDEN');assert.throws(()=>assertConsumerEvidencePrivacySafe({contact:'090-1234-5678'}),e=>e.code==='CONSUMER_EVIDENCE_PERSONAL_DATA_FORBIDDEN');assert.doesNotThrow(()=>assertConsumerEvidencePrivacySafe({occurred_at:'2026-08-11T00:00:00.000Z'}));const secret='sk-'+'A'.repeat(24);assert.throws(()=>assertConsumerEvidencePrivacySafe({value:secret}),e=>e.code==='CONSUMER_EVIDENCE_SECRET_DETECTED'&&!String(e.message).includes(secret));});
test('pilot long job and review summary enforce property types',()=>{assert.equal(validateConsumerEvidenceEvent(validEvent({event_id:'evt-longjob-0002',type:'performance',feature:'long_running_job_result',properties:{chunk_count:8,resume_used:true,resumed_chunk_count:2}})).feature,'long_running_job_result');assert.throws(()=>validateConsumerEvidenceEvent(validEvent({type:'performance',feature:'long_running_job_result',properties:{chunk_count:-1,resume_used:true,resumed_chunk_count:0}})),e=>e.code==='CONSUMER_EVIDENCE_CATALOG_PROPERTY_INVALID');});
test('batch requires identity and rejects internal duplicate ids',()=>{const b=validateConsumerEvidenceBatch(validBatch());assert.equal(b.product.product_id,'bai-video-production');assert.throws(()=>validateConsumerEvidenceBatch(validBatch({events:[validEvent(),validEvent()]})),e=>e.code==='CONSUMER_EVIDENCE_BATCH_DUPLICATE_EVENT_ID');});
test('batch content hash is deterministic and mismatch rejected',()=>{const h=withConsumerEvidenceBatchSha256(validBatch());assert.equal(h.content_sha256,computeConsumerEvidenceBatchSha256(h));assert.throws(()=>validateConsumerEvidenceBatch({...h,content_sha256:'0'.repeat(64)}),e=>e.code==='CONSUMER_EVIDENCE_BATCH_HASH_MISMATCH');});
test('client policy intersection cannot raise privacy and preserves schema compatibility',()=>{const p=intersectClientPolicies({max_privacy_level:'P0',enabled_features:['subtitle_import'],max_batch_events:10,max_payload_bytes:5000,max_outbox_bytes:1000,policy_version:'L'},{max_privacy_level:'P2',enabled_features:['subtitle_import','x'],max_batch_events:100,max_payload_bytes:10000,max_outbox_bytes:2000,policy_version:'S'});assert.equal(p.max_privacy_level,'P0');assert.deepEqual(p.enabled_features,['subtitle_import']);assert.deepEqual(p.accepted_schema_versions,['1.0']);});
test('client policy rejects invalid sampling or oversized limits',()=>{assert.throws(()=>intersectClientPolicies({sampling:{diagnostic:1.1}},{}),e=>e.code==='CONSUMER_EVIDENCE_POLICY_INVALID');assert.throws(()=>intersectClientPolicies({max_batch_events:101},{}),e=>e.code==='CONSUMER_EVIDENCE_POLICY_INVALID');});
test('canonical batch maps to Knowledge Evidence without raw event body',()=>{const [e]=mapConsumerBatchToKnowledgeEvidence(validBatch());assert.equal(e.evidence_type,'success_pattern');assert.equal(e.producer.project_id,'bai-video-production');assert.ok(e.payload_hash.startsWith('sha256:'));assert.equal(Object.hasOwn(e,'payload'),false);});
test('receipt supports event-level partial rejection',()=>{const r=validateDeliveryReceipt({receipt_version:'1.0',receipt_id:'rcpt-12345678',batch_id:'batch-demo-12345678',accepted:['evt-subtitle-0001'],already_seen:[],rejected:[{event_id:'evt-longjob-0002',reason_code:'MOCK_REJECTED'}],server_time:'2026-08-11T00:20:00Z'});assert.equal(r.rejected[0].reason_code,'MOCK_REJECTED');});
test('legacy RC1 envelope can be read as compatibility input but normalizes to canonical event',()=>{const e=validateConsumerEvidenceEvent({schema_version:'1.0',event_id:'evt-legacy-1234',occurred_at:'2026-08-11T00:00:00Z',product:{product_id:'bai-video-production',product_version:'0.16.4'},installation_id:'inst-legacy-1234',event_type:'feature_result',privacy_level:'P0',payload:{feature:'subtitle_import',result:'success',duration_ms:1,retry_count:0}});assert.equal(e.type,'feature_result');assert.equal(e.feature,'subtitle_import');assert.equal(Object.hasOwn(e,'product'),false);});

test('event identity is unambiguous and Product ID is transport-safe',()=>{assert.throws(()=>validateConsumerEvidenceEvent({...validEvent(),operation:'also-present'}),e=>e.code==='CONSUMER_EVIDENCE_FEATURE_OPERATION_AMBIGUOUS');assert.throws(()=>validateConsumerEvidenceBatch(validBatch({product:{product_id:'../unsafe/product',product_version:'0.17.0'}})),e=>e.code==='KNOWLEDGE_EVOLUTION_ID_INVALID');});
test('receipt event outcomes are mutually exclusive',()=>{assert.throws(()=>validateDeliveryReceipt({receipt_version:'1.0',receipt_id:'rcpt-overlap-0001',batch_id:'batch-demo-12345678',accepted:['evt-subtitle-0001'],already_seen:['evt-subtitle-0001'],rejected:[],server_time:'2026-08-11T00:20:00Z'}),e=>e.code==='CONSUMER_EVIDENCE_RECEIPT_EVENT_OUTCOME_CONFLICT');});
test('client policy fails closed on Event Catalog version mismatch',()=>{assert.throws(()=>intersectClientPolicies({event_catalog_version:'1.0'},{event_catalog_version:'2.0'}),e=>e.code==='CONSUMER_EVIDENCE_POLICY_CATALOG_VERSION_MISMATCH');});
