import assert from 'node:assert/strict';import test from 'node:test';
import {createConsumerEvidenceMockHub} from '../../src/knowledge-evolution/index.mjs';import {validEvent} from './helpers.mjs';
async function withHub(scenario,fn){const h=createConsumerEvidenceMockHub({scenario});const s=await h.start();try{return await fn(s.base_url,h);}finally{await h.stop();}}
const headers={'authorization':'Bearer local-test-credential','content-type':'application/json'};
test('mock hub accepts valid batch',()=>withHub('accept',async base=>{const r=await fetch(base+'/v1/evidence/batch',{method:'POST',headers,body:JSON.stringify({schema_version:'1.0',events:[validEvent()]})});assert.equal(r.status,200);const body=await r.json();assert.deepEqual(body.accepted,['evt-12345678']);}));
test('mock hub duplicate is idempotent already_seen',()=>withHub('accept',async base=>{const body=JSON.stringify({schema_version:'1.0',events:[validEvent()]});await fetch(base+'/v1/evidence/batch',{method:'POST',headers,body});const r=await fetch(base+'/v1/evidence/batch',{method:'POST',headers,body});const x=await r.json();assert.deepEqual(x.already_seen,['evt-12345678']);assert.deepEqual(x.accepted,[]);}));
test('mock hub partial rejects last event',()=>withHub('partial',async base=>{const e2=validEvent({event_id:'evt-87654321'});const r=await fetch(base+'/v1/evidence/batch',{method:'POST',headers,body:JSON.stringify({schema_version:'1.0',events:[validEvent(),e2]})});const x=await r.json();assert.equal(x.accepted.length,1);assert.equal(x.rejected[0].event_id,'evt-87654321');}));
test('mock hub requires credential',()=>withHub('accept',async base=>{const r=await fetch(base+'/v1/client-policy');assert.equal(r.status,401);}));
test('mock hub rate limit emits Retry-After',()=>withHub('rate-limit',async base=>{const r=await fetch(base+'/v1/client-policy',{headers:{authorization:'Bearer x'}});assert.equal(r.status,429);assert.equal(r.headers.get('retry-after'),'1');}));
test('mock hub server error is non-success',()=>withHub('server-error',async base=>{const r=await fetch(base+'/v1/client-policy',{headers:{authorization:'Bearer x'}});assert.equal(r.status,500);}));
test('mock hub rejects P3 batch at server validator',()=>withHub('accept',async base=>{const r=await fetch(base+'/v1/evidence/batch',{method:'POST',headers,body:JSON.stringify({schema_version:'1.0',events:[validEvent({privacy_level:'P3'})]})});assert.equal(r.status,400);}));
