import assert from 'node:assert/strict';import test from 'node:test';
import {createConsumerEvidenceMockHub} from '../../src/knowledge-evolution/index.mjs';import {validBatch,validEvent} from './helpers.mjs';
async function withHub(scenario,fn){const h=createConsumerEvidenceMockHub({scenario});const s=await h.start();try{return await fn(s.base_url,h);}finally{await h.stop();}}
const headers={'authorization':'Bearer local-test-credential','content-type':'application/json'};
test('mock hub accepts canonical batch with receipt binding',()=>withHub('accept',async base=>{const b=validBatch();const r=await fetch(base+'/v1/evidence/batch',{method:'POST',headers,body:JSON.stringify(b)});assert.equal(r.status,200);const x=await r.json();assert.equal(x.batch_id,b.batch_id);assert.equal(x.receipt_version,'1.0');assert.deepEqual(x.accepted,['evt-subtitle-0001']);}));
test('mock hub duplicate resend is event-id idempotent',()=>withHub('accept',async base=>{const body=JSON.stringify(validBatch());await fetch(base+'/v1/evidence/batch',{method:'POST',headers,body});const r=await fetch(base+'/v1/evidence/batch',{method:'POST',headers,body});const x=await r.json();assert.deepEqual(x.already_seen,['evt-subtitle-0001']);assert.deepEqual(x.accepted,[]);}));
test('mock hub partial rejects last event with machine reason',()=>withHub('partial',async base=>{const b=validBatch({batch_id:'batch-partial-1234',events:[validEvent(),validEvent({event_id:'evt-subtitle-0002'})]});const r=await fetch(base+'/v1/evidence/batch',{method:'POST',headers,body:JSON.stringify(b)});const x=await r.json();assert.equal(x.accepted.length,1);assert.equal(x.rejected[0].event_id,'evt-subtitle-0002');assert.equal(x.rejected[0].reason_code,'MOCK_REJECTED');}));
test('mock hub requires credential',()=>withHub('accept',async base=>{const r=await fetch(base+'/v1/client-policy');assert.equal(r.status,401);}));
test('mock hub rate limit emits Retry-After',()=>withHub('rate-limit',async base=>{const r=await fetch(base+'/v1/client-policy',{headers:{authorization:'Bearer x'}});assert.equal(r.status,429);assert.equal(r.headers.get('retry-after'),'1');}));
test('mock hub server error is non-success',()=>withHub('server-error',async base=>{const r=await fetch(base+'/v1/client-policy',{headers:{authorization:'Bearer x'}});assert.equal(r.status,500);}));
test('mock hub rejects P3 batch at server validator',()=>withHub('accept',async base=>{const b=validBatch({events:[validEvent({privacy_level:'P3'})]});const r=await fetch(base+'/v1/evidence/batch',{method:'POST',headers,body:JSON.stringify(b)});assert.equal(r.status,400);}));
