import assert from 'node:assert/strict';
import test from 'node:test';
import {spawnSync} from 'node:child_process';
import path from 'node:path';
const root=path.resolve('templates/consumer-evidence/python');
function run(code){return spawnSync('python',['-c',code],{env:{...process.env,PYTHONPATH:root},encoding:'utf8'});}
test('Product-owned Python reference fails closed on ambiguous Event, catalog privacy, unsafe object key and policy version mismatch',()=>{const r=run(`from bai_consumer_evidence.sanitizer import sanitize_event\nfrom bai_consumer_evidence.artifact import object_key\nfrom bai_consumer_evidence.policy import ClientPolicy,intersect_policy\nchecks=[]\nbase={'event_id':'evt-12345678','occurred_at':'2026-08-11T00:00:00Z','type':'feature_result','feature':'subtitle_import','result':'success','privacy_level':'P0','properties':{'cue_count':1}}\nfor fn in [lambda:sanitize_event({**base,'operation':'also'}),lambda:sanitize_event({**base,'privacy_level':'P2'}),lambda:object_key({'created_at':'2026-08-11T00:00:00Z','product':{'product_id':'../bad'},'installation':{'installation_id':'inst-12345678'},'batch_id':'batch-12345678'}),lambda:intersect_policy(ClientPolicy(event_catalog_version='1.0'),ClientPolicy(event_catalog_version='2.0'))]:\n try: fn(); checks.append(False)\n except ValueError: checks.append(True)\nassert all(checks)\n`);assert.equal(r.status,0,r.stderr);});
test('Product-owned Python receipt validator binds batch and Event IDs before ack',()=>{const r=run(`from bai_consumer_evidence.client import _acknowledged_event_ids\nb={'batch_id':'batch-12345678','events':[{'event_id':'evt-12345678'}]}\ngood={'receipt_version':'1.0','batch_id':'batch-12345678','accepted':['evt-12345678'],'already_seen':[],'rejected':[]}\nassert _acknowledged_event_ids(good,b)==['evt-12345678']\nfor bad in [{**good,'batch_id':'other-12345678'},{**good,'accepted':['evt-unknown-1234']},{**good,'already_seen':['evt-12345678']}]:\n try: _acknowledged_event_ids(bad,b); raise AssertionError('expected fail')\n except ValueError: pass\n`);assert.equal(r.status,0,r.stderr);});

test('Product-owned Python presigned Object Storage uploader is credential-free, redirect-safe and does not acknowledge Outbox Events',()=>{const r=run(`import json,tempfile,threading\nfrom http.server import BaseHTTPRequestHandler,HTTPServer\nfrom bai_consumer_evidence import EvidenceClient,LocalOutbox\nclass Cred:\n def is_configured(self): return False\n def get_secret(self): return None\nclass H(BaseHTTPRequestHandler):\n body=b''; auth=None; digest=None; requests=0\n def do_PUT(self):\n  H.requests+=1; H.auth=self.headers.get('Authorization');H.digest=self.headers.get('X-Content-SHA256');H.body=self.rfile.read(int(self.headers.get('Content-Length','0')));self.send_response(204);self.end_headers()\n def log_message(self,*a): pass\ns=HTTPServer(('127.0.0.1',0),H);threading.Thread(target=s.serve_forever,daemon=True).start()\nwith tempfile.TemporaryDirectory() as d:\n out=LocalOutbox(d);c=EvidenceClient('http://unused','bai-video-production','0.17.0','inst-demo-12345678',Cred(),out)\n q=c.record_event('feature_result','subtitle_import','success',properties={'cue_count':2},event_id='evt-demo-12345678');assert q['status']=='queued'\n url=f'http://127.0.0.1:{s.server_port}/signed?opaque=1'\n x=c.flush_to_object_storage(lambda meta:{'url':url,'headers':{'X-Demo-Signed':'yes'}},allow_insecure_loopback=True)\n assert x['status']=='stored' and x['stored'] is True and x['event_ids']==['evt-demo-12345678']\n assert H.requests==1 and H.auth is None and H.digest==x['content_sha256']\n body=json.loads(H.body.decode());assert body['events'][0]['event_id']=='evt-demo-12345678' and body['content_sha256']==x['content_sha256']\n assert [e['event_id'] for e in out.list_events()]==['evt-demo-12345678']\ns.shutdown();s.server_close()\n`);assert.equal(r.status,0,r.stderr);});

test('Product-owned Python presigned uploader rejects redirect, remote plaintext URL and credential-bearing headers',()=>{const r=run(`import threading\nfrom http.server import BaseHTTPRequestHandler,HTTPServer\nfrom bai_consumer_evidence.artifact import build_artifact\nfrom bai_consumer_evidence.object_storage import upload_artifact_presigned,validate_presigned_url\nb={'schema_version':'1.0','batch_id':'batch-demo-12345678','created_at':'2026-08-11T00:00:00Z','product':{'product_id':'bai-video-production','product_version':'0.17.0'},'installation':{'installation_id':'inst-demo-12345678'},'events':[]}\na=build_artifact(b)\ntry: validate_presigned_url('http://example.com/x');raise AssertionError('expected HTTPS rejection')\nexcept ValueError: pass\nclass R(BaseHTTPRequestHandler):\n def do_PUT(self): self.send_response(307);self.send_header('Location',f'http://127.0.0.1:{self.server.server_port}/other');self.end_headers()\n def log_message(self,*a): pass\ns=HTTPServer(('127.0.0.1',0),R);threading.Thread(target=s.serve_forever,daemon=True).start();u=f'http://127.0.0.1:{s.server_port}/signed'\nr=upload_artifact_presigned(u,a,allow_insecure_loopback=True);assert r['status']=='http_307' and r['stored'] is False\nr=upload_artifact_presigned(u,a,headers={'Authorization':'Bearer must-not-be-sent'},allow_insecure_loopback=True);assert r['status']=='delivery_unavailable' and r['stored'] is False\ns.shutdown();s.server_close()\n`);assert.equal(r.status,0,r.stderr);});
