import assert from 'node:assert/strict';
import test from 'node:test';
import {mkdtemp,readFile,rm} from 'node:fs/promises';
import os from 'node:os';import path from 'node:path';
import {createKnowledgeIntakePackageFromRepositorySnapshot,validateRepositorySnapshotReference} from '../../src/knowledge-evolution/index.mjs';
const snapshot=()=>({schema_version:'1.0',snapshot_id:'snap-bvp-github-20260811',observed_at:'2026-08-10T23:33:00Z',vcs:'git',repository_url:'https://github.com/baisound/bai_video_production',ref:'main',commit_sha:'a098f881b095e3290d2562efe3846d9e2384806a',tree_sha:'59d7dd9a233570e3e3616face417a6925307492b',development_os:{version:'1.0.0',architecture:'2.28',commit:null},consumer:{project_id:'bai-video-production',task_id:'TASK-006',version:'0.16.4',commit:'a098f881b095e3290d2562efe3846d9e2384806a'},validation:{tree_identity_verified:true,content_scan_status:'KEY_FILES_ONLY',key_files:[{path:'PROJECT.md',blob_id:'d903745bd052f1f31168f4d1c47ea881bf823e60',size_bytes:11066},{path:'.bai-os/project.json',blob_id:'3c7e972596c927476cd1d301818c18ad9cf5bed2',size_bytes:1022}]},notes:'GitHub canonical tracked snapshot; key files fetched explicitly.'});
test('repository snapshot reference preserves immutable Git identity without copying raw repository',()=>{const s=validateRepositorySnapshotReference(snapshot());assert.equal(s.commit_sha,s.consumer.commit);assert.equal(s.validation.content_scan_status,'KEY_FILES_ONLY');});
test('repository snapshot rejects credential URL, unsafe key path and commit mismatch',()=>{assert.throws(()=>validateRepositorySnapshotReference({...snapshot(),repository_url:'https://token@example.com/repo'}),e=>e.code==='KNOWLEDGE_REPOSITORY_SNAPSHOT_URL_INVALID');assert.throws(()=>validateRepositorySnapshotReference({...snapshot(),validation:{...snapshot().validation,key_files:[{path:'../secret.txt'}]}}),e=>e.code==='KNOWLEDGE_SNAPSHOT_PATH_ESCAPE');assert.throws(()=>validateRepositorySnapshotReference({...snapshot(),consumer:{...snapshot().consumer,commit:'0'.repeat(40)}}),e=>e.code==='KNOWLEDGE_REPOSITORY_SNAPSHOT_CONSUMER_COMMIT_MISMATCH');});
test('repository snapshot intake emits provenance/evidence/candidate package and no raw source tree',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'bai-repo-intake-'));try{const out=path.join(root,'intake');await createKnowledgeIntakePackageFromRepositorySnapshot({repositorySnapshot:snapshot(),outputRoot:out,clock:()=>new Date('2026-08-10T23:33:00Z'),evidence:[{schema_version:'1.0',evidence_id:'EV-BVP-GITHUB-RUNTIME-001',evidence_type:'architecture_decision',producer:{project_id:'bai-video-production',task_id:'TASK-006',product_version:'0.16.4'},observation:'Product runtime is independent from Development OS.',resolution:'Preserve standalone boundary.',outcome:'accepted_product_invariant',candidate_scope:'product-family',provenance:{completeness:'PARTIAL',source_commit:snapshot().commit_sha,architecture_version:'2.28',snapshot_sha256:null,observed_at:'2026-08-10T23:33:00Z'},sensitivity:'PUBLIC',payload_hash:null,processing_status:'CANDIDATE_CREATED'}],candidates:[{schema_version:'1.0',candidate_id:'KC-BVP-GITHUB-RUNTIME-001',source_evidence_ids:['EV-BVP-GITHUB-RUNTIME-001'],status:'SUPPORTED',scope:'product-family',risk:'HIGH',title:'Standalone Consumer runtime',statement:'Consumer runtime remains independent from Development OS.',rationale:'GitHub canonical Product source confirms the boundary.',supersedes:null,required_review:'CRITIC_AND_JUDGE'}]});const m=JSON.parse(await readFile(path.join(out,'manifest.json'),'utf8'));assert.equal(m.source.kind,'git-repository-reference');assert.equal(m.source.raw_source_committed,false);await assert.rejects(readFile(path.join(out,'PROJECT.md'),'utf8'));}finally{await rm(root,{recursive:true,force:true});}});
