import assert from 'node:assert/strict';import test from 'node:test';import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {inspectKnowledgeSnapshot} from '../../src/knowledge-evolution/index.mjs';import {writeStoredZip} from './helpers.mjs';
const tmp=()=>mkdtemp(path.join(os.tmpdir(),'bai-ke-snapshot-'));

test('ZIP snapshot recovers complete manifest and inventory',async()=>{const root=await tmp();try{const zip=path.join(root,'s.zip');await writeStoredZip(zip,[{name:'bundle/snapshot-manifest.json',data:JSON.stringify({schema_version:'1.0',snapshot_id:'snap-12345678',created_at:'2026-08-11T00:00:00Z',development_os:{version:'1.0.0',architecture:'2.28',commit:'abc'},consumer:{project_id:'bai-video-production',task_id:'TASK-006',version:'0.17.0',commit:'def'}})},{name:'bundle/PROJECT.md',data:'# Product'}]);const r=await inspectKnowledgeSnapshot(zip);assert.equal(r.state,'PROVENANCE_RECOVERED');assert.equal(r.provenance.completeness,'COMPLETE');assert.equal(r.provenance.consumer.project_id,'bai-video-production');assert.ok(r.provenance.snapshot_sha256.startsWith('sha256:'));}finally{await rm(root,{recursive:true,force:true});}});
test('manifestless directory recovers PARTIAL provenance',async()=>{const root=await tmp();try{await mkdir(path.join(root,'.bai-os'),{recursive:true});await writeFile(path.join(root,'.bai-os','project.json'),JSON.stringify({project_id:'bai-video-production'}));await writeFile(path.join(root,'PROJECT.md'),'# BAI\n\nActive Task: `TASK-006`\nPackage: `0.17.0`\n');const r=await inspectKnowledgeSnapshot(root);assert.equal(r.provenance.completeness,'PARTIAL');assert.equal(r.provenance.consumer.project_id,'bai-video-production');assert.equal(r.provenance.consumer.task_id,'TASK-006');}finally{await rm(root,{recursive:true,force:true});}});
test('ZIP path traversal is rejected before extraction',async()=>{const root=await tmp();try{const zip=path.join(root,'evil.zip');await writeStoredZip(zip,[{name:'../escape.txt',data:'x'}]);await assert.rejects(inspectKnowledgeSnapshot(zip),e=>e.code==='KNOWLEDGE_SNAPSHOT_PATH_ESCAPE');}finally{await rm(root,{recursive:true,force:true});}});
test('ZIP symlink is rejected',async()=>{const root=await tmp();try{const zip=path.join(root,'link.zip');await writeStoredZip(zip,[{name:'link',data:'../../x',symlink:true}]);await assert.rejects(inspectKnowledgeSnapshot(zip),e=>e.code==='KNOWLEDGE_SNAPSHOT_SYMLINK_UNSUPPORTED');}finally{await rm(root,{recursive:true,force:true});}});
test('secret-bearing source is quarantined without secret value in report',async()=>{const root=await tmp();try{await writeFile(path.join(root,'.env'),'API_KEY=super-secret-value\n');const r=await inspectKnowledgeSnapshot(root);assert.equal(r.state,'QUARANTINED');assert.ok(r.issues.some(x=>x.rule_id==='SECRET_BEARING_PATH'));assert.equal(JSON.stringify(r).includes('super-secret-value'),false);}finally{await rm(root,{recursive:true,force:true});}});
