export const KNOWLEDGE_TYPES = Object.freeze([
  'PRINCIPLE','GOOD_PRACTICE','PROHIBITION','SUCCESS_CASE','FAILURE_CASE','LESSON_LEARNED',
  'ADR','PROCEDURE','TEMPLATE','QUALITY_CRITERION','TROUBLESHOOTING'
]);
export const ASSET_STATUSES = Object.freeze(['CANDIDATE','DRAFT','UNDER_REVIEW','ACTIVE','STALE','DEPRECATED','INVALID','ARCHIVED']);
export const MATURITY_STAGES = Object.freeze(['EXPERIENCE','OBSERVATION','IDEA','KNOWLEDGE_ASSET','FRAMEWORK','STANDARD','ORGANIZATION_STANDARD']);
export const ENFORCEMENT_LEVELS = Object.freeze(['MANDATORY','CONDITIONAL_MANDATORY','ADVISORY','REFERENCE']);
export const SCOPE_LEVELS = Object.freeze(['GLOBAL','DOMAIN','TECHNOLOGY','SPECIALIZATION','TOOL','PROJECT','TASK']);
export const SOURCE_TRUST_LEVELS = Object.freeze(['CANONICAL','OFFICIAL','VERIFIED_INTERNAL','USER_OBSERVED','EXTERNAL_REFERENCE','AI_INFERRED','UNTRUSTED']);
export const SENSITIVITY_LEVELS = Object.freeze(['PUBLIC','INTERNAL','CONFIDENTIAL','RESTRICTED']);
export const RELATION_TYPES = Object.freeze(['REQUIRES','EXCEPTION','CONFLICT','SUPERSEDES','DERIVED_FROM','RELATED_TO']);
export const USAGE_ACTIONS = Object.freeze(['APPLIED','DEVIATED','NOT_APPLICABLE']);
export const VERIFICATION_RESULTS = Object.freeze(['PASS','FAIL','NOT_RUN']);
export const PATTERN_KINDS = Object.freeze(['PATTERN','ANTI_PATTERN']);
export const DECISION_STATUSES = Object.freeze(['PROPOSED','ACCEPTED','SUPERSEDED','REJECTED']);
export const TRUST_RANK = Object.freeze({UNTRUSTED:0,AI_INFERRED:1,EXTERNAL_REFERENCE:2,USER_OBSERVED:3,VERIFIED_INTERNAL:4,OFFICIAL:5,CANONICAL:6});
export const SENSITIVITY_RANK = Object.freeze({PUBLIC:0,INTERNAL:1,CONFIDENTIAL:2,RESTRICTED:3});
export const SCOPE_SPECIFICITY = Object.freeze({GLOBAL:0,DOMAIN:1,TECHNOLOGY:2,SPECIALIZATION:3,TOOL:4,PROJECT:5,TASK:6});
export const ENFORCEMENT_RANK = Object.freeze({REFERENCE:1,ADVISORY:2,CONDITIONAL_MANDATORY:3,MANDATORY:4});
