import { mkdir, open, readFile, readdir, realpath, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { KnowledgeError } from './errors.mjs';
import { assertRealContained, checksumObject, confinePath, deepFreeze, safeId, sha256 } from './util.mjs';

async function withLedgerLock(root, fn) {
  await mkdir(root,{recursive:true}); await assertRealContained(root,root); const lock=confinePath(root,'.knowledge-ledger.lock'); let h;
  try { h=await open(lock,'wx'); } catch(e) { if(e.code==='EEXIST') throw new KnowledgeError('KNOWLEDGE_LEDGER_BUSY'); throw e; }
  try { return await fn(); } finally { await h.close(); await rm(lock,{force:true}); }
}
async function appendHashRecord(file,record){let rows=[];try{const t=await readFile(file,'utf8');if(t.trim())rows=t.trim().split('\n').map(JSON.parse);}catch(e){if(e.code!=='ENOENT')throw e;}const prev=rows.at(-1);const base={seq:(prev?.seq??0)+1,...record,previous_hash:prev?.record_hash??null};base.record_hash=`sha256:${sha256(base)}`;await writeFile(file,`${JSON.stringify(base)}\n`,{encoding:'utf8',flag:'a'});return base;}
async function verifyHashFile(file){let rows=[];try{const t=await readFile(file,'utf8');if(t.trim())rows=t.trim().split('\n').map(JSON.parse);}catch(e){if(e.code==='ENOENT')return [];throw e;}let prev=null;for(let i=0;i<rows.length;i++){const r=rows[i];if(r.seq!==i+1||r.previous_hash!==(prev?.record_hash??null))throw new KnowledgeError('KNOWLEDGE_LEDGER_CHAIN_INVALID');const c={...r};delete c.record_hash;if(r.record_hash!==`sha256:${sha256(c)}`)throw new KnowledgeError('KNOWLEDGE_LEDGER_CHAIN_INVALID');prev=r;}return rows;}
export async function appendKnowledgeUsageEvent(root,event){return withLedgerLock(path.resolve(root),async()=>{const file=confinePath(root,'usage-log.jsonl');await mkdir(path.dirname(file),{recursive:true});await assertRealContained(root,path.dirname(file));await assertRealContained(root,file,{allowMissing:true});const payload=structuredClone(event);return deepFreeze(await appendHashRecord(file,{record_type:'USAGE_EVENT',payload,payload_checksum:checksumObject(payload)}));});}
export async function listKnowledgeUsageEvents(root){const file=confinePath(root,'usage-log.jsonl');await assertRealContained(root,file,{allowMissing:true});const rows=await verifyHashFile(file);return rows.map(r=>r.payload);}
export async function verifyKnowledgeUsageLedger(root){const file=confinePath(root,'usage-log.jsonl');await assertRealContained(root,file,{allowMissing:true});const rows=await verifyHashFile(file);for(const r of rows)if(r.payload_checksum!==checksumObject(r.payload))throw new KnowledgeError('KNOWLEDGE_LEDGER_PAYLOAD_INVALID');return deepFreeze({result:'KNOWLEDGE_USAGE_LEDGER_VERIFIED',event_count:rows.length,last_hash:rows.at(-1)?.record_hash??null});}
export async function saveKnowledgePackArtifact(root,pack){safeId(pack.pack_id,'pack_id');if(pack.checksum!==checksumObject(pack))throw new KnowledgeError('KNOWLEDGE_PACK_CHECKSUM_MISMATCH');const dir=confinePath(root,'packs');await mkdir(dir,{recursive:true});await assertRealContained(root,dir);const target=confinePath(dir,`${pack.pack_id}.json`);await assertRealContained(root,target,{allowMissing:true});let h;try{h=await open(target,'wx');await h.writeFile(`${JSON.stringify(pack,null,2)}\n`);}catch(e){if(e.code==='EEXIST')throw new KnowledgeError('KNOWLEDGE_PACK_ALREADY_EXISTS');throw e;}finally{await h?.close();}return deepFreeze({result:'KNOWLEDGE_PACK_PERSISTED',pack_id:pack.pack_id,path:target});}
export async function loadKnowledgePackArtifact(root,packId){const target=confinePath(root,'packs',`${safeId(packId,'pack_id')}.json`);const base=await realpath(root);const actual=await realpath(target);if(actual!==base&&!actual.startsWith(base+path.sep))throw new KnowledgeError('KNOWLEDGE_PATH_ESCAPE');const p=JSON.parse(await readFile(target,'utf8'));if(p.checksum!==checksumObject(p))throw new KnowledgeError('KNOWLEDGE_PACK_CHECKSUM_MISMATCH');return deepFreeze(p);}
export async function listKnowledgePackArtifacts(root){const dir=confinePath(root,'packs');let entries;try{await assertRealContained(root,dir);entries=await readdir(dir,{withFileTypes:true});}catch(e){if(e.code==='ENOENT')return [];throw e;}const packs=[];for(const e of entries.filter(x=>x.isFile()&&x.name.endsWith('.json')).sort((a,b)=>a.name.localeCompare(b.name))){packs.push(await loadKnowledgePackArtifact(root,e.name.slice(0,-5)));}return packs;}
