import { mkdir, readFile, readdir, rm, stat, writeFile, open, realpath } from 'node:fs/promises';
import path from 'node:path';
import { KnowledgeError } from './errors.mjs';
import { validateKnowledgeAsset } from './asset.mjs';
import { assertRealContained, confinePath, deepFreeze, nowIso, safeId, sha256 } from './util.mjs';
import { prepareJournalTransaction, commitJournalTransaction, listJournalTransactions } from '../security/journal.mjs';

const LOCK='.knowledge-repository.lock';
const assetDir=(root,id)=>confinePath(root,'assets',safeId(id,'asset_id'));
async function withLock(root,fn){await mkdir(root,{recursive:true});const lp=confinePath(root,LOCK);let h;try{h=await open(lp,'wx');}catch(e){if(e.code==='EEXIST')throw new KnowledgeError('KNOWLEDGE_REPOSITORY_BUSY');throw e;}try{return await fn();}finally{await h.close();await rm(lp,{force:true});}}
export async function initializeKnowledgeRepository(root){const base=path.resolve(root);await mkdir(base,{recursive:true});await assertRealContained(base,base);const assets=confinePath(base,'assets');await mkdir(assets,{recursive:true});await assertRealContained(base,assets);const ev=confinePath(base,'event-log.jsonl');try{await stat(ev);await assertRealContained(base,ev);}catch(e){if(e.code!=='ENOENT')throw e;await assertRealContained(base,ev,{allowMissing:true});await writeFile(ev,'','utf8');await assertRealContained(base,ev);}return deepFreeze({root:base});}
async function readEvents(root){const file=confinePath(root,'event-log.jsonl');await assertRealContained(root,file);const t=await readFile(file,'utf8').catch(e=>e.code==='ENOENT'?'':Promise.reject(e));return t.trim()?t.trim().split('\n').map(l=>JSON.parse(l)):[];}
export async function loadCurrentKnowledgeAsset(root,id){const safe=safeId(id,'asset_id');const dir=assetDir(root,safe);await assertRealContained(root,dir);const pointerPath=confinePath(dir,'current.json');await assertRealContained(root,pointerPath);const pointer=JSON.parse(await readFile(pointerPath,'utf8'));if(pointer.asset_id!==safe||!Number.isSafeInteger(pointer.revision)||pointer.revision<1)throw new KnowledgeError('KNOWLEDGE_CURRENT_POINTER_INVALID');const revisionPath=confinePath(dir,'revisions',`${String(pointer.revision).padStart(6,'0')}.json`);await assertRealContained(root,revisionPath);const asset=validateKnowledgeAsset(JSON.parse(await readFile(revisionPath,'utf8')),{verifyChecksum:true});if(pointer.checksum!==asset.checksum||pointer.revision!==asset.revision)throw new KnowledgeError('KNOWLEDGE_CURRENT_POINTER_INVALID');return asset;}
export async function listCurrentKnowledgeAssets(root){await initializeKnowledgeRepository(root);const dirs=await readdir(confinePath(root,'assets'),{withFileTypes:true});const out=[];for(const d of dirs.filter(d=>d.isDirectory()).sort((a,b)=>a.name.localeCompare(b.name)))out.push(await loadCurrentKnowledgeAsset(root,d.name));return out;}
export async function saveKnowledgeAssetRevision(root,asset,{actor='system',authority=null,event_type,governance_decision=null,import_authorized=false}={}){const a=validateKnowledgeAsset(asset,{verifyChecksum:Boolean(asset.checksum)});return withLock(path.resolve(root),async()=>{await initializeKnowledgeRepository(root);let current=null;try{current=await loadCurrentKnowledgeAsset(root,a.asset_id);}catch(e){if(e.code!=='ENOENT')throw e;}
    if(!current&&a.revision!==1)throw new KnowledgeError('KNOWLEDGE_REVISION_SEQUENCE');if(current&&a.revision!==current.revision+1)throw new KnowledgeError('KNOWLEDGE_REVISION_SEQUENCE');
    if(!current&&!['CANDIDATE','DRAFT'].includes(a.status)&&!import_authorized)throw new KnowledgeError('KNOWLEDGE_GOVERNANCE_BYPASS_FORBIDDEN','new active/non-draft asset requires authorized import');
    if(current&&a.status!==current.status){const d=governance_decision;if(!d?.authorized||d.asset_id!==a.asset_id||d.from_status!==current.status||d.target_status!==a.status)throw new KnowledgeError('KNOWLEDGE_GOVERNANCE_BYPASS_FORBIDDEN','status change requires matching governance decision');}
    const dir=assetDir(root,a.asset_id);const revisionPath=confinePath(dir,'revisions',`${String(a.revision).padStart(6,'0')}.json`);await mkdir(path.dirname(revisionPath),{recursive:true});await assertRealContained(root,dir);await assertRealContained(root,path.dirname(revisionPath));await assertRealContained(root,revisionPath,{allowMissing:true});
    const pointer={asset_id:a.asset_id,revision:a.revision,checksum:a.checksum,revision_path:path.relative(root,revisionPath).split(path.sep).join('/'),updated_at:a.updated_at};
    const events=await readEvents(root);const prev=events.at(-1);const ev={seq:(prev?.seq??0)+1,timestamp:a.updated_at??nowIso(),event_type:event_type??(a.revision===1?'ASSET_CREATED':'ASSET_REVISED'),asset_id:a.asset_id,revision:a.revision,actor,authority:authority??null,previous_hash:prev?.event_hash??null,payload_hash:a.checksum};ev.event_hash=`sha256:${sha256(ev)}`;
    const txId=`KN-${a.asset_id}-${String(a.revision).padStart(6,'0')}`;
    await prepareJournalTransaction(root,{tx_id:txId,operations:[
      {path:path.relative(root,revisionPath).split(path.sep).join('/'),data:`${JSON.stringify(a,null,2)}\n`,mode:'CREATE'},
      {path:path.relative(root,confinePath(dir,'current.json')).split(path.sep).join('/'),data:`${JSON.stringify(pointer,null,2)}\n`,mode:'REPLACE'},
      {path:'event-log.jsonl',data:`${events.map(e=>JSON.stringify(e)).join('\n')}${events.length?'\n':''}${JSON.stringify(ev)}\n`,mode:'REPLACE'}
    ]});
    await commitJournalTransaction(root,txId);return a;});}
export async function verifyKnowledgeRepository(root){await initializeKnowledgeRepository(root);const pending=(await listJournalTransactions(root)).filter(x=>['PREPARED','COMMITTING'].includes(x.state));if(pending.length)throw new KnowledgeError('KNOWLEDGE_RECOVERY_REQUIRED','pending security journal',{transactions:pending.map(x=>x.tx_id)});const base=await realpath(root);const assets=await listCurrentKnowledgeAssets(root);for(const a of assets){const dir=await realpath(assetDir(root,a.asset_id));if(dir!==base&&!dir.startsWith(base+path.sep))throw new KnowledgeError('KNOWLEDGE_PATH_ESCAPE');}
  const events=await readEvents(root);let prev=null;for(let i=0;i<events.length;i++){const e=events[i];if(e.seq!==i+1||e.previous_hash!==(prev?.event_hash??null))throw new KnowledgeError('KNOWLEDGE_EVENT_CHAIN_INVALID');const copy={...e};delete copy.event_hash;const expected=`sha256:${sha256(copy)}`;if(e.event_hash!==expected)throw new KnowledgeError('KNOWLEDGE_EVENT_CHAIN_INVALID');prev=e;}
  const latest=new Map();for(const e of events)latest.set(e.asset_id,e);for(const a of assets){const e=latest.get(a.asset_id);if(!e||e.revision!==a.revision||e.payload_hash!==a.checksum)throw new KnowledgeError('KNOWLEDGE_REPOSITORY_CURRENT_EVENT_MISMATCH',a.asset_id);}
  return deepFreeze({result:'KNOWLEDGE_REPOSITORY_VERIFIED',asset_count:assets.length,event_count:events.length,last_event_hash:prev?.event_hash??null});}
