import { ReleaseError } from './errors.mjs';
import { satisfiesBounds, compareSemver, parseSemver } from './semver.mjs';
import { deepFreeze } from './util.mjs';
export function evaluateCompatibility(releaseManifest,consumer={}){
  const issues=[]; const warnings=[]; const c=releaseManifest.compatibility??{};
  if(c.consumer_adapter && consumer.consumer_adapter_version && !satisfiesBounds(consumer.consumer_adapter_version,{min:c.consumer_adapter.min,max:c.consumer_adapter.max})) issues.push({code:'CONSUMER_ADAPTER_INCOMPATIBLE'});
  if(c.node && consumer.node_version && !satisfiesBounds(consumer.node_version,{min:c.node.min,max:c.node.max})) issues.push({code:'NODE_INCOMPATIBLE'});
  for(const [component,target] of Object.entries(releaseManifest.schemas??{})){ const current=consumer.schemas?.[component]; if(!current){ warnings.push({code:'SCHEMA_CURRENT_UNKNOWN',component,target}); continue; } try{parseSemver(current);parseSemver(target);}catch{issues.push({code:'SCHEMA_VERSION_INVALID',component});continue;} if(compareSemver(current,target)!==0){ const hasMigration=(releaseManifest.migrations??[]).some(m=>m.component===component&&m.from_version===current&&m.to_version===target); if(!hasMigration) issues.push({code:'SCHEMA_MIGRATION_MISSING',component,from:current,to:target}); else warnings.push({code:'SCHEMA_MIGRATION_REQUIRED',component,from:current,to:target}); }}
  const required=releaseManifest.security_profile??{}; const currentSecurity=consumer.security_profile??{}; for(const [key,value] of Object.entries(required)){ if(value===true&&currentSecurity[key]!==true) warnings.push({code:'SECURITY_PROFILE_WILL_TIGHTEN',key}); if(value===false&&currentSecurity[key]===true) issues.push({code:'SECURITY_PROFILE_WEAKENING',key}); }
  return deepFreeze({compatible:issues.length===0,issues,warnings});
}
export function assertCompatible(manifest,consumer){ const r=evaluateCompatibility(manifest,consumer); if(!r.compatible) throw new ReleaseError('RELEASE_COMPATIBILITY_BLOCKED','compatibility blocked',r); return r; }
export function detectBreakingChanges(currentManifest,nextManifest){ const changes=[]; if(!currentManifest)return deepFreeze(changes); for(const [k,v] of Object.entries(nextManifest.schemas??{})){ const before=currentManifest.schemas?.[k]; if(before&&before!==v) changes.push({type:'SCHEMA_CHANGE',component:k,from:before,to:v}); } const a=currentManifest.compatibility??{},b=nextManifest.compatibility??{}; if(JSON.stringify(a)!==JSON.stringify(b)) changes.push({type:'COMPATIBILITY_CONTRACT_CHANGE'}); const spA=currentManifest.security_profile??{},spB=nextManifest.security_profile??{}; for(const k of new Set([...Object.keys(spA),...Object.keys(spB)])){ if(spA[k]===true&&spB[k]===false) changes.push({type:'SECURITY_WEAKENING',key:k}); } return deepFreeze(changes); }
