import { signEnvelopeWithProvider, verifySignedEnvelope } from '../security/signing.mjs';
import { normalizeRelativePath } from '../security/path.mjs';
import { ReleaseError } from './errors.mjs';
import { compareSemver, parseSemver } from './semver.mjs';
import { deepFreeze, nowIso, requireString, sha256, stable } from './util.mjs';
function uniqBy(items,key){ const seen=new Set(); for(const x of items){const v=x[key];if(seen.has(v))throw new ReleaseError('RELEASE_MANIFEST_DUPLICATE',`${key}:${v}`);seen.add(v);} }
export function createReleaseManifest({os_version,channel='stable',artifacts=[],schemas={},compatibility={},migrations=[],security_profile={},sbom=null,dependency_inventory=null,rollback_target=null,release_notes='',clock=()=>new Date()}={}){
  parseSemver(os_version); if(!['stable','candidate','canary'].includes(channel)) throw new ReleaseError('RELEASE_CHANNEL_INVALID');
  const normalizedArtifacts=artifacts.map(a=>{let safePath;try{safePath=normalizeRelativePath(requireString(a.path,'artifact.path'));}catch{throw new ReleaseError('RELEASE_ARTIFACT_PATH_INVALID');}return ({path:safePath,checksum:requireString(a.checksum,'artifact.checksum'),size_bytes:Number(a.size_bytes),mode:a.mode??'REPLACE'});});
  if(normalizedArtifacts.some(a=>!Number.isSafeInteger(a.size_bytes)||a.size_bytes<0)) throw new ReleaseError('RELEASE_ARTIFACT_SIZE_INVALID'); uniqBy(normalizedArtifacts,'path');
  const normalizedMigrations=migrations.map(m=>({migration_id:requireString(m.migration_id,'migration_id'),component:requireString(m.component,'component'),from_version:requireString(m.from_version,'from_version'),to_version:requireString(m.to_version,'to_version'),required:m.required!==false,broadens_authorization:Boolean(m.broadens_authorization),irreversible:Boolean(m.irreversible)})); uniqBy(normalizedMigrations,'migration_id');
  if(normalizedMigrations.some(m=>m.broadens_authorization)) throw new ReleaseError('RELEASE_MIGRATION_AUTHORIZATION_BROADENING');
  if(rollback_target) parseSemver(rollback_target);
  const manifest={release_manifest_version:'1.0.0',os_version,channel,created_at:nowIso(clock),artifacts:normalizedArtifacts,schemas:structuredClone(schemas),compatibility:structuredClone(compatibility),migrations:normalizedMigrations,security_profile:structuredClone(security_profile),sbom:sbom?structuredClone(sbom):null,dependency_inventory:dependency_inventory?structuredClone(dependency_inventory):null,rollback_target,release_notes};
  return deepFreeze({...manifest,manifest_checksum:sha256(stable(manifest))});
}
export async function signReleaseManifest(manifest,signer,{clock=()=>new Date()}={}){ const copy=structuredClone(manifest); delete copy.manifest_checksum; const expected=sha256(stable(copy)); if(manifest.manifest_checksum!==expected) throw new ReleaseError('RELEASE_MANIFEST_CHECKSUM_MISMATCH'); return signEnvelopeWithProvider(manifest,signer,{clock}); }
export function verifyReleaseManifestStructure(manifest){ if(manifest?.release_manifest_version!=='1.0.0') throw new ReleaseError('RELEASE_MANIFEST_VERSION_UNSUPPORTED'); parseSemver(manifest.os_version); const copy=structuredClone(manifest); for(const k of ['signature','signature_algorithm','key_id','signed_at','payload_checksum']) delete copy[k]; const checksum=copy.manifest_checksum; delete copy.manifest_checksum; if(checksum!==sha256(stable(copy))) throw new ReleaseError('RELEASE_MANIFEST_CHECKSUM_MISMATCH'); if(!Array.isArray(manifest.artifacts))throw new ReleaseError('RELEASE_MANIFEST_INVALID'); return true; }
export function verifyReleaseManifestSignature(manifest,trustAnchor,{allow_retired=true}={}){ verifyReleaseManifestStructure(manifest); if(!manifest.signature) throw new ReleaseError('RELEASE_SIGNATURE_REQUIRED'); if(trustAnchor.status!=='TRUSTED'&&!allow_retired) throw new ReleaseError('RELEASE_TRUST_ANCHOR_NOT_ACTIVE'); if(trustAnchor.status==='RETIRED'&&trustAnchor.retired_at&&new Date(manifest.signed_at).getTime()>new Date(trustAnchor.retired_at).getTime()) throw new ReleaseError('RELEASE_SIGNATURE_AFTER_KEY_RETIREMENT'); verifySignedEnvelope(manifest,{public_key:trustAnchor.public_key_pem,expected_key_id:trustAnchor.key_id}); return true; }
export function compareReleaseManifests(current,next){ verifyReleaseManifestStructure(next); if(!current)return deepFreeze({direction:'INSTALL',from:null,to:next.os_version}); verifyReleaseManifestStructure(current); const c=compareSemver(next.os_version,current.os_version); return deepFreeze({direction:c>0?'UPGRADE':c<0?'DOWNGRADE':'REINSTALL',from:current.os_version,to:next.os_version}); }
