import { ReleaseError } from './errors.mjs';
import { deepFreeze } from './util.mjs';
export class MigrationRegistry {
  constructor(){this.steps=new Map();}
  register({migration_id,component,from_version,to_version,apply,preview=null,broadens_authorization=false,irreversible=false}={}){ if(!migration_id||!component||!from_version||!to_version||typeof apply!=='function')throw new ReleaseError('RELEASE_MIGRATION_INVALID'); if(broadens_authorization)throw new ReleaseError('RELEASE_MIGRATION_AUTHORIZATION_BROADENING'); if(this.steps.has(migration_id))throw new ReleaseError('RELEASE_MIGRATION_DUPLICATE'); const step={migration_id,component,from_version,to_version,apply,preview,irreversible:Boolean(irreversible)};this.steps.set(migration_id,step);return this; }
  find(component,from,to){return [...this.steps.values()].find(s=>s.component===component&&s.from_version===from&&s.to_version===to)??null;}
  plan(manifest,currentSchemas={}){const plan=[];for(const m of manifest.migrations??[]){const current=currentSchemas[m.component];if(current===m.to_version)continue;if(current!==m.from_version)throw new ReleaseError('RELEASE_MIGRATION_SOURCE_MISMATCH',m.component);const step=this.find(m.component,m.from_version,m.to_version);if(!step&&m.required)throw new ReleaseError('RELEASE_MIGRATION_HANDLER_MISSING',m.migration_id);if(step)plan.push(step);}return deepFreeze(plan.map(({apply,preview,...x})=>x));}
  async apply(manifest,state={}){const result=structuredClone(state);for(const m of manifest.migrations??[]){if(result.schemas?.[m.component]===m.to_version)continue;const step=this.find(m.component,m.from_version,m.to_version);if(!step){if(m.required)throw new ReleaseError('RELEASE_MIGRATION_HANDLER_MISSING');continue;}const before=structuredClone(result);const next=await step.apply(before);if(!next||typeof next!=='object')throw new ReleaseError('RELEASE_MIGRATION_RESULT_INVALID',m.migration_id);Object.assign(result,next);result.schemas={...(result.schemas??{}),[m.component]:m.to_version};}return deepFreeze(result);}
}
