import assert from 'node:assert/strict';import test from 'node:test';import {mkdtemp,readFile,writeFile,symlink,rm,mkdir,readdir} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {initializeKnowledgeRepository,saveKnowledgeAssetRevision,loadCurrentKnowledgeAsset,listCurrentKnowledgeAssets,verifyKnowledgeRepository,reviseKnowledgeAsset} from '../../src/knowledge/index.mjs';import {asset,fixedClock} from './helpers.mjs';
const tmp=()=>mkdtemp(path.join(os.tmpdir(),'bai-knowledge-'));
const readdirSafe=async p=>readdir(p).catch(e=>e.code==='ENOENT'?[]:Promise.reject(e));
test('repository persists immutable revisions and current pointer',async()=>{const root=await tmp();try{await initializeKnowledgeRepository(root);const a=asset('KA-R1');await saveKnowledgeAssetRevision(root,a,{actor:'Builder',import_authorized:true});const b=reviseKnowledgeAsset(a,{content:{...a.content,summary:'v2'}},{clock:fixedClock('2026-08-09T00:00:00Z')});await saveKnowledgeAssetRevision(root,b,{actor:'KnowledgeReviewer'});assert.equal((await loadCurrentKnowledgeAsset(root,'KA-R1')).revision,2);assert.equal((await listCurrentKnowledgeAssets(root)).length,1);}finally{await rm(root,{recursive:true,force:true});}});
test('repository rejects revision gaps',async()=>{const root=await tmp();try{const a=asset('KA-R2');await saveKnowledgeAssetRevision(root,a,{import_authorized:true});const bad={...a,revision:3,updated_at:'2026-08-09T00:00:00Z',checksum:undefined};await assert.rejects(saveKnowledgeAssetRevision(root,bad),e=>e.code==='KNOWLEDGE_REVISION_SEQUENCE');}finally{await rm(root,{recursive:true,force:true});}});
test('repository event chain verifies',async()=>{const root=await tmp();try{await saveKnowledgeAssetRevision(root,asset('KA-R3'),{import_authorized:true});const v=await verifyKnowledgeRepository(root);assert.equal(v.result,'KNOWLEDGE_REPOSITORY_VERIFIED');assert.equal(v.event_count,1);}finally{await rm(root,{recursive:true,force:true});}});
test('repository detects event log tampering',async()=>{const root=await tmp();try{await saveKnowledgeAssetRevision(root,asset('KA-R4'),{import_authorized:true});const p=path.join(root,'event-log.jsonl');const events=(await readFile(p,'utf8')).trim().split('\n').map(JSON.parse);events[0].actor='attacker';await writeFile(p,events.map(JSON.stringify).join('\n')+'\n');await assert.rejects(verifyKnowledgeRepository(root),e=>e.code==='KNOWLEDGE_EVENT_CHAIN_INVALID');}finally{await rm(root,{recursive:true,force:true});}});
test('repository detects revision content tampering via checksum',async()=>{const root=await tmp();try{const a=asset('KA-R5');await saveKnowledgeAssetRevision(root,a,{import_authorized:true});const p=path.join(root,'assets','KA-R5','revisions','000001.json');const data=JSON.parse(await readFile(p,'utf8'));data.content.summary='tampered';await writeFile(p,JSON.stringify(data));await assert.rejects(loadCurrentKnowledgeAsset(root,'KA-R5'),e=>e.code==='KNOWLEDGE_CHECKSUM_MISMATCH');}finally{await rm(root,{recursive:true,force:true});}});
test('repository refuses symlinked asset directory escaping root',async()=>{const root=await tmp(),outside=await tmp();try{await initializeKnowledgeRepository(root);await mkdir(path.join(outside,'revisions'),{recursive:true});await writeFile(path.join(outside,'current.json'),JSON.stringify({revision:1}));await writeFile(path.join(outside,'revisions','000001.json'),'{}');await symlink(outside,path.join(root,'assets','KA-EVIL'));await assert.rejects(loadCurrentKnowledgeAsset(root,'KA-EVIL'),e=>e.code==='KNOWLEDGE_PATH_ESCAPE');}finally{await rm(root,{recursive:true,force:true});await rm(outside,{recursive:true,force:true});}});

test('repository blocks governance bypass for new ACTIVE asset',async()=>{const root=await tmp();try{await assert.rejects(saveKnowledgeAssetRevision(root,asset('KA-BYPASS')),e=>e.code==='KNOWLEDGE_GOVERNANCE_BYPASS_FORBIDDEN');}finally{await rm(root,{recursive:true,force:true});}});
test('repository detects current pointer rollback/tampering',async()=>{const root=await tmp();try{const a=asset('KA-PTR');await saveKnowledgeAssetRevision(root,a,{import_authorized:true});const b=reviseKnowledgeAsset(a,{content:{...a.content,summary:'v2'}},{clock:fixedClock('2026-08-09T00:00:00Z')});await saveKnowledgeAssetRevision(root,b);const pp=path.join(root,'assets','KA-PTR','current.json');const ptr=JSON.parse(await readFile(pp,'utf8'));ptr.revision=1;ptr.checksum=a.checksum;await writeFile(pp,JSON.stringify(ptr));await assert.rejects(verifyKnowledgeRepository(root),e=>e.code==='KNOWLEDGE_REPOSITORY_CURRENT_EVENT_MISMATCH');}finally{await rm(root,{recursive:true,force:true});}});
test('repository lock fails closed on concurrent mutation marker',async()=>{const root=await tmp();try{await initializeKnowledgeRepository(root);await writeFile(path.join(root,'.knowledge-repository.lock'),'busy');await assert.rejects(saveKnowledgeAssetRevision(root,asset('KA-R6')),e=>e.code==='KNOWLEDGE_REPOSITORY_BUSY');}finally{await rm(root,{recursive:true,force:true});}});

test('repository refuses writes through pre-created symlinked asset directory',async()=>{const root=await tmp(),outside=await tmp();try{await initializeKnowledgeRepository(root);await symlink(outside,path.join(root,'assets','KA-WRITE-EVIL'));await assert.rejects(saveKnowledgeAssetRevision(root,asset('KA-WRITE-EVIL'),{import_authorized:true}),e=>e.code==='KNOWLEDGE_PATH_ESCAPE');assert.equal((await readdirSafe(outside)).length,0);}finally{await rm(root,{recursive:true,force:true});await rm(outside,{recursive:true,force:true});}});
test('repository refuses symlinked event log escaping root',async()=>{const root=await tmp(),outside=await tmp();try{await mkdir(root,{recursive:true});await writeFile(path.join(outside,'events.txt'),'sentinel');await symlink(path.join(outside,'events.txt'),path.join(root,'event-log.jsonl'));await assert.rejects(initializeKnowledgeRepository(root),e=>e.code==='KNOWLEDGE_PATH_ESCAPE');assert.equal(await readFile(path.join(outside,'events.txt'),'utf8'),'sentinel');}finally{await rm(root,{recursive:true,force:true});await rm(outside,{recursive:true,force:true});}});
