import assert from 'node:assert/strict';import test from 'node:test';
import {authorizeKnowledgeTransition,applyKnowledgeTransition,evaluateScopeChange,applyScopeChange} from '../../src/knowledge/index.mjs';
import {asset,fixedClock,reviewerApproval,ownerApproval} from './helpers.mjs';

test('P12 reviewer can activate project advisory knowledge',()=>{const a=asset('KA-G1',{status:'UNDER_REVIEW',scope:{level:'PROJECT',project_id:'P1'}});const d=authorizeKnowledgeTransition({asset:a,target_status:'ACTIVE',actor_role:'KnowledgeReviewer',approvals:[reviewerApproval],reason:'reviewed'});assert.equal(applyKnowledgeTransition(a,d,{clock:fixedClock('2026-08-09T00:00:00Z')}).status,'ACTIVE');});
test('P12 global activation requires owner approval',()=>{const a=asset('KA-G2',{status:'UNDER_REVIEW'});assert.throws(()=>authorizeKnowledgeTransition({asset:a,target_status:'ACTIVE',actor_role:'KnowledgeReviewer',approvals:[reviewerApproval],reason:'reviewed'}),e=>e.code==='KNOWLEDGE_OWNER_APPROVAL_REQUIRED');});
test('P12 global activation succeeds with reviewer and owner',()=>{const a=asset('KA-G3',{status:'UNDER_REVIEW'});const d=authorizeKnowledgeTransition({asset:a,target_status:'ACTIVE',actor_role:'KnowledgeReviewer',approvals:[reviewerApproval,ownerApproval],reason:'reviewed'});assert.equal(d.authorized,true);});
test('P12 untrusted knowledge cannot become active',()=>{const a=asset('KA-G4',{status:'UNDER_REVIEW',scope:{level:'PROJECT',project_id:'P1'},source_trust:'UNTRUSTED'});assert.throws(()=>authorizeKnowledgeTransition({asset:a,target_status:'ACTIVE',actor_role:'KnowledgeReviewer',approvals:[reviewerApproval],reason:'reviewed'}),e=>e.code==='KNOWLEDGE_UNTRUSTED_ACTIVATION_FORBIDDEN');});
test('P12 archived status is terminal',()=>{const a=asset('KA-G5',{status:'ARCHIVED'});assert.throws(()=>authorizeKnowledgeTransition({asset:a,target_status:'ACTIVE',actor_role:'Owner',approvals:[reviewerApproval,ownerApproval],reason:'restore'}),e=>e.code==='KNOWLEDGE_STATUS_TRANSITION_INVALID');});
test('P10 scope promotion needs verified evidence',()=>{const a=asset('KA-P1',{scope:{level:'PROJECT',project_id:'P1'}});assert.throws(()=>evaluateScopeChange({asset:a,target_scope:{level:'DOMAIN',domain:'dev'},metrics:{verified_success_count:2},approvals:[reviewerApproval]}),e=>e.code==='KNOWLEDGE_PROMOTION_EVIDENCE_INSUFFICIENT');});
test('P10 global promotion requires diversity and owner',()=>{const a=asset('KA-P2',{scope:{level:'PROJECT',project_id:'P1'}});assert.throws(()=>evaluateScopeChange({asset:a,target_scope:{level:'GLOBAL'},metrics:{verified_success_count:4,distinct_projects:2},approvals:[reviewerApproval,ownerApproval]}),e=>e.code==='KNOWLEDGE_GLOBAL_PROMOTION_DIVERSITY_INSUFFICIENT');assert.throws(()=>evaluateScopeChange({asset:a,target_scope:{level:'GLOBAL'},metrics:{verified_success_count:4,distinct_projects:3},approvals:[reviewerApproval]}),e=>e.code==='KNOWLEDGE_OWNER_APPROVAL_REQUIRED');});
test('P10 approved promotion creates next revision',()=>{const a=asset('KA-P3',{scope:{level:'PROJECT',project_id:'P1'}});const d=evaluateScopeChange({asset:a,target_scope:{level:'DOMAIN',domain:'dev'},metrics:{verified_success_count:3,distinct_projects:1},approvals:[reviewerApproval]});const b=applyScopeChange(a,d,{clock:fixedClock('2026-08-09T00:00:00Z')});assert.equal(b.revision,2);assert.equal(b.scope.level,'DOMAIN');});
test('P10 demotion requires reviewer or owner authority',()=>{const a=asset('KA-D',{scope:{level:'DOMAIN',domain:'dev'}});assert.throws(()=>evaluateScopeChange({asset:a,target_scope:{level:'PROJECT',project_id:'P1'},approvals:[]}),e=>e.code==='KNOWLEDGE_REVIEW_APPROVAL_REQUIRED');});
