import assert from 'node:assert/strict';import test from 'node:test';import {mkdtemp,readFile,writeFile,rm,mkdir,symlink} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {createKnowledgeCandidateFromHandoff,findFailureKnowledgeDuplicates,resolveKnowledge,buildKnowledgePack,createKnowledgeUsageEvent,appendKnowledgeUsageEvent,listKnowledgeUsageEvents,verifyKnowledgeUsageLedger,saveKnowledgePackArtifact,loadKnowledgePackArtifact} from '../../src/knowledge/index.mjs';
import {asset,fixedClock} from './helpers.mjs';
const tmp=()=>mkdtemp(path.join(os.tmpdir(),'bai-knowledge-ledger-'));
test('candidate handoff creates CANDIDATE without activating knowledge',()=>{const c=createKnowledgeCandidateFromHandoff({candidate_id:'C-1',title:'Lesson',project_id:'P1',source_task:'TASK-004',summary:'Observed lesson',evidence_refs:['tasks/TASK-004/evidence.md']},{clock:fixedClock()});assert.equal(c.status,'CANDIDATE');assert.equal(c.scope.project_id,'P1');});
test('failure fingerprint finds duplicate candidates/assets',()=>{const failure={fingerprint:'fp-1',failure_mode:'wrong runtime inference',safe_action:'probe runtime',evidence_refs:['e.md']};const a=asset('KA-F1',{knowledge_type:'FAILURE_CASE',failure});const b=asset('KA-F2',{knowledge_type:'FAILURE_CASE',failure});assert.equal(findFailureKnowledgeDuplicates(a,[a,b]).length,1);});
test('usage ledger persists and verifies append-only records',async()=>{const root=await tmp();try{const a=asset('KA-L1');const resolution=resolveKnowledge({task_id:'T',role:'Builder',phase:'I',scope:{},sensitivity:'INTERNAL',token_budget:1000,now:'2026-08-08T00:00:00Z'},[a]);const pack=buildKnowledgePack({resolution,assets:[a],pack_id:'KP-L1',clock:fixedClock()});const event=createKnowledgeUsageEvent({event_id:'UE-L1',pack,asset_id:a.asset_id,task_id:'T',action:'APPLIED',verification:'PASS'});await appendKnowledgeUsageEvent(root,event);assert.equal((await listKnowledgeUsageEvents(root)).length,1);assert.equal((await verifyKnowledgeUsageLedger(root)).event_count,1);}finally{await rm(root,{recursive:true,force:true});}});
test('usage ledger detects tampering',async()=>{const root=await tmp();try{const a=asset('KA-L2');const resolution=resolveKnowledge({task_id:'T',role:'Builder',phase:'I',scope:{},sensitivity:'INTERNAL',token_budget:1000,now:'2026-08-08T00:00:00Z'},[a]);const pack=buildKnowledgePack({resolution,assets:[a],pack_id:'KP-L2',clock:fixedClock()});const event=createKnowledgeUsageEvent({event_id:'UE-L2',pack,asset_id:a.asset_id,task_id:'T',action:'APPLIED',verification:'PASS'});await appendKnowledgeUsageEvent(root,event);const p=path.join(root,'usage-log.jsonl');const row=JSON.parse((await readFile(p,'utf8')).trim());row.payload.action='DEVIATED';await writeFile(p,JSON.stringify(row)+'\n');await assert.rejects(verifyKnowledgeUsageLedger(root),e=>['KNOWLEDGE_LEDGER_CHAIN_INVALID','KNOWLEDGE_LEDGER_PAYLOAD_INVALID'].includes(e.code));}finally{await rm(root,{recursive:true,force:true});}});
test('knowledge pack artifacts are immutable and checksum verified',async()=>{const root=await tmp();try{const a=asset('KA-L3');const resolution=resolveKnowledge({task_id:'T',role:'Builder',phase:'I',scope:{},sensitivity:'INTERNAL',token_budget:1000,now:'2026-08-08T00:00:00Z'},[a]);const pack=buildKnowledgePack({resolution,assets:[a],pack_id:'KP-L3',clock:fixedClock()});await saveKnowledgePackArtifact(root,pack);assert.equal((await loadKnowledgePackArtifact(root,'KP-L3')).checksum,pack.checksum);await assert.rejects(saveKnowledgePackArtifact(root,pack),e=>e.code==='KNOWLEDGE_PACK_ALREADY_EXISTS');}finally{await rm(root,{recursive:true,force:true});}});

test('usage ledger refuses symlink escape writes',async()=>{const root=await tmp(),outside=await tmp();try{await mkdir(root,{recursive:true});const target=path.join(outside,'usage.txt');await writeFile(target,'sentinel');await symlink(target,path.join(root,'usage-log.jsonl'));const a=asset('KA-L4');const resolution=resolveKnowledge({task_id:'T',role:'Builder',phase:'I',scope:{},sensitivity:'INTERNAL',token_budget:1000,now:'2026-08-08T00:00:00Z'},[a]);const pack=buildKnowledgePack({resolution,assets:[a],pack_id:'KP-L4',clock:fixedClock()});const event=createKnowledgeUsageEvent({event_id:'UE-L4',pack,asset_id:a.asset_id,task_id:'T',action:'APPLIED',verification:'PASS'});await assert.rejects(appendKnowledgeUsageEvent(root,event),e=>e.code==='KNOWLEDGE_PATH_ESCAPE');assert.equal(await readFile(target,'utf8'),'sentinel');}finally{await rm(root,{recursive:true,force:true});await rm(outside,{recursive:true,force:true});}});
test('knowledge pack persistence refuses symlinked pack directory',async()=>{const root=await tmp(),outside=await tmp();try{await mkdir(root,{recursive:true});await symlink(outside,path.join(root,'packs'));const a=asset('KA-L5');const resolution=resolveKnowledge({task_id:'T',role:'Builder',phase:'I',scope:{},sensitivity:'INTERNAL',token_budget:1000,now:'2026-08-08T00:00:00Z'},[a]);const pack=buildKnowledgePack({resolution,assets:[a],pack_id:'KP-L5',clock:fixedClock()});await assert.rejects(saveKnowledgePackArtifact(root,pack),e=>e.code==='KNOWLEDGE_PATH_ESCAPE');}finally{await rm(root,{recursive:true,force:true});await rm(outside,{recursive:true,force:true});}});
